'\" t
.TH "BOOTCTL" "1" "" "systemd 221" "bootctl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bootctl \- Control the firmware and boot manager settings
.SH "SYNOPSIS"
.HP \w'\fBbootctl\ \fR\fB[OPTIONS...]\fR\fBstatus\fR\ 'u
\fBbootctl \fR\fB[OPTIONS...]\fR\fBstatus\fR
.HP \w'\fBbootctl\ \fR\fB[OPTIONS...]\fR\fBupdate\fR\ 'u
\fBbootctl \fR\fB[OPTIONS...]\fR\fBupdate\fR
.HP \w'\fBbootctl\ \fR\fB[OPTIONS...]\fR\fBinstall\fR\ 'u
\fBbootctl \fR\fB[OPTIONS...]\fR\fBinstall\fR
.HP \w'\fBbootctl\ \fR\fB[OPTIONS...]\fR\fBremove\fR\ 'u
\fBbootctl \fR\fB[OPTIONS...]\fR\fBremove\fR
.SH "DESCRIPTION"
.PP
\fBbootctl\fR
checks, updates, installs or removes the boot loader from the current system\&.
.PP
\fBbootctl status\fR
checks and prints the currently installed versions of the boot loader binaries and the all current EFI boot variables\&.
.PP
\fBbootctl update\fR
updates all installed versions of systemd\-boot, if the current version is newer than the version installed in the EFI system partition\&. This also includes the EFI default/fallback loader at /EFI/Boot/boot*\&.efi\&. A systemd\-boot entry in the EFI boot variables is created, if there is no current entry\&. The created entry will be added to the end of the boot order list\&.
.PP
\fBbootctl install\fR
installs systemd\-boot into the EFI system partition\&. A copy of systemd\-boot will be stored as the EFI default/fallback loader at /EFI/Boot/boot*\&.efi\&. A systemd\-boot entry in the EFI boot variables is created and added to the top of the boot order list\&.
.PP
\fBbootctl remove\fR
removes all installed versions of systemd\-boot from the EFI system partition, and removes systemd\-boot from the EFI boot variables\&.
.PP
If no command is passed
\fBstatus\fR
is implied\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.PP
\fB\-\-path\fR
.RS 4
Path to the EFI system partition\&. The default is /boot\&.
.RE
.PP
\fB\-\-no\-variables\fR
.RS 4
Do not touch the EFI boot variables\&.
.RE
.SH "EXIT STATUS"
.PP
On success 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\m[blue]\fBBoot loader specification\fR\m[]\&\s-2\u[1]\d\s+2\m[blue]\fBSystemd boot loader interface\fR\m[]\&\s-2\u[2]\d\s+2
.SH "NOTES"
.IP " 1." 4
Boot loader specification
.RS 4
\%http://www.freedesktop.org/wiki/Specifications/BootLoaderSpec
.RE
.IP " 2." 4
Systemd boot loader interface
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/BootLoaderInterface
.RE
