'\" t
.TH "BOOTCHART\&.CONF" "5" "" "systemd 221" "bootchart.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bootchart.conf, bootchart.conf.d \- Boot performance analysis graphing tool configuration files
.SH "SYNOPSIS"
.PP
/etc/systemd/bootchart\&.conf
.PP
/etc/systemd/bootchart\&.conf\&.d/*\&.conf
.PP
/run/systemd/bootchart\&.conf\&.d/*\&.conf
.PP
/usr/lib/systemd/bootchart\&.conf\&.d/*\&.conf
.SH "DESCRIPTION"
.PP
When starting, systemd\-bootchart will read the configuration file
/etc/systemd/bootchart\&.conf, followed by the files in the
bootchart\&.conf\&.d
directories\&. These configuration files determine logging parameters and graph output\&.
.SH "CONFIGURATION DIRECTORIES AND PRECEDENCE"
.PP
Default configuration is defined during compilation, so a configuration file is only needed when it is necessary to deviate from those defaults\&. By default the configuration file in
/etc/systemd/
contains commented out entries showing the defaults as a guide to the administrator\&. This file can be edited to create local overrides\&.
.PP
When packages need to customize the configuration, they can install configuration snippets in
/usr/lib/systemd/*\&.conf\&.d/\&. Files in
/etc/
are reserved for the local administrator, who may use this logic to override the configuration files installed by vendor packages\&. The main configuration file is read before any of the configuration directories, and has the lowest precedence; entries in a file in any configuration directory override entries in the single configuration file\&. Files in the
*\&.conf\&.d/
configuration subdirectories are sorted by their filename in lexicographic order, regardless of which of the subdirectories they reside in\&. If multiple files specify the same option, the entry in the file with the lexicographically latest name takes precedence\&. It is recommended to prefix all filenames in those subdirectories with a two\-digit number and a dash, to simplify the ordering of the files\&.
.PP
To disable a configuration file supplied by the vendor, the recommended way is to place a symlink to
/dev/null
in the configuration directory in
/etc/, with the same filename as the vendor configuration file\&.
.SH "OPTIONS"
.PP
\fISamples=500\fR
.RS 4
Configure the amount of samples to record in total before bootchart exits\&. Each sample will record at intervals defined by Frequency=\&.
.RE
.PP
\fIFrequency=25\fR
.RS 4
Configure the sample log frequency\&. This can be a fractional number, but must be larger than 0\&.0\&. Most systems can cope with values under 25\-50 without impacting boot time severely\&.
.RE
.PP
\fIRelative=no\fR
.RS 4
Configures whether the left axis of the output graph equals time=0\&.0 (\fBCLOCK_MONOTONIC\fR
start)\&. This is useful for using bootchart at post\-boot time to profile an already booted system, otherwise the graph would become extremely large\&. If set to yes, the horizontal axis starts at the first recorded sample instead of time=0\&.0\&.
.RE
.PP
\fIFilter=no\fR
.RS 4
Configures whether the resulting graph should omit tasks that did not contribute significantly to the boot\&. Processes that are too short\-lived (only seen in one sample) or that do not consume any significant CPU time (less than 0\&.001sec) will not be displayed in the output graph\&.
.RE
.PP
\fIOutput=[path]\fR
.RS 4
Configures the output directory for writing the graphs\&. By default, bootchart writes the graphs to
/run/log\&.
.RE
.PP
\fIInit=[path]\fR
.RS 4
Configures bootchart to run a non\-standard binary instead of
/usr/lib/systemd/systemd\&. This option is only relevant if bootchart was invoked from the kernel command line with init=/usr/lib/systemd/systemd\-bootchart\&.
.RE
.PP
\fIPlotMemoryUsage=no\fR
.RS 4
If set to yes, enables logging and graphing of processes\*(Aq PSS memory consumption\&.
.RE
.PP
\fIPlotEntropyGraph=no\fR
.RS 4
If set to yes, enables logging and graphing of the kernel random entropy pool size\&.
.RE
.PP
\fIScaleX=100\fR
.RS 4
Horizontal scaling factor for all variable graph components\&.
.RE
.PP
\fIScaleY=20\fR
.RS 4
Vertical scaling factor for all variable graph components\&.
.RE
.PP
\fIControlGroup=no\fR
.RS 4
Display process control group\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd-bootchart\fR(1),
\fBsystemd.directives\fR(7)
