'\" t
.TH "BUSCTL" "1" "" "systemd 220" "busctl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
busctl \- Introspect the bus
.SH "SYNOPSIS"
.HP \w'\fBbusctl\fR\ 'u
\fBbusctl\fR [OPTIONS...] [COMMAND] [\fINAME\fR...]
.SH "DESCRIPTION"
.PP
\fBbusctl\fR
may be used to introspect and monitor the D\-Bus bus\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-address=\fR\fB\fIADDRESS\fR\fR
.RS 4
Connect to the bus specified by
\fIADDRESS\fR
instead of using suitable defaults for either the system or user bus (see
\fB\-\-system\fR
and
\fB\-\-user\fR
options)\&.
.RE
.PP
\fB\-\-show\-machine\fR
.RS 4
When showing the list of endpoints, show a column containing the names of containers they belong to\&. See
\fBsystemd-machined.service\fR(8)\&.
.RE
.PP
\fB\-\-unique\fR
.RS 4
When showing the list of endpoints, show only "unique" names (of the form
":\fInumber\fR\&.\fInumber\fR")\&.
.RE
.PP
\fB\-\-acquired\fR
.RS 4
The opposite of
\fB\-\-unique\fR
\(em only "well\-known" names will be shown\&.
.RE
.PP
\fB\-\-activatable\fR
.RS 4
When showing the list of endpoints, show only endpoints which have actually not been activated yet, but may be started automatically if accessed\&.
.RE
.PP
\fB\-\-match=\fR\fB\fIMATCH\fR\fR
.RS 4
When showing messages being exchanged, show only the subset matching
\fIMATCH\fR\&.
.RE
.PP
\fB\-\-size=\fR
.RS 4
When used with the
\fBcapture\fR
command specifies the maximum bus message size to capture ("snaplen")\&. Defaults to 4096 bytes\&.
.RE
.PP
\fB\-\-list\fR
.RS 4
When used with the
\fBtree\fR
command shows a flat list of object paths instead of a tree\&.
.RE
.PP
\fB\-\-quiet\fR
.RS 4
When used with the
\fBcall\fR
command suppresses display of the response message payload\&. Note that even if this option is specified errors returned will still be printed and the tool will indicate success or failure with the process exit code\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
When used with the
\fBcall\fR
or
\fBget\-property\fR
command shows output in a more verbose format\&.
.RE
.PP
\fB\-\-expect\-reply=\fR\fIBOOL\fR
.RS 4
When used with the
\fBcall\fR
command specifies whether
\fBbusctl\fR
shall wait for completion of the method call, output the returned method response data, and return success or failure via the process exit code\&. If this is set to
"no"
the method call will be issued but no response is expected, the tool terminates immediately, and thus no response can be shown, and no success or failure is returned via the exit code\&. To only suppress output of the reply message payload use
\fB\-\-quiet\fR
above\&. Defaults to
"yes"\&.
.RE
.PP
\fB\-\-auto\-start=\fR\fIBOOL\fR
.RS 4
When used with the
\fBcall\fR
command specifies whether the method call should implicitly activate the called service should it not be running yet but is configured to be auto\-started\&. Defaults to
"yes"\&.
.RE
.PP
\fB\-\-allow\-interactive\-authorization=\fR\fIBOOL\fR
.RS 4
When used with the
\fBcall\fR
command specifies whether the services may enforce interactive authorization while executing the operation, if the security policy is configured for this\&. Defaults to
"yes"\&.
.RE
.PP
\fB\-\-timeout=\fR\fISECS\fR
.RS 4
When used with the
\fBcall\fR
command specifies the maximum time to wait for method call completion\&. If no time unit is specified assumes seconds\&. The usual other units are understood, too (ms, us, s, min, h, d, w, month, y)\&. Note that this timeout does not apply if
\fB\-\-expect\-reply=no\fR
is used as the tool does not wait for any reply message then\&. When not specified or when set to 0 the default of
"25s"
is assumed\&.
.RE
.PP
\fB\-\-augment\-creds=\fR\fIBOOL\fR
.RS 4
Controls whether credential data reported by
\fBlist\fR
or
\fBstatus\fR
shall be augmented with data from
/proc\&. When this is turned on the data shown is possibly inconsistent, as the data read from
/proc
might be more recent than rest of the credential information\&. Defaults to
"yes"\&.
.RE
.PP
\fB\-\-user\fR
.RS 4
Talk to the service manager of the calling user, rather than the service manager of the system\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
Talk to the service manager of the system\&. This is the implied default\&.
.RE
.PP
\fB\-H\fR, \fB\-\-host=\fR
.RS 4
Execute the operation remotely\&. Specify a hostname, or a username and hostname separated by
"@", to connect to\&. The hostname may optionally be suffixed by a container name, separated by
":", which connects directly to a specific container on the specified host\&. This will use SSH to talk to the remote machine manager instance\&. Container names may be enumerated with
\fBmachinectl \-H \fR\fB\fIHOST\fR\fR\&.
.RE
.PP
\fB\-M\fR, \fB\-\-machine=\fR
.RS 4
Execute operation on a local container\&. Specify a container name to connect to\&.
.RE
.PP
\fB\-\-no\-pager\fR
.RS 4
Do not pipe output into a pager\&.
.RE
.PP
\fB\-\-no\-legend\fR
.RS 4
Do not print the legend, i\&.e\&. column headers and the footer with hints\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "COMMANDS"
.PP
The following commands are understood:
.PP
\fBlist\fR
.RS 4
Show service names on the bus\&. This is the default if no command is specified\&.
.RE
.PP
\fBstatus\fR [\fISERVICE\fR]
.RS 4
Show process information and credentials of a bus service (if one is specified by its unique or well\-known name), a process (if one is specified by its numeric PID), or the owner of the bus (if no parameter is specified)\&.
.RE
.PP
\fBmonitor\fR [\fISERVICE\fR...]
.RS 4
Dump messages being exchanged\&. If
\fISERVICE\fR
is specified, show messages to or from this endpoint\&. Otherwise, show all messages on the bus\&. Use Ctrl\-C to terminate dump\&.
.RE
.PP
\fBcapture\fR [\fISERVICE\fR...]
.RS 4
Similar to
\fBmonitor\fR
but writes the output in pcap format (for details see the
\m[blue]\fBLibpcap File Format\fR\m[]\&\s-2\u[1]\d\s+2
description\&. Make sure to redirect the output to STDOUT to a file\&. Tools like
\fBwireshark\fR(1)
may be used to dissect and view the generated files\&.
.RE
.PP
\fBtree\fR [\fISERVICE\fR...]
.RS 4
Shows an object tree of one or more services\&. If
\fISERVICE\fR
is specified, show object tree of the specified services only\&. Otherwise, show all object trees of all services on the bus that acquired at least one well\-known name\&.
.RE
.PP
\fBintrospect\fR \fISERVICE\fR \fIOBJECT\fR [\fIINTERFACE\fR]
.RS 4
Show interfaces, methods, properties and signals of the specified object (identified by its path) on the specified service\&. If the interface argument is passed the output is limited to members of the specified interface\&.
.RE
.PP
\fBcall\fR \fISERVICE\fR \fIOBJECT\fR \fIINTERFACE\fR \fIMETHOD\fR [\fISIGNATURE\fR\ [\fIARGUMENT\fR...]]
.RS 4
Invoke a method and show the response\&. Takes a service name, object path, interface name and method name\&. If parameters shall be passed to the method call a signature string is required, followed by the arguments, individually formatted as strings\&. For details on the formatting used, see below\&. To suppress output of the returned data use the
\fB\-\-quiet\fR
option\&.
.RE
.PP
\fBget\-property\fR \fISERVICE\fR \fIOBJECT\fR \fIINTERFACE\fR \fIPROPERTY\fR...
.RS 4
Retrieve the current value of one or more object properties\&. Takes a service name, object path, interface name and property name\&. Multiple properties may be specified at once in which case their values will be shown one after the other, separated by newlines\&. The output is by default in terse format\&. Use
\fB\-\-verbose\fR
for a more elaborate output format\&.
.RE
.PP
\fBset\-property\fR \fISERVICE\fR \fIOBJECT\fR \fIINTERFACE\fR \fIPROPERTY\fR \fISIGNATURE\fR \fIARGUMENT\fR...
.RS 4
Set the current value an object property\&. Takes a service name, object path, interface name, property name, property signature, followed by a list of parameters formatted as strings\&.
.RE
.PP
\fBhelp\fR
.RS 4
Show command syntax help\&.
.RE
.SH "PARAMETER FORMATTING"
.PP
The
\fBcall\fR
and
\fBset\-property\fR
commands take a signature string followed by a list of parameters formatted as string (for details on D\-Bus signature strings see the
\m[blue]\fBType system chapter of the D\-Bus specification\fR\m[]\&\s-2\u[2]\d\s+2)\&. For simple types each parameter following the signature should simply be the parameter\*(Aqs value formatted as string\&. Positive boolean values may be formatted as
"true",
"yes",
"on",
"1"; negative boolean values may be specified as
"false",
"no",
"off",
"0"\&. For arrays, a numeric argument for the number of entries followed by the entries shall be specified\&. For variants the signature of the contents shall be specified, followed by the contents\&. For dictionaries and structs the contents of them shall be directly specified\&.
.PP
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
s jawoll
.fi
.if n \{\
.RE
.\}
.sp
is the formatting of a single string
"jawoll"\&.
.PP
.if n \{\
.RS 4
.\}
.nf
as 3 hello world foobar
.fi
.if n \{\
.RE
.\}
.sp
is the formatting of a string array with three entries,
"hello",
"world"
and
"foobar"\&.
.PP
.if n \{\
.RS 4
.\}
.nf
a{sv} 3 One s Eins Two u 2 Yes b true
.fi
.if n \{\
.RE
.\}
.sp
is the formatting of a dictionary array that maps strings to variants, consisting of three entries\&. The string
"One"
is assigned the string
"Eins"\&. The string
"Two"
is assigned the 32bit unsigned integer 2\&. The string
"Yes"
is assigned a positive boolean\&.
.PP
Note that the
\fBcall\fR,
\fBget\-property\fR,
\fBintrospect\fR
commands will also generate output in this format for the returned data\&. Since this format is sometimes too terse to be easily understood, the
\fBcall\fR
and
\fBget\-property\fR
commands may generate a more verbose, multi\-line output when passed the
\fB\-\-verbose\fR
option\&.
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&Write and Read a Property\fR
.PP
The following two commands first write a property and then read it back\&. The property is found on the
"/org/freedesktop/systemd1"
object of the
"org\&.freedesktop\&.systemd1"
service\&. The name of the property is
"LogLevel"
on the
"org\&.freedesktop\&.systemd1\&.Manager"
interface\&. The property contains a single string:
.sp
.if n \{\
.RS 4
.\}
.nf
# busctl set\-property org\&.freedesktop\&.systemd1 /org/freedesktop/systemd1 org\&.freedesktop\&.systemd1\&.Manager LogLevel s debug
# busctl get\-property org\&.freedesktop\&.systemd1 /org/freedesktop/systemd1 org\&.freedesktop\&.systemd1\&.Manager LogLevel
s "debug"
.fi
.if n \{\
.RE
.\}
.PP
\fBExample\ \&2.\ \&Terse and Verbose Output\fR
.PP
The following two commands read a property that contains an array of strings, and first show it in terse format, followed by verbose format:
.sp
.if n \{\
.RS 4
.\}
.nf
$ busctl get\-property org\&.freedesktop\&.systemd1 /org/freedesktop/systemd1 org\&.freedesktop\&.systemd1\&.Manager Environment
as 2 "LANG=en_US\&.UTF\-8" "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
$ busctl get\-property \-\-verbose org\&.freedesktop\&.systemd1 /org/freedesktop/systemd1 org\&.freedesktop\&.systemd1\&.Manager Environment
ARRAY "s" {
        STRING "LANG=en_US\&.UTF\-8";
        STRING "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin";
};
.fi
.if n \{\
.RE
.\}
.PP
\fBExample\ \&3.\ \&Invoking a Method\fR
.PP
The following command invokes a the
"StartUnit"
method on the
"org\&.freedesktop\&.systemd1\&.Manager"
interface of the
"/org/freedesktop/systemd1"
object of the
"org\&.freedesktop\&.systemd1"
service, and passes it two strings
"cups\&.service"
and
"replace"\&. As result of the method call a single object path parameter is received and shown:
.sp
.if n \{\
.RS 4
.\}
.nf
# busctl call org\&.freedesktop\&.systemd1 /org/freedesktop/systemd1 org\&.freedesktop\&.systemd1\&.Manager StartUnit ss "cups\&.service" "replace"
o "/org/freedesktop/systemd1/job/42684"
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBdbus-daemon\fR(1),
\m[blue]\fBD\-Bus\fR\m[]\&\s-2\u[3]\d\s+2,
\m[blue]\fBkdbus\fR\m[]\&\s-2\u[4]\d\s+2,
\fBsd-bus\fR(3),
\fBsystemd\fR(1),
\fBsystemd-bus-proxyd\fR(8),
\fBmachinectl\fR(1),
\fBwireshark\fR(1)
.SH "NOTES"
.IP " 1." 4
Libpcap File Format
.RS 4
\%http://wiki.wireshark.org/Development/LibpcapFileFormat
.RE
.IP " 2." 4
Type system chapter of the D-Bus specification
.RS 4
\%http://dbus.freedesktop.org/doc/dbus-specification.html#type-system
.RE
.IP " 3." 4
D-Bus
.RS 4
\%http://freedesktop.org/wiki/Software/dbus
.RE
.IP " 4." 4
kdbus
.RS 4
\%https://code.google.com/p/d-bus/
.RE
