'\" t
.TH "COREDUMP\&.CONF" "5" "" "systemd 220" "coredump.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
coredump.conf, coredump.conf.d \- Coredump storage configuration files
.SH "SYNOPSIS"
.PP
/etc/systemd/coredump\&.conf
.PP
/etc/systemd/coredump\&.conf\&.d/*\&.conf
.PP
/run/systemd/coredump\&.conf\&.d/*\&.conf
.PP
/usr/lib/systemd/coredump\&.conf\&.d/*\&.conf
.SH "DESCRIPTION"
.PP
These files configure the behaviour of
\fBsystemd-coredump\fR(8), a handler for core dumps invoked by the kernel\&.
.SH "CONFIGURATION DIRECTORIES AND PRECEDENCE"
.PP
Default configuration is defined during compilation, so a configuration file is only needed when it is necessary to deviate from those defaults\&. By default the configuration file in
/etc/systemd/
contains commented out entries showing the defaults as a guide to the administrator\&. This file can be edited to create local overrides\&.
.PP
When packages need to customize the configuration, they can install configuration snippets in
/usr/lib/systemd/*\&.conf\&.d/\&. Files in
/etc/
are reserved for the local administrator, who may use this logic to override the configuration files installed by vendor packages\&. The main configuration file is read before any of the configuration directories, and has the lowest precedence; entries in a file in any configuration directory override entries in the single configuration file\&. Files in the
*\&.conf\&.d/
configuration subdirectories are sorted by their filename in lexicographic order, regardless of which of the subdirectories they reside in\&. If multiple files specify the same option, the entry in the file with the lexicographically latest name takes precedence\&. It is recommended to prefix all filenames in those subdirectories with a two\-digit number and a dash, to simplify the ordering of the files\&.
.PP
To disable a configuration file supplied by the vendor, the recommended way is to place a symlink to
/dev/null
in the configuration directory in
/etc/, with the same filename as the vendor configuration file\&.
.SH "OPTIONS"
.PP
All options are configured in the
"[Coredump]"
section:
.PP
\fIStorage=\fR
.RS 4
Controls where to store cores\&. One of
"none",
"external",
"journal", and
"both"\&. When
"none", the coredumps will be logged but not stored permanently\&. When
"external"
(the default), cores will be stored in
/var/lib/systemd/coredump\&. When
"journal", cores will be stored in the journal and rotated following normal journal rotation patterns\&. When
"both", cores will be stored in both locations\&.
.sp
When cores are stored in the journal, they might be compressed following journal compression settings, see
\fBjournald.conf\fR(5)\&. When cores are stored externally, they will be compressed by default, see below\&.
.RE
.PP
\fICompress=\fR
.RS 4
Controls compression for external storage\&. Takes a boolean argument, defaults to
"yes"\&.
.RE
.PP
\fIProcessSizeMax=\fR
.RS 4
The maximum size in bytes of a core which will be processed\&. Coredumps exceeding this size will be logged, but the backtrace will not be generated and the core will not be stored\&.
.RE
.PP
\fIExternalSizeMax=\fR, \fIJournalSizeMax=\fR
.RS 4
The maximum (uncompressed) size in bytes of a core to be saved\&.
.RE
.PP
\fIMaxUse=\fR, \fIKeepFree=\fR
.RS 4
Enforce limits on the disk space taken up by externally stored coredumps\&.
\fBMaxUse=\fR
makes sure that old coredumps are removed as soon as the total disk space taken up by coredumps grows beyond this limit (defaults to 10% of the total disk size)\&.
\fBKeepFree=\fR
controls how much disk space to keep free at least (defaults to 15% of the total disk size)\&. Note that the disk space used by coredumps might temporarily exceed these limits while coredumps are processed\&. Note that old coredumps are also removed based on time via
\fBsystemd-tmpfiles\fR(8)\&. Set either value to 0 to turn off size based clean\-up\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd-journald.service\fR(8),
\fBcoredumpctl\fR(1),
\fBsystemd-tmpfiles\fR(8)
