'\" t
.TH "HALT" "8" "" "systemd 220" "halt"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
halt, poweroff, reboot \- Halt, power\-off or reboot the machine
.SH "SYNOPSIS"
.HP \w'\fBhalt\fR\ 'u
\fBhalt\fR [OPTIONS...]
.HP \w'\fBpoweroff\fR\ 'u
\fBpoweroff\fR [OPTIONS...]
.HP \w'\fBreboot\fR\ 'u
\fBreboot\fR [OPTIONS...]
.SH "DESCRIPTION"
.PP
\fBhalt\fR,
\fBpoweroff\fR,
\fBreboot\fR
may be used to halt, power\-off or reboot the machine\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-halt\fR
.RS 4
Halt the machine, regardless of which one of the three commands is invoked\&.
.RE
.PP
\fB\-p\fR, \fB\-\-poweroff\fR
.RS 4
Power\-off the machine, regardless of which one of the three commands is invoked\&.
.RE
.PP
\fB\-\-reboot\fR
.RS 4
Reboot the machine, regardless of which one of the three commands is invoked\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Force immediate halt, power\-off, reboot\&. Do not contact the init system\&.
.RE
.PP
\fB\-w\fR, \fB\-\-wtmp\-only\fR
.RS 4
Only write wtmp shutdown entry, do not actually halt, power\-off, reboot\&.
.RE
.PP
\fB\-d\fR, \fB\-\-no\-wtmp\fR
.RS 4
Do not write wtmp shutdown entry\&.
.RE
.PP
\fB\-\-no\-wall\fR
.RS 4
Do not send wall message before halt, power\-off, reboot\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "NOTES"
.PP
These are legacy commands available for compatibility only\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBshutdown\fR(8),
\fBwall\fR(1)
