'\" t
.TH "JOURNALD\&.CONF" "5" "" "systemd 215" "journald.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
journald.conf \- Journal service configuration file
.SH "SYNOPSIS"
.PP
/etc/systemd/journald\&.conf
.SH "DESCRIPTION"
.PP
This file configures various parameters of the systemd journal service,
\fBsystemd-journald.service\fR(8)\&.
.SH "OPTIONS"
.PP
All options are configured in the
"[Journal]"
section:
.PP
\fIStorage=\fR
.RS 4
Controls where to store journal data\&. One of
"volatile",
"persistent",
"auto"
and
"none"\&. If
"volatile", journal log data will be stored only in memory, i\&.e\&. below the
/run/log/journal
hierarchy (which is created if needed)\&. If
"persistent", data will be stored preferably on disk, i\&.e\&. below the
/var/log/journal
hierarchy (which is created if needed), with a fallback to
/run/log/journal
(which is created if needed), during early boot and if the disk is not writable\&.
"auto"
is similar to
"persistent"
but the directory
/var/log/journal
is not created if needed, so that its existence controls where log data goes\&.
"none"
turns off all storage, all log data received will be dropped\&. Forwarding to other targets, such as the console, the kernel log buffer or a syslog daemon will still work however\&. Defaults to
"auto"\&.
.RE
.PP
\fICompress=\fR
.RS 4
Takes a boolean value\&. If enabled (the default), data objects that shall be stored in the journal and are larger than a certain threshold are compressed with the XZ compression algorithm before they are written to the file system\&.
.RE
.PP
\fISeal=\fR
.RS 4
Takes a boolean value\&. If enabled (the default), and a sealing key is available (as created by
\fBjournalctl\fR(1)\*(Aqs
\fB\-\-setup\-keys\fR
command), Forward Secure Sealing (FSS) for all persistent journal files is enabled\&. FSS is based on
\m[blue]\fBSeekable Sequential Key Generators\fR\m[]\&\s-2\u[1]\d\s+2
by G\&. A\&. Marson and B\&. Poettering (doi:10\&.1007/978\-3\-642\-40203\-6_7) and may be used to protect journal files from unnoticed alteration\&.
.RE
.PP
\fISplitMode=\fR
.RS 4
Controls whether to split up journal files per user\&. One of
"uid",
"login"
and
"none"\&. If
"uid", all users will get each their own journal files regardless of whether they possess a login session or not, however system users will log into the system journal\&. If
"login", actually logged\-in users will get each their own journal files, but users without login session and system users will log into the system journal\&. If
"none", journal files are not split up by user and all messages are instead stored in the single system journal\&. Note that splitting up journal files by user is only available for journals stored persistently\&. If journals are stored on volatile storage (see above), only a single journal file for all user IDs is kept\&. Defaults to
"uid"\&.
.RE
.PP
\fIRateLimitInterval=\fR, \fIRateLimitBurst=\fR
.RS 4
Configures the rate limiting that is applied to all messages generated on the system\&. If, in the time interval defined by
\fIRateLimitInterval=\fR, more messages than specified in
\fIRateLimitBurst=\fR
are logged by a service, all further messages within the interval are dropped until the interval is over\&. A message about the number of dropped messages is generated\&. This rate limiting is applied per\-service, so that two services which log do not interfere with each other\*(Aqs limits\&. Defaults to 1000 messages in 30s\&. The time specification for
\fIRateLimitInterval=\fR
may be specified in the following units:
"s",
"min",
"h",
"ms",
"us"\&. To turn off any kind of rate limiting, set either value to 0\&.
.RE
.PP
\fISystemMaxUse=\fR, \fISystemKeepFree=\fR, \fISystemMaxFileSize=\fR, \fIRuntimeMaxUse=\fR, \fIRuntimeKeepFree=\fR, \fIRuntimeMaxFileSize=\fR
.RS 4
Enforce size limits on the journal files stored\&. The options prefixed with
"System"
apply to the journal files when stored on a persistent file system, more specifically
/var/log/journal\&. The options prefixed with
"Runtime"
apply to the journal files when stored on a volatile in\-memory file system, more specifically
/run/log/journal\&. The former is used only when
/var
is mounted, writable, and the directory
/var/log/journal
exists\&. Otherwise, only the latter applies\&. Note that this means that during early boot and if the administrator disabled persistent logging, only the latter options apply, while the former apply if persistent logging is enabled and the system is fully booted up\&.
\fBjournalctl\fR
and
\fBsystemd\-journald\fR
ignore all files with names not ending with
"\&.journal"
or
"\&.journal~", so only such files, located in the appropriate directories, are taken into account when calculating current disk usage\&.
.sp
\fISystemMaxUse=\fR
and
\fIRuntimeMaxUse=\fR
control how much disk space the journal may use up at maximum\&.
\fISystemKeepFree=\fR
and
\fIRuntimeKeepFree=\fR
control how much disk space systemd\-journald shall leave free for other uses\&.
\fBsystemd\-journald\fR
will respect both limits and use the smaller of the two values\&.
.sp
The first pair defaults to 10% and the second to 15% of the size of the respective file system\&. If the file system is nearly full and either
\fISystemKeepFree=\fR
or
\fIRuntimeKeepFree=\fR
is violated when systemd\-journald is started, the value will be raised to percentage that is actually free\&. This means that if there was enough free space before and journal files were created, and subsequently something else causes the file system to fill up, journald will stop using more space, but it will not be removing existing files to go reduce footprint either\&.
.sp
\fISystemMaxFileSize=\fR
and
\fIRuntimeMaxFileSize=\fR
control how large individual journal files may grow at maximum\&. This influences the granularity in which disk space is made available through rotation, i\&.e\&. deletion of historic data\&. Defaults to one eighth of the values configured with
\fISystemMaxUse=\fR
and
\fIRuntimeMaxUse=\fR, so that usually seven rotated journal files are kept as history\&. Specify values in bytes or use K, M, G, T, P, E as units for the specified sizes (equal to 1024, 1024\(S2,\&.\&.\&. bytes)\&. Note that size limits are enforced synchronously when journal files are extended, and no explicit rotation step triggered by time is needed\&.
.RE
.PP
\fIMaxFileSec=\fR
.RS 4
The maximum time to store entries in a single journal file before rotating to the next one\&. Normally, time\-based rotation should not be required as size\-based rotation with options such as
\fISystemMaxFileSize=\fR
should be sufficient to ensure that journal files do not grow without bounds\&. However, to ensure that not too much data is lost at once when old journal files are deleted, it might make sense to change this value from the default of one month\&. Set to 0 to turn off this feature\&. This setting takes time values which may be suffixed with the units
"year",
"month",
"week",
"day",
"h"
or
"m"
to override the default time unit of seconds\&.
.RE
.PP
\fIMaxRetentionSec=\fR
.RS 4
The maximum time to store journal entries\&. This controls whether journal files containing entries older then the specified time span are deleted\&. Normally, time\-based deletion of old journal files should not be required as size\-based deletion with options such as
\fISystemMaxUse=\fR
should be sufficient to ensure that journal files do not grow without bounds\&. However, to enforce data retention policies, it might make sense to change this value from the default of 0 (which turns off this feature)\&. This setting also takes time values which may be suffixed with the units
"year",
"month",
"week",
"day",
"h"
or
" m"
to override the default time unit of seconds\&.
.RE
.PP
\fISyncIntervalSec=\fR
.RS 4
The timeout before synchronizing journal files to disk\&. After syncing, journal files are placed in the OFFLINE state\&. Note that syncing is unconditionally done immediately after a log message of priority CRIT, ALERT or EMERG has been logged\&. This setting hence applies only to messages of the levels ERR, WARNING, NOTICE, INFO, DEBUG\&. The default timeout is 5 minutes\&.
.RE
.PP
\fIForwardToSyslog=\fR, \fIForwardToKMsg=\fR, \fIForwardToConsole=\fR, \fIForwardToWall=\fR
.RS 4
Control whether log messages received by the journal daemon shall be forwarded to a traditional syslog daemon, to the kernel log buffer (kmsg), to the system console, or sent as wall messages to all logged\-in users\&. These options take boolean arguments\&. If forwarding to syslog is enabled but no syslog daemon is running, the respective option has no effect\&. By default, only forwarding to syslog and wall is enabled\&. These settings may be overridden at boot time with the kernel command line options
"systemd\&.journald\&.forward_to_syslog=",
"systemd\&.journald\&.forward_to_kmsg=",
"systemd\&.journald\&.forward_to_console="
and
"systemd\&.journald\&.forward_to_wall="\&. When forwarding to the console, the TTY to log to can be changed with
\fITTYPath=\fR, described below\&.
.RE
.PP
\fIMaxLevelStore=\fR, \fIMaxLevelSyslog=\fR, \fIMaxLevelKMsg=\fR, \fIMaxLevelConsole=\fR, \fIMaxLevelWall=\fR
.RS 4
Controls the maximum log level of messages that are stored on disk, forwarded to syslog, kmsg, the console or wall (if that is enabled, see above)\&. As argument, takes one of
"emerg",
"alert",
"crit",
"err",
"warning",
"notice",
"info",
"debug"
or integer values in the range of 0\&.\&.7 (corresponding to the same levels)\&. Messages equal or below the log level specified are stored/forwarded, messages above are dropped\&. Defaults to
"debug"
for
\fIMaxLevelStore=\fR
and
\fIMaxLevelSyslog=\fR, to ensure that the all messages are written to disk and forwarded to syslog\&. Defaults to
"notice"
for
\fIMaxLevelKMsg=\fR,
"info"
for
\fIMaxLevelConsole=\fR
and
"emerg"
for
\fIMaxLevelWall=\fR\&.
.RE
.PP
\fITTYPath=\fR
.RS 4
Change the console TTY to use if
\fIForwardToConsole=yes\fR
is used\&. Defaults to
/dev/console\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-journald.service\fR(8),
\fBjournalctl\fR(1),
\fBsystemd.journal-fields\fR(7),
\fBsystemd-system.conf\fR(5)
.SH "NOTES"
.IP " 1." 4
Seekable Sequential Key Generators
.RS 4
\%https://eprint.iacr.org/2013/397
.RE
