'\" t
.TH "KERNEL\-COMMAND\-LINE" "7" "" "systemd 220" "kernel-command-line"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kernel-command-line \- Kernel command line parameters
.SH "SYNOPSIS"
.PP
/proc/cmdline
.SH "DESCRIPTION"
.PP
The kernel, the initial RAM disk (initrd) and basic userspace functionality may be configured at boot via kernel command line arguments\&.
.PP
For command line parameters understood by the kernel, please see
\m[blue]\fBkernel\-parameters\&.txt\fR\m[]\&\s-2\u[1]\d\s+2
and
\fBbootparam\fR(7)\&.
.PP
For command line parameters understood by the initial RAM disk, please see
\fBdracut.cmdline\fR(7), or the documentation of the specific initrd implementation of your installation\&.
.SH "CORE OS COMMAND LINE ARGUMENTS"
.PP
\fIsystemd\&.unit=\fR, \fIrd\&.systemd\&.unit=\fR, \fIsystemd\&.dump_core=\fR, \fIsystemd\&.crash_shell=\fR, \fIsystemd\&.crash_chvt=\fR, \fIsystemd\&.confirm_spawn=\fR, \fIsystemd\&.show_status=\fR, \fIsystemd\&.log_target=\fR, \fIsystemd\&.log_level=\fR, \fIsystemd\&.log_color=\fR, \fIsystemd\&.log_location=\fR, \fIsystemd\&.default_standard_output=\fR, \fIsystemd\&.default_standard_error=\fR, \fIsystemd\&.setenv=\fR
.RS 4
Parameters understood by the system and service manager to control system behavior\&. For details, see
\fBsystemd\fR(1)\&.
.RE
.PP
\fIsystemd\&.mask=\fR, \fIsystemd\&.wants=\fR, \fIsystemd\&.debug\-shell\fR
.RS 4
Additional parameters understood by
\fBsystemd-debug-generator\fR(8), to mask or start specific units at boot, or invoke a debug shell on tty9\&.
.RE
.PP
\fIsystemd\&.restore_state=\fR
.RS 4
This parameter is understood by several system tools to control whether or not they should restore system state from the previous boot\&. For details, see
\fBsystemd-backlight@.service\fR(8)
and
\fBsystemd-rfkill@.service\fR(8)\&.
.RE
.PP
\fIquiet\fR
.RS 4
Parameter understood by both the kernel and the system and service manager to control console log verbosity\&. For details, see
\fBsystemd\fR(1)\&.
.RE
.PP
\fIdebug\fR
.RS 4
Parameter understood by both the kernel and the system and service manager to control console log verbosity\&. For details, see
\fBsystemd\fR(1)\&.
.RE
.PP
\fI\-b\fR, \fIemergency\fR, \fIrescue\fR, \fIsingle\fR, \fIs\fR, \fIS\fR, \fI1\fR, \fI2\fR, \fI3\fR, \fI4\fR, \fI5\fR
.RS 4
Parameters understood by the system and service manager, as compatibility options\&. For details, see
\fBsystemd\fR(1)\&.
.RE
.PP
\fIlocale\&.LANG=\fR, \fIlocale\&.LANGUAGE=\fR, \fIlocale\&.LC_CTYPE=\fR, \fIlocale\&.LC_NUMERIC=\fR, \fIlocale\&.LC_TIME=\fR, \fIlocale\&.LC_COLLATE=\fR, \fIlocale\&.LC_MONETARY=\fR, \fIlocale\&.LC_MESSAGES=\fR, \fIlocale\&.LC_PAPER=\fR, \fIlocale\&.LC_NAME=\fR, \fIlocale\&.LC_ADDRESS=\fR, \fIlocale\&.LC_TELEPHONE=\fR, \fIlocale\&.LC_MEASUREMENT=\fR, \fIlocale\&.LC_IDENTIFICATION=\fR
.RS 4
Parameters understood by the system and service manager to control locale and language settings\&. For details, see
\fBsystemd\fR(1)\&.
.RE
.PP
\fIfsck\&.mode=\fR, \fIfsck\&.repair=\fR
.RS 4
Parameters understood by the file system checker services\&. For details, see
\fBsystemd-fsck@.service\fR(8)\&.
.RE
.PP
\fIquotacheck\&.mode=\fR
.RS 4
Parameter understood by the file quota checker service\&. For details, see
\fBsystemd-quotacheck.service\fR(8)\&.
.RE
.PP
\fIsystemd\&.journald\&.forward_to_syslog=\fR, \fIsystemd\&.journald\&.forward_to_kmsg=\fR, \fIsystemd\&.journald\&.forward_to_console=\fR, \fIsystemd\&.journald\&.forward_to_wall=\fR
.RS 4
Parameters understood by the journal service\&. For details, see
\fBsystemd-journald.service\fR(8)\&.
.RE
.PP
\fIvconsole\&.keymap=\fR, \fIvconsole\&.keymap\&.toggle=\fR, \fIvconsole\&.font=\fR, \fIvconsole\&.font\&.map=\fR, \fIvconsole\&.font\&.unimap=\fR
.RS 4
Parameters understood by the virtual console setup logic\&. For details, see
\fBsystemd-vconsole-setup.service\fR(8)\&.
.RE
.PP
\fIudev\&.log\-priority=\fR, \fIrd\&.udev\&.log\-priority=\fR, \fIudev\&.children\-max=\fR, \fIrd\&.udev\&.children\-max=\fR, \fIudev\&.exec\-delay=\fR, \fIrd\&.udev\&.exec\-delay=\fR, \fIudev\&.event\-timeout=\fR, \fIrd\&.udev\&.event\-timeout=\fR, \fInet\&.ifnames=\fR
.RS 4
Parameters understood by the device event managing daemon\&. For details, see
\fBsystemd-udevd.service\fR(8)\&.
.RE
.PP
\fIplymouth\&.enable=\fR
.RS 4
May be used to disable the Plymouth boot splash\&. For details, see
\fBplymouth\fR(8)\&.
.RE
.PP
\fIluks=\fR, \fIrd\&.luks=\fR, \fIluks\&.crypttab=\fR, \fIrd\&.luks\&.crypttab=\fR, \fIluks\&.name=\fR, \fIrd\&.luks\&.name=\fR, \fIluks\&.uuid=\fR, \fIrd\&.luks\&.uuid=\fR, \fIluks\&.options=\fR, \fIrd\&.luks\&.options=\fR, \fIluks\&.key=\fR, \fIrd\&.luks\&.key=\fR
.RS 4
Configures the LUKS full\-disk encryption logic at boot\&. For details, see
\fBsystemd-cryptsetup-generator\fR(8)\&.
.RE
.PP
\fIfstab=\fR, \fIrd\&.fstab=\fR
.RS 4
Configures the
/etc/fstab
logic at boot\&. For details, see
\fBsystemd-fstab-generator\fR(8)\&.
.RE
.PP
\fIroot=\fR, \fIrootfstype=\fR, \fIrootflags=\fR, \fIro\fR, \fIrw\fR
.RS 4
Configures the root file system and its file system type and mount options, as well as whether it shall be mounted read\-only or read\-writable initially\&. For details, see
\fBsystemd-fstab-generator\fR(8)\&.
.RE
.PP
\fIsystemd\&.gpt_auto=\fR, \fIrd\&.systemd\&.gpt_auto=\fR
.RS 4
Configures whether GPT based partition auto\-discovery shall be attempted\&. For details, see
\fBsystemd-gpt-auto-generator\fR(8)\&.
.RE
.PP
\fImodules\-load=\fR, \fIrd\&.modules\-load=\fR
.RS 4
Load a specific kernel module early at boot\&. For details, see
\fBsystemd-modules-load.service\fR(8)\&.
.RE
.PP
\fIresume=\fR
.RS 4
Enables resume from hibernation using the specified device\&. All
\fBfstab\fR(5)\-like paths are supported\&. For details, see
\fBsystemd-hibernate-resume-generator\fR(8)\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBbootparam\fR(7),
\fBdracut.cmdline\fR(7),
\fBsystemd-debug-generator\fR(8),
\fBsystemd-fsck@.service\fR(8),
\fBsystemd-quotacheck.service\fR(8),
\fBsystemd-journald.service\fR(8),
\fBsystemd-vconsole-setup.service\fR(8),
\fBsystemd-udevd.service\fR(8),
\fBplymouth\fR(8),
\fBsystemd-cryptsetup-generator\fR(8),
\fBsystemd-fstab-generator\fR(8),
\fBsystemd-gpt-auto-generator\fR(8),
\fBsystemd-modules-load.service\fR(8),
\fBsystemd-backlight@.service\fR(8),
\fBsystemd-rfkill@.service\fR(8),
\fBsystemd-hibernate-resume-generator\fR(8)
.SH "NOTES"
.IP " 1." 4
kernel-parameters.txt
.RS 4
\%https://www.kernel.org/doc/Documentation/kernel-parameters.txt
.RE
