'\" t
.TH "LOCALTIME" "5" "" "systemd 220" "localtime"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
localtime \- Local timezone configuration file
.SH "SYNOPSIS"
.PP
/etc/localtime
\->
\&.\&./usr/share/zoneinfo/\&...
.SH "DESCRIPTION"
.PP
The
/etc/localtime
file configures the system\-wide timezone of the local system that is used by applications for presentation to the user\&. It should be an absolute or relative symbolic link pointing to
/usr/share/zoneinfo/, followed by a timezone identifier such as
"Europe/Berlin"
or
"Etc/UTC"\&. The resulting link should lead to the corresponding binary
\fBtzfile\fR(5)
timezone data for the configured timezone\&.
.PP
Because the timezone identifier is extracted from the symlink target name of
/etc/localtime, this file may not be a normal file or hardlink\&.
.PP
The timezone may be overridden for individual programs by using the
\fI$TZ\fR
environment variable\&. See
\fBenviron\fR(7)\&.
.PP
You may use
\fBtimedatectl\fR(1)
to change the settings of this file from the command line during runtime\&. Use
\fBsystemd-firstboot\fR(1)
to initialize the time zone on mounted (but not booted) system images\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBtzset\fR(3),
\fBlocaltime\fR(3),
\fBtimedatectl\fR(1),
\fBsystemd-timedated.service\fR(8),
\fBsystemd-firstboot\fR(1)
