'\" t
.TH "LOCALE\&.CONF" "5" "" "systemd 215" "locale.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
locale.conf \- Configuration file for locale settings
.SH "SYNOPSIS"
.PP
/etc/locale\&.conf
.SH "DESCRIPTION"
.PP
The
/etc/locale\&.conf
file configures system\-wide locale settings\&. It is read at early\-boot by
\fBsystemd\fR(1)\&.
.PP
The basic file format of
locale\&.conf
is a newline\-separated list of environment\-like shell\-compatible variable assignments\&. It is possible to source the configuration from shell scripts, however, beyond mere variable assignments, no shell features are supported, allowing applications to read the file without implementing a shell compatible execution engine\&.
.PP
Note that the kernel command line options
\fIlocale\&.LANG=\fR,
\fIlocale\&.LANGUAGE=\fR,
\fIlocale\&.LC_CTYPE=\fR,
\fIlocale\&.LC_NUMERIC=\fR,
\fIlocale\&.LC_TIME=\fR,
\fIlocale\&.LC_COLLATE=\fR,
\fIlocale\&.LC_MONETARY=\fR,
\fIlocale\&.LC_MESSAGES=\fR,
\fIlocale\&.LC_PAPER=\fR,
\fIlocale\&.LC_NAME=\fR,
\fIlocale\&.LC_ADDRESS=\fR,
\fIlocale\&.LC_TELEPHONE=\fR,
\fIlocale\&.LC_MEASUREMENT=\fR,
\fIlocale\&.LC_IDENTIFICATION=\fR
may be used to override the locale settings at boot\&.
.PP
The locale settings configured in
/etc/locale\&.conf
are system\-wide and are inherited by every service or user, unless overridden or unset by individual programs or individual users\&.
.PP
Depending on the operating system, other configuration files might be checked for locale configuration as well, however only as fallback\&.
.SH "OPTIONS"
.PP
The following locale settings may be set using
/etc/locale\&.conf:
\fILANG=\fR,
\fILANGUAGE=\fR,
\fILC_CTYPE=\fR,
\fILC_NUMERIC=\fR,
\fILC_TIME=\fR,
\fILC_COLLATE=\fR,
\fILC_MONETARY=\fR,
\fILC_MESSAGES=\fR,
\fILC_PAPER=\fR,
\fILC_NAME=\fR,
\fILC_ADDRESS=\fR,
\fILC_TELEPHONE=\fR,
\fILC_MEASUREMENT=\fR,
\fILC_IDENTIFICATION=\fR\&. Note that
\fILC_ALL\fR
may not be configured in this file\&. For details about the meaning and semantics of these settings, refer to
\fBlocale\fR(7)\&.
.SH "EXAMPLE"
.PP
\fBExample\ \&1.\ \&German locale with English messages\fR
.PP
/etc/locale\&.conf:
.sp
.if n \{\
.RS 4
.\}
.nf
LANG=de_DE\&.UTF\-8
LC_MESSAGES=en_US\&.UTF\-8
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBlocale\fR(7),
\fBsystemd-localed.service\fR(8)
