'\" t
.TH "LOCALECTL" "1" "" "systemd 215" "localectl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
localectl \- Control the system locale and keyboard layout settings
.SH "SYNOPSIS"
.HP \w'\fBlocalectl\fR\ 'u
\fBlocalectl\fR [OPTIONS...] {COMMAND}
.SH "DESCRIPTION"
.PP
\fBlocalectl\fR
may be used to query and change the system locale and keyboard layout settings\&.
.PP
The system locale controls the language settings of system services and of the UI before the user logs in, such as the display manager, as well as the default for users after login\&.
.PP
The keyboard settings control the keyboard layout used on the text console and of the graphical UI before the user logs in, such as the display manager, as well as the default for users after login\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-no\-ask\-password\fR
.RS 4
Do not query the user for authentication for privileged operations\&.
.RE
.PP
\fB\-P\fR, \fB\-\-privileged\fR
.RS 4
Acquire privileges via PolicyKit before executing the operation\&.
.RE
.PP
\fB\-\-no\-convert\fR
.RS 4
If
\fBset\-keymap\fR
or
\fBset\-x11\-keymap\fR
is invoked and this option is passed, then the keymap will not be converted from the console to X11, or X11 to console, respectively\&.
.RE
.PP
\fB\-H\fR, \fB\-\-host=\fR
.RS 4
Execute the operation remotely\&. Specify a hostname, or a username and hostname separated by
"@", to connect to\&. The hostname may optionally be suffixed by a container name, separated by
":", which connects directly to a specific container on the specified host\&. This will use SSH to talk to the remote machine manager instance\&. Container names may be enumerated with
\fBmachinectl \-H \fR\fB\fIHOST\fR\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.PP
\fB\-\-no\-pager\fR
.RS 4
Do not pipe output into a pager\&.
.RE
.PP
The following commands are understood:
.PP
\fBstatus\fR
.RS 4
Show current settings of the system locale and keyboard mapping\&.
.RE
.PP
\fBset\-locale LOCALE\&.\&.\&.\fR
.RS 4
Set the system locale\&. This takes one or more assignments such as "LANG=de_DE\&.utf8", "LC_MESSAGES=en_GB\&.utf8", and so on\&. See
\fBlocale\fR(7)
for details on the available settings and their meanings\&. Use
\fBlist\-locales\fR
for a list of available locales (see below)\&.
.RE
.PP
\fBlist\-locales\fR
.RS 4
List available locales useful for configuration with
\fBset\-locale\fR\&.
.RE
.PP
\fBset\-keymap MAP [TOGGLEMAP]\fR
.RS 4
Set the system keyboard mapping for the console\&. This takes a keyboard mapping name (such as "de" or "us"), and possibly a second one to define a toggle keyboard mapping\&. Unless
\fB\-\-no\-convert\fR
is passed, the selected setting is also applied to the default keyboard mapping of X11, after converting it to the closest matching X11 keyboard mapping\&. Use
\fBlist\-keymaps\fR
for a list of available keyboard mappings (see below)\&.
.RE
.PP
\fBlist\-keymaps\fR
.RS 4
List available keyboard mappings for the console, useful for configuration with
\fBset\-keymap\fR\&.
.RE
.PP
\fBset\-x11\-keymap LAYOUT [MODEL] [VARIANT] [OPTIONS]\fR
.RS 4
Set the system default keyboard mapping for X11\&. This takes a keyboard mapping name (such as "de" or "us"), and possibly a model, variant and options, see
\fBkbd\fR(4)
for details\&. Unless
\fB\-\-no\-convert\fR
is passed, the selected setting is also applied to the system console keyboard mapping, after converting it to the closest matching console keyboard mapping\&.
.RE
.PP
\fBlist\-x11\-keymap\-models\fR, \fBlist\-x11\-keymap\-layouts\fR, \fBlist\-x11\-keymap\-variants [LAYOUT]\fR, \fBlist\-x11\-keymap\-options\fR
.RS 4
List available X11 keymap models, layouts, variants and options, useful for configuration with
\fBset\-keymap\fR\&. The command
\fBlist\-x11\-keymap\-variants\fR
optionally takes a layout parameter to limit the output to the variants suitable for the specific layout\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "ENVIRONMENT"
.PP
\fI$SYSTEMD_PAGER\fR
.RS 4
Pager to use when
\fB\-\-no\-pager\fR
is not given; overrides
\fI$PAGER\fR\&. Setting this to an empty string or the value
"cat"
is equivalent to passing
\fB\-\-no\-pager\fR\&.
.RE
.PP
\fI$SYSTEMD_LESS\fR
.RS 4
Override the default options passed to
\fBless\fR
("FRSXMK")\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBlocale\fR(7),
\fBlocale.conf\fR(5),
\fBvconsole.conf\fR(5),
\fBloadkeys\fR(1),
\fBkbd\fR(4),
\m[blue]\fBThe XKB Configuration Guide\fR\m[]\&\s-2\u[1]\d\s+2,
\fBsystemctl\fR(1),
\fBsystemd-localed.service\fR(8)
.SH "NOTES"
.IP " 1." 4
The XKB Configuration Guide
.RS 4
\%http://www.x.org/releases/current/doc/xorg-docs/input/XKB-Config.html
.RE
