'\" t
.TH "MACHINE\-INFO" "5" "" "systemd 221" "machine-info"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
machine-info \- Local machine information file
.SH "SYNOPSIS"
.PP
/etc/machine\-info
.SH "DESCRIPTION"
.PP
The
/etc/machine\-info
file contains machine metadata\&.
.PP
The basic file format of
machine\-info
is a newline\-separated list of environment\-like shell\-compatible variable assignments\&. It is possible to source the configuration from shell scripts, however, beyond mere variable assignments no shell features are supported, allowing applications to read the file without implementing a shell compatible execution engine\&.
.PP
/etc/machine\-info
contains metadata about the machine that is set by the user or administrator\&.
.PP
Depending on the operating system other configuration files might be checked for machine information as well, however only as fallback\&.
.PP
You may use
\fBhostnamectl\fR(1)
to change the settings of this file from the command line\&.
.SH "OPTIONS"
.PP
The following machine metadata parameters may be set using
/etc/machine\-info:
.PP
\fIPRETTY_HOSTNAME=\fR
.RS 4
A pretty human\-readable UTF\-8 machine identifier string\&. This should contain a name like
"Lennart\*(Aqs Laptop"
which is useful to present to the user and does not suffer by the syntax limitations of internet domain names\&. If possible, the internet hostname as configured in
/etc/hostname
should be kept similar to this one\&. Example: if this value is
"Lennart\*(Aqs Computer"
an Internet hostname of
"lennarts\-computer"
might be a good choice\&. If this parameter is not set, an application should fall back to the Internet host name for presentation purposes\&.
.RE
.PP
\fIICON_NAME=\fR
.RS 4
An icon identifying this machine according to the
\m[blue]\fBXDG Icon Naming Specification\fR\m[]\&\s-2\u[1]\d\s+2\&. If this parameter is not set, an application should fall back to
"computer"
or a similar icon name\&.
.RE
.PP
\fICHASSIS=\fR
.RS 4
The chassis type\&. Currently, the following chassis types are defined:
"desktop",
"laptop",
"server",
"tablet",
"handset",
"watch", and
"embedded"
as well as the special chassis types
"vm"
and
"container"
for virtualized systems that lack an immediate physical chassis\&. Note that many systems allow detection of the chassis type automatically (based on firmware information or suchlike)\&. This setting (if set) shall take precedence over automatically detected information and is useful to override misdetected configuration or to manually configure the chassis type where automatic detection is not available\&.
.RE
.PP
\fIDEPLOYMENT=\fR
.RS 4
Describes the system deployment environment\&. One of the following is suggested:
"development",
"integration",
"staging",
"production"\&.
.RE
.PP
\fILOCATION=\fR
.RS 4
Describes the system location if applicable and known\&. Takes a human\-friendly, free\-form string\&. This may be as generic as
"Berlin, Germany"
or as specific as
"Left Rack, 2nd Shelf"\&.
.RE
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
PRETTY_HOSTNAME="Lennart\*(Aqs Tablet"
ICON_NAME=computer\-tablet
CHASSIS=tablet
DEPLOYMENT=production
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBos-release\fR(5),
\fBhostname\fR(5),
\fBmachine-id\fR(5),
\fBhostnamectl\fR(1),
\fBsystemd-hostnamed.service\fR(8)
.SH "NOTES"
.IP " 1." 4
XDG Icon Naming Specification
.RS 4
\%http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
.RE
