'\" t
.TH "MODULES\-LOAD\&.D" "5" "" "systemd 221" "modules-load.d"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
modules-load.d \- Configure kernel modules to load at boot
.SH "SYNOPSIS"
.PP
/etc/modules\-load\&.d/*\&.conf
.PP
/run/modules\-load\&.d/*\&.conf
.PP
/usr/lib/modules\-load\&.d/*\&.conf
.SH "DESCRIPTION"
.PP
\fBsystemd-modules-load.service\fR(8)
reads files from the above directories which contain kernel modules to load during boot in a static list\&. Each configuration file is named in the style of
/etc/modules\-load\&.d/\fIprogram\fR\&.conf\&. Note that it is usually a better idea to rely on the automatic module loading by PCI IDs, USB IDs, DMI IDs or similar triggers encoded in the kernel modules themselves instead of static configuration like this\&. In fact, most modern kernel modules are prepared for automatic loading already\&.
.SH "CONFIGURATION FORMAT"
.PP
The configuration files should simply contain a list of kernel module names to load, separated by newlines\&. Empty lines and lines whose first non\-whitespace character is # or ; are ignored\&.
.SH "CONFIGURATION DIRECTORIES AND PRECEDENCE"
.PP
Configuration files are read from directories in
/etc/,
/run/, and
/usr/lib/, in order of precedence\&. Each configuration file in these configuration directories shall be named in the style of
\fIfilename\fR\&.conf\&. Files in
/etc/
override files with the same name in
/run/
and
/usr/lib/\&. Files in
/run/
override files with the same name in
/usr/lib/\&.
.PP
Packages should install their configuration files in
/usr/lib/\&. Files in
/etc/
are reserved for the local administrator, who may use this logic to override the configuration files installed by vendor packages\&. All configuration files are sorted by their filename in lexicographic order, regardless of which of the directories they reside in\&. If multiple files specify the same option, the entry in the file with the lexicographically latest name will take precedence\&. It is recommended to prefix all filenames with a two\-digit number and a dash, to simplify the ordering of the files\&.
.PP
If the administrator wants to disable a configuration file supplied by the vendor, the recommended way is to place a symlink to
/dev/null
in the configuration directory in
/etc/, with the same filename as the vendor configuration file\&.
.SH "EXAMPLE"
.PP
\fBExample\ \&1.\ \&/etc/modules-load.d/virtio-net.conf example:\fR
.sp
.if n \{\
.RS 4
.\}
.nf
# Load virtio\-net\&.ko at boot
virtio\-net
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-modules-load.service\fR(8),
\fBsystemd-delta\fR(1),
\fBmodprobe\fR(8)
