'\" t
.TH "OS\-RELEASE" "5" "" "systemd 220" "os-release"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
os-release \- Operating system identification
.SH "SYNOPSIS"
.PP
/etc/os\-release
.PP
/usr/lib/os\-release
.SH "DESCRIPTION"
.PP
The
/etc/os\-release
and
/usr/lib/os\-release
files contain operating system identification data\&.
.PP
The basic file format of
os\-release
is a newline\-separated list of environment\-like shell\-compatible variable assignments\&. It is possible to source the configuration from shell scripts, however, beyond mere variable assignments, no shell features are supported (this means variable expansion is explicitly not supported), allowing applications to read the file without implementing a shell compatible execution engine\&. Variable assignment values must be enclosed in double or single quotes if they include spaces, semicolons or other special characters outside of A\-Z, a\-z, 0\-9\&. Shell special characters ("$", quotes, backslash, backtick) must be escaped with backslashes, following shell style\&. All strings should be in UTF\-8 format, and non\-printable characters should not be used\&. It is not supported to concatenate multiple individually quoted strings\&. Lines beginning with "#" shall be ignored as comments\&.
.PP
The file
/etc/os\-release
takes precedence over
/usr/lib/os\-release\&. Applications should check for the former, and exclusively use its data if it exists, and only fall back to
/usr/lib/os\-release
if it is missing\&. Applications should not read data from both files at the same time\&.
/usr/lib/os\-release
is the recommended place to store OS release information as part of vendor trees\&.
/etc/os\-release
should be a relative symlink to
/usr/lib/os\-release, to provide compatibility with applications only looking at
/etc\&. A relative symlink instead of an absolute symlink is necessary to avoid breaking the link in a chroot or initrd environment such as dracut\&.
.PP
os\-release
contains data that is defined by the operating system vendor and should generally not be changed by the administrator\&.
.PP
As this file only encodes names and identifiers it should not be localized\&.
.PP
The
/etc/os\-release
and
/usr/lib/os\-release
files might be symlinks to other files, but it is important that the file is available from earliest boot on, and hence must be located on the root file system\&.
.PP
For a longer rationale for
os\-release
please refer to the
\m[blue]\fBAnnouncement of /etc/os\-release\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "OPTIONS"
.PP
The following OS identifications parameters may be set using
os\-release:
.PP
\fINAME=\fR
.RS 4
A string identifying the operating system, without a version component, and suitable for presentation to the user\&. If not set, defaults to
"NAME=Linux"\&. Example:
"NAME=Fedora"
or
"NAME="Debian GNU/Linux""\&.
.RE
.PP
\fIVERSION=\fR
.RS 4
A string identifying the operating system version, excluding any OS name information, possibly including a release code name, and suitable for presentation to the user\&. This field is optional\&. Example:
"VERSION=17"
or
"VERSION="17 (Beefy Miracle)""\&.
.RE
.PP
\fIID=\fR
.RS 4
A lower\-case string (no spaces or other characters outside of 0\-9, a\-z, "\&.", "_" and "\-") identifying the operating system, excluding any version information and suitable for processing by scripts or usage in generated filenames\&. If not set, defaults to
"ID=linux"\&. Example:
"ID=fedora"
or
"ID=debian"\&.
.RE
.PP
\fIID_LIKE=\fR
.RS 4
A space\-separated list of operating system identifiers in the same syntax as the
\fIID=\fR
setting\&. It should list identifiers of operating systems that are closely related to the local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from\&. An OS should generally only list other OS identifiers it itself is a derivative of, and not any OSes that are derived from it, though symmetric relationships are possible\&. Build scripts and similar should check this variable if they need to identify the local operating system and the value of
\fIID=\fR
is not recognized\&. Operating systems should be listed in order of how closely the local operating system relates to the listed ones, starting with the closest\&. This field is optional\&. Example: for an operating system with
"ID=centos", an assignment of
"ID_LIKE="rhel fedora""
would be appropriate\&. For an operating system with
"ID=ubuntu", an assignment of
"ID_LIKE=debian"
is appropriate\&.
.RE
.PP
\fIVERSION_ID=\fR
.RS 4
A lower\-case string (mostly numeric, no spaces or other characters outside of 0\-9, a\-z, "\&.", "_" and "\-") identifying the operating system version, excluding any OS name information or release code name, and suitable for processing by scripts or usage in generated filenames\&. This field is optional\&. Example:
"VERSION_ID=17"
or
"VERSION_ID=11\&.04"\&.
.RE
.PP
\fIPRETTY_NAME=\fR
.RS 4
A pretty operating system name in a format suitable for presentation to the user\&. May or may not contain a release code name or OS version of some kind, as suitable\&. If not set, defaults to
"PRETTY_NAME="Linux""\&. Example:
"PRETTY_NAME="Fedora 17 (Beefy Miracle)""\&.
.RE
.PP
\fIANSI_COLOR=\fR
.RS 4
A suggested presentation color when showing the OS name on the console\&. This should be specified as string suitable for inclusion in the ESC [ m ANSI/ECMA\-48 escape code for setting graphical rendition\&. This field is optional\&. Example:
"ANSI_COLOR="0;31""
for red, or
"ANSI_COLOR="1;34""
for light blue\&.
.RE
.PP
\fICPE_NAME=\fR
.RS 4
A CPE name for the operating system, following the
\m[blue]\fBCommon Platform Enumeration Specification\fR\m[]\&\s-2\u[2]\d\s+2
as proposed by the MITRE Corporation\&. This field is optional\&. Example:
"CPE_NAME="cpe:/o:fedoraproject:fedora:17""
.RE
.PP
\fIHOME_URL=\fR, \fISUPPORT_URL=\fR, \fIBUG_REPORT_URL=\fR, \fIPRIVACY_POLICY_URL=\fR
.RS 4
Links to resources on the Internet related the operating system\&.
\fIHOME_URL=\fR
should refer to the homepage of the operating system, or alternatively some homepage of the specific version of the operating system\&.
\fISUPPORT_URL=\fR
should refer to the main support page for the operating system, if there is any\&. This is primarily intended for operating systems which vendors provide support for\&.
\fIBUG_REPORT_URL=\fR
should refer to the main bug reporting page for the operating system, if there is any\&. This is primarily intended for operating systems that rely on community QA\&.
\fIPRIVACY_POLICY_URL=\fR
should refer to the main privacy policy page for the operation system, if there is any\&. These settings are optional, and providing only some of these settings is common\&. These URLs are intended to be exposed in "About this system" UIs behind links with captions such as "About this Operating System", "Obtain Support", "Report a Bug", or "Privacy Policy"\&. The values should be in
\m[blue]\fBRFC3986 format\fR\m[]\&\s-2\u[3]\d\s+2, and should be
"http:"
or
"https:"
URLs, and possibly
"mailto:"
or
"tel:"\&. Only one URL shall be listed in each setting\&. If multiple resources need to be referenced, it is recommended to provide an online landing page linking all available resources\&. Examples:
"HOME_URL="https://fedoraproject\&.org/""
and
"BUG_REPORT_URL="https://bugzilla\&.redhat\&.com/""
.RE
.PP
\fIBUILD_ID=\fR
.RS 4
A string uniquely identifying the system image used as the origin for a distribution (it is not updated with system updates)\&. The field can be identical between different VERSION_IDs as BUILD_ID is an only a unique identifier to a specific version\&. Distributions that release each update as a new version would only need to use VERSION_ID as each build is already distinct based on the VERSION_ID\&. This field is optional\&. Example:
"BUILD_ID="2013\-03\-20\&.3""
or
"BUILD_ID=201303203"\&.
.RE
.PP
\fIVARIANT=\fR
.RS 4
A string identifying a specific variant or edition of the operating system suitable for presentation to the user\&. This field may be used to inform the user that the configuration of this system is subject to a specific divergent set of rules or default configuration settings\&. This field is optional and may not be implemented on all systems\&. Examples:
"VARIANT="Server Edition"",
"VARIANT="Smart Refrigerator Edition""
Note: this field is for display purposes only\&. The
\fIVARIANT_ID\fR
field should be used for making programmatic decisions\&.
.RE
.PP
\fIVARIANT_ID=\fR
.RS 4
A lower\-case string (no spaces or other characters outside of 0\-9, a\-z, "\&.", "_" and "\-"), identifying a specific variant or edition of the operating system\&. This may be interpreted by other packages in order to determine a divergent default configuration\&. This field is optional and may not be implemented on all systems\&. Examples:
"VARIANT_ID=server",
"VARIANT_ID=embedded"
.RE
.PP
If you are reading this file from C code or a shell script to determine the OS or a specific version of it, use the
\fIID\fR
and
\fIVERSION_ID\fR
fields, possibly with
\fIID_LIKE\fR
as fallback for
\fIID\fR\&. When looking for an OS identification string for presentation to the user use the
\fIPRETTY_NAME\fR
field\&.
.PP
Note that operating system vendors may choose not to provide version information, for example to accommodate for rolling releases\&. In this case,
\fIVERSION\fR
and
\fIVERSION_ID\fR
may be unset\&. Applications should not rely on these fields to be set\&.
.PP
Operating system vendors may extend the file format and introduce new fields\&. It is highly recommended to prefix new fields with an OS specific name in order to avoid name clashes\&. Applications reading this file must ignore unknown fields\&. Example:
"DEBIAN_BTS="debbugs://bugs\&.debian\&.org/""
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
NAME=Fedora
VERSION="17 (Beefy Miracle)"
ID=fedora
VERSION_ID=17
PRETTY_NAME="Fedora 17 (Beefy Miracle)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:17"
HOME_URL="https://fedoraproject\&.org/"
BUG_REPORT_URL="https://bugzilla\&.redhat\&.com/"
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBlsb_release\fR(1),
\fBhostname\fR(5),
\fBmachine-id\fR(5),
\fBmachine-info\fR(5)
.SH "NOTES"
.IP " 1." 4
Announcement of /etc/os-release
.RS 4
\%http://0pointer.de/blog/projects/os-release
.RE
.IP " 2." 4
Common Platform Enumeration Specification
.RS 4
\%https://cpe.mitre.org/specification/
.RE
.IP " 3." 4
RFC3986 format
.RS 4
\%https://tools.ietf.org/html/rfc3986
.RE
