'\" t
.TH "SD\-JOURNAL" "3" "" "systemd 220" "sd-journal"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd-journal \- APIs for submitting and querying log entries to and from the journal
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-journal\&.h>
.fi
.ft
.HP \w'\fBpkg\-config\ \-\-cflags\ \-\-libs\ libsystemd\fR\ 'u
\fBpkg\-config \-\-cflags \-\-libs libsystemd\fR
.SH "DESCRIPTION"
.PP
sd\-journal\&.h
provides APIs to submit and query log entries\&. The APIs exposed act both as client for the
\fBsystemd-journald.service\fR(8)
journal service and as parser for the journal files on disk\&.
.PP
See
\fBsd_journal_print\fR(3),
\fBsd_journal_stream_fd\fR(3),
\fBsd_journal_open\fR(3),
\fBsd_journal_next\fR(3),
\fBsd_journal_get_realtime_usec\fR(3),
\fBsd_journal_add_match\fR(3),
\fBsd_journal_seek_head\fR(3),
\fBsd_journal_get_cursor\fR(3),
\fBsd_journal_get_cutoff_realtime_usec\fR(3),
\fBsd_journal_get_cutoff_monotonic_usec\fR(3),
\fBsd_journal_get_usage\fR(3),
\fBsd_journal_get_catalog\fR(3)
and
\fBsd_journal_get_fd\fR(3)
for more information about the functions implemented\&.
.PP
Command line access for submitting entries to the journal is available with the
\fBsystemd-cat\fR(1)
tool\&. Command line access for querying entries from the journal is available with the
\fBjournalctl\fR(1)
tool\&.
.SH "NOTES"
.PP
These APIs are implemented as a shared library, which can be compiled and linked to with the
\fBlibsystemd\fR\ \&\fBpkg-config\fR(1)
file\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd_journal_print\fR(3),
\fBsd_journal_stream_fd\fR(3),
\fBsd_journal_open\fR(3),
\fBsd_journal_next\fR(3),
\fBsd_journal_get_data\fR(3),
\fBsd_journal_get_realtime_usec\fR(3),
\fBsd_journal_add_match\fR(3),
\fBsd_journal_seek_head\fR(3),
\fBsd_journal_get_cursor\fR(3),
\fBsd_journal_get_cutoff_realtime_usec\fR(3),
\fBsd_journal_get_cutoff_monotonic_usec\fR(3),
\fBsd_journal_get_usage\fR(3),
\fBsd_journal_get_fd\fR(3),
\fBsd_journal_query_unique\fR(3),
\fBsd_journal_get_catalog\fR(3),
\fBjournalctl\fR(1),
\fBsd-id128\fR(3),
\fBpkg-config\fR(1)
