'\" t
.TH "SD_EVENT_ADD_SIGNAL" "3" "" "systemd 221" "sd_event_add_signal"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd_event_add_signal, sd_event_source_get_signal \- Add a signal event source to an event loop
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-bus\&.h>
.fi
.ft
.HP \w'int\ sd_event_add_signal('u
.BI "int sd_event_add_signal(sd_event\ *" "event" ", sd_event_source\ **" "source" ", int\ " "signal" ", sd_event_signal_handler_t\ " "handler" ", void\ *" "userdata" ");"
.HP \w'typedef\ int\ (*sd_event_signal_handler_t)('u
.BI "typedef int (*sd_event_signal_handler_t)(sd_event_source\ *" "s" ", const\ struct\ signalfd_siginfo\ *" "si" ", void\ *" "userdata" ");"
.HP \w'int\ sd_event_source_get_signal('u
.BI "int sd_event_source_get_signal(sd_event_source\ *" "source" ");"
.SH "DESCRIPTION"
.PP
\fBsd_event_add_signal()\fR
adds a new signal event source to an event loop object\&. The event loop is specified in
\fIevent\fR, the event source is returned in the
\fIsource\fR
parameter\&. The
\fIsignal\fR
parameter specifies the signal to be handled (see
\fBsignal\fR(7))\&. The
\fIhandler\fR
must reference a function to call when the signal is delivered or be
\fBNULL\fR\&. The handler function will be passed the
\fIuserdata\fR
pointer, which may be chosen freely by the caller\&. The handler also receives a pointer to a
const struct signalfd_siginfo
containing the information about the received signal\&. See
\fBsignalfd\fR(2)
for further information\&.
.PP
Only a single handler may be installed for a specific signal\&. The signal will be unblocked, and must be blocked when the function is called\&. If the handler is not specified (\fIhandler\fR
is
\fBNULL\fR), a default handler which causes the program to exit will be used\&. By default, the handler is enabled permanently (\fBSD_EVENT_ON\fR), but this may be changed with
\fBsd_event_source_set_enabled\fR(3)\&. If the handler function returns a negative error code, it will be disabled after the invocation, even if
\fBSD_EVENT_ON\fR
mode is set\&.
.PP
\fBsd_event_source_get_signal()\fR
retrieves the configured signal number of a signal event source created previously with
\fBsd_event_add_signal()\fR\&. It takes the event source object as the
\fIsource\fR
parameter\&.
.SH "RETURN VALUE"
.PP
On success, these functions return 0 or a positive integer\&. On failure, they return a negative errno\-style error code\&.
.SH "ERRORS"
.PP
Returned errors may indicate the following problems:
.PP
\fB\-ENOMEM\fR
.RS 4
Not enough memory to allocate an object\&.
.RE
.PP
\fB\-EINVAL\fR
.RS 4
An invalid argument has been passed\&.
.RE
.PP
\fB\-EBUSY\fR
.RS 4
An handler is already installed for this signal or the signal was not blocked previously\&.
.RE
.PP
\fB\-ESTALE\fR
.RS 4
The event loop is already terminated\&.
.RE
.PP
\fB\-ECHILD\fR
.RS 4
The event loop has been created in a different process\&.
.RE
.SH "NOTES"
.PP
\fBsd_event_add_signal()\fR
and the other functions described here are available as a shared library, which can be compiled and linked to with the
\fBlibsystemd\fR\ \&\fBpkg-config\fR(1)
file\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd-event\fR(3),
\fBsd_event_new\fR(3),
\fBsd_event_add_time\fR(3),
\fBsd_event_add_child\fR(3),
\fBsd_event_add_defer\fR(3),
\fBsd_event_source_set_enabled\fR(3)
