'\" t
.TH "SD_ID128_RANDOMIZE" "3" "" "systemd 215" "sd_id128_randomize"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd_id128_randomize \- Generate 128\-bit IDs
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-id128\&.h>
.fi
.ft
.HP \w'int\ sd_id128_randomize('u
.BI "int sd_id128_randomize(sd_id128_t\ *" "ret" ");"
.SH "DESCRIPTION"
.PP
\fBsd_id128_randomize()\fR
generates a new randomized 128\-bit ID and returns it in
\fIret\fR\&. Every invocation returns a new randomly generated ID\&. This uses the
/dev/urandom
kernel random number generator\&.
.PP
Note that
\fBsd_id128_randomize()\fR
always returns a UUID v4\-compatible ID\&.
.PP
For more information about the
"sd_id128_t"
type, see
\fBsd-id128\fR(3)\&.
.PP
\fBjournalctl\fR(1)\*(Aqs
\fB\-\-new\-id\fR
option may be used as a command\-line front\-end for
\fBsd_id128_randomize()\fR\&.
.SH "RETURN VALUE"
.PP
The call returns 0 on success (in which case
\fIret\fR
is filled in), or a negative errno\-style error code\&.
.SH "NOTES"
.PP
The
\fBsd_id128_randomize()\fR
interface is available as a shared library, which can be compiled and linked to with the
"libsystemd"\ \&\fBpkg-config\fR(1)
file\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd-id128\fR(3),
\fBmachine-id\fR(5),
\fBrandom\fR(4),
\fBsd_id128_get_machine\fR(3)
