'\" t
.TH "SD_JOURNAL_GET_CUTOFF_REALTIME_USEC" "3" "" "systemd 221" "sd_journal_get_cutoff_realtime_usec"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd_journal_get_cutoff_realtime_usec, sd_journal_get_cutoff_monotonic_usec \- Read cut\-off timestamps from the current journal entry
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-journal\&.h>
.fi
.ft
.HP \w'int\ sd_journal_get_cutoff_realtime_usec('u
.BI "int sd_journal_get_cutoff_realtime_usec(sd_journal\ *" "j" ", uint64_t\ *" "from" ", uint64_t\ *" "to" ");"
.HP \w'int\ sd_journal_get_cutoff_monotonic_usec('u
.BI "int sd_journal_get_cutoff_monotonic_usec(sd_journal\ *" "j" ", sd_id128_t\ " "boot_id" ", uint64_t\ *" "from" ", uint64_t\ *" "to" ");"
.SH "DESCRIPTION"
.PP
\fBsd_journal_get_cutoff_realtime_usec()\fR
retrieves the realtime (wallclock) timestamps of the first and last entries accessible in the journal\&. It takes three arguments: the journal context object
\fIj\fR
and two pointers
\fIfrom\fR
and
\fIto\fR
pointing at 64\-bit unsigned integers to store the timestamps in\&. The timestamps are in microseconds since the epoch, i\&.e\&.
\fBCLOCK_REALTIME\fR\&. Either one of the two timestamp arguments may be passed as
\fBNULL\fR
in case the timestamp is not needed, but not both\&.
.PP
\fBsd_journal_get_cutoff_monotonic_usec()\fR
retrieves the monotonic timestamps of the first and last entries accessible in the journal\&. It takes three arguments: the journal context object
\fIj\fR, a 128\-bit identifier for the boot
\fIboot_id\fR, and two pointers to 64\-bit unsigned integers to store the timestamps,
\fIfrom\fR
and
\fIto\fR\&. The timestamps are in microseconds since boot\-up of the specific boot, i\&.e\&.
\fBCLOCK_MONOTONIC\fR\&. Since the monotonic clock begins new with every reboot it only defines a well\-defined point in time when used together with an identifier identifying the boot, see
\fBsd_id128_get_boot\fR(3)
for more information\&. The function will return the timestamps for the boot identified by the passed boot ID\&. Either one of the two timestamp arguments may be passed as
\fBNULL\fR
in case the timestamp is not needed, but not both\&.
.SH "RETURN VALUE"
.PP
\fBsd_journal_get_cutoff_realtime_usec()\fR
and
\fBsd_journal_get_cutoff_monotonic_usec()\fR
return 1 on success, 0 if not suitable entries are in the journal or a negative errno\-style error code\&.
.PP
Locations pointed to by parameters
\fIfrom\fR
and
\fIto\fR
will be set only if the return value is positive, and obviously, the parameters are non\-null\&.
.SH "NOTES"
.PP
The
\fBsd_journal_get_cutoff_realtime_usec()\fR
and
\fBsd_journal_get_cutoff_monotonic_usec()\fR
interfaces are available as a shared library, which can be compiled and linked to with the
\fBlibsystemd\fR\ \&\fBpkg-config\fR(1)
file\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd-journal\fR(3),
\fBsd_journal_open\fR(3),
\fBsd_journal_get_realtime_usec\fR(3),
\fBsd_id128_get_boot\fR(3),
\fBclock_gettime\fR(2)
