'\" t
.TH "SD_JOURNAL_NEXT" "3" "" "systemd 220" "sd_journal_next"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd_journal_next, sd_journal_previous, sd_journal_next_skip, sd_journal_previous_skip, SD_JOURNAL_FOREACH, SD_JOURNAL_FOREACH_BACKWARDS \- Advance or set back the read pointer in the journal
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-journal\&.h>
.fi
.ft
.HP \w'int\ sd_journal_next('u
.BI "int sd_journal_next(sd_journal\ *" "j" ");"
.HP \w'int\ sd_journal_previous('u
.BI "int sd_journal_previous(sd_journal\ *" "j" ");"
.HP \w'int\ sd_journal_next_skip('u
.BI "int sd_journal_next_skip(sd_journal\ *" "j" ", uint64_t\ " "skip" ");"
.HP \w'int\ sd_journal_previous_skip('u
.BI "int sd_journal_previous_skip(sd_journal\ *" "j" ", uint64_t\ " "skip" ");"
.HP \w'SD_JOURNAL_FOREACH('u
.BI "SD_JOURNAL_FOREACH(sd_journal\ *" "j" ");"
.HP \w'SD_JOURNAL_FOREACH_BACKWARDS('u
.BI "SD_JOURNAL_FOREACH_BACKWARDS(sd_journal\ *" "j" ");"
.SH "DESCRIPTION"
.PP
\fBsd_journal_next()\fR
advances the read pointer into the journal by one entry\&. The only argument taken is a journal context object as allocated via
\fBsd_journal_open\fR(3)\&. After successful invocation the entry may be read with functions such as
\fBsd_journal_get_data\fR(3)\&.
.PP
Similarly,
\fBsd_journal_previous()\fR
sets the read pointer back one entry\&.
.PP
\fBsd_journal_next_skip()\fR
and
\fBsd_journal_previous_skip()\fR
advance/set back the read pointer by multiple entries at once, as specified in the
\fIskip\fR
parameter\&.
.PP
The journal is strictly ordered by reception time, and hence advancing to the next entry guarantees that the entry then pointing to is later in time than then previous one, or has the same timestamp\&.
.PP
Note that
\fBsd_journal_get_data\fR(3)
and related calls will fail unless
\fBsd_journal_next()\fR
has been invoked at least once in order to position the read pointer on a journal entry\&.
.PP
Note that the
\fBSD_JOURNAL_FOREACH()\fR
macro may be used as a wrapper around
\fBsd_journal_seek_head\fR(3)
and
\fBsd_journal_next()\fR
in order to make iterating through the journal easier\&. See below for an example\&. Similarly,
\fBSD_JOURNAL_FOREACH_BACKWARDS()\fR
may be used for iterating the journal in reverse order\&.
.SH "RETURN VALUE"
.PP
The four calls return the number of entries advanced/set back on success or a negative errno\-style error code\&. When the end or beginning of the journal is reached, a number smaller than requested is returned\&. More specifically, if
\fBsd_journal_next()\fR
or
\fBsd_journal_previous()\fR
reach the end/beginning of the journal they will return 0, instead of 1 when they are successful\&. This should be considered an EOF marker\&.
.SH "NOTES"
.PP
The
\fBsd_journal_next()\fR,
\fBsd_journal_previous()\fR,
\fBsd_journal_next_skip()\fR
and
\fBsd_journal_previous_skip()\fR
interfaces are available as a shared library, which can be compiled and linked to with the
\fBlibsystemd\fR\ \&\fBpkg-config\fR(1)
file\&.
.SH "EXAMPLES"
.PP
Iterating through the journal:
.sp
.if n \{\
.RS 4
.\}
.nf
#include <stdio\&.h>
#include <string\&.h>
#include <systemd/sd\-journal\&.h>

int main(int argc, char *argv[]) {
  int r;
  sd_journal *j;
  r = sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
  if (r < 0) {
    fprintf(stderr, "Failed to open journal: %s\en", strerror(\-r));
    return 1;
  }
  SD_JOURNAL_FOREACH(j) {
    const char *d;
    size_t l;

    r = sd_journal_get_data(j, "MESSAGE", (const void **)&d, &l);
    if (r < 0) {
      fprintf(stderr, "Failed to read message field: %s\en", strerror(\-r));
      continue;
    }

    printf("%\&.*s\en", (int) l, d);
  }
  sd_journal_close(j);
  return 0;
}
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd-journal\fR(3),
\fBsd_journal_open\fR(3),
\fBsd_journal_get_data\fR(3),
\fBsd_journal_get_realtime_usec\fR(3),
\fBsd_journal_get_cursor\fR(3)
