'\" t
.TH "SD_JOURNAL_GET_FD" "3" "" "systemd 220" "sd_journal_get_fd"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd_journal_get_fd, sd_journal_get_events, sd_journal_get_timeout, sd_journal_process, sd_journal_wait, sd_journal_reliable_fd, SD_JOURNAL_NOP, SD_JOURNAL_APPEND, SD_JOURNAL_INVALIDATE \- Journal change notification interface
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-journal\&.h>
.fi
.ft
.HP \w'int\ sd_journal_get_fd('u
.BI "int sd_journal_get_fd(sd_journal\ *" "j" ");"
.HP \w'int\ sd_journal_get_events('u
.BI "int sd_journal_get_events(sd_journal\ *" "j" ");"
.HP \w'int\ sd_journal_get_timeout('u
.BI "int sd_journal_get_timeout(sd_journal\ *" "j" ", uint64_t\ *" "timeout_usec" ");"
.HP \w'int\ sd_journal_process('u
.BI "int sd_journal_process(sd_journal\ *" "j" ");"
.HP \w'int\ sd_journal_wait('u
.BI "int sd_journal_wait(sd_journal\ *" "j" ", uint64_t\ " "timeout_usec" ");"
.HP \w'int\ sd_journal_reliable_fd('u
.BI "int sd_journal_reliable_fd(sd_journal\ *" "j" ");"
.SH "DESCRIPTION"
.PP
\fBsd_journal_get_fd()\fR
returns a file descriptor that may be asynchronously polled in an external event loop and is signaled as soon as the journal changes, because new entries or files were added, rotation took place, or files have been deleted, and similar\&. The file descriptor is suitable for usage in
\fBpoll\fR(2)\&. Use
\fBsd_journal_get_events()\fR
for an events mask to watch for\&. The call takes one argument: the journal context object\&. Note that not all file systems are capable of generating the necessary events for wakeups from this file descriptor for changes to be noticed immediately\&. In particular network files systems do not generate suitable file change events in all cases\&. Cases like this can be detected with
\fBsd_journal_reliable_fd()\fR, below\&.
\fBsd_journal_get_timeout()\fR
will ensure in these cases that wake\-ups happen frequently enough for changes to be noticed, although with a certain latency\&.
.PP
\fBsd_journal_get_events()\fR
will return the
\fBpoll()\fR
mask to wait for\&. This function will return a combination of
\fBPOLLIN\fR
and
\fBPOLLOUT\fR
and similar to fill into the
"\&.events"
field of
\fIstruct pollfd\fR\&.
.PP
\fBsd_journal_get_timeout()\fR
will return a timeout value for usage in
\fBpoll()\fR\&. This returns a value in microseconds since the epoch of
\fBCLOCK_MONOTONIC\fR
for timing out
\fBpoll()\fR
in
\fItimeout_usec\fR\&. See
\fBclock_gettime\fR(2)
for details about
\fBCLOCK_MONOTONIC\fR\&. If there is no timeout to wait for, this will fill in
\fB(uint64_t) \-1\fR
instead\&. Note that
\fBpoll()\fR
takes a relative timeout in milliseconds rather than an absolute timeout in microseconds\&. To convert the absolute \*(Aqus\*(Aq timeout into relative \*(Aqms\*(Aq, use code like the following:
.sp
.if n \{\
.RS 4
.\}
.nf
uint64_t t;
int msec;
sd_journal_get_timeout(m, &t);
if (t == (uint64_t) \-1)
  msec = \-1;
else {
  struct timespec ts;
  uint64_t n;
  clock_getttime(CLOCK_MONOTONIC, &ts);
  n = (uint64_t) ts\&.tv_sec * 1000000 + ts\&.tv_nsec / 1000;
  msec = t > n ? (int) ((t \- n + 999) / 1000) : 0;
}
.fi
.if n \{\
.RE
.\}
.PP
The code above does not do any error checking for brevity\*(Aqs sake\&. The calculated
\fImsec\fR
integer can be passed directly as
\fBpoll()\fR\*(Aqs timeout parameter\&.
.PP
After each
\fBpoll()\fR
wake\-up
\fBsd_journal_process()\fR
needs to be called to process events\&. This call will also indicate what kind of change has been detected (see below; note that spurious wake\-ups are possible)\&.
.PP
A synchronous alternative for using
\fBsd_journal_get_fd()\fR,
\fBsd_journal_get_events()\fR,
\fBsd_journal_get_timeout()\fR
and
\fBsd_journal_process()\fR
is
\fBsd_journal_wait()\fR\&. It will synchronously wait until the journal gets changed\&. The maximum time this call sleeps may be controlled with the
\fItimeout_usec\fR
parameter\&. Pass
\fB(uint64_t) \-1\fR
to wait indefinitely\&. Internally this call simply combines
\fBsd_journal_get_fd()\fR,
\fBsd_journal_get_events()\fR,
\fBsd_journal_get_timeout()\fR,
\fBpoll()\fR
and
\fBsd_journal_process()\fR
into one\&.
.PP
\fBsd_journal_reliable_fd()\fR
may be used to check whether the wakeup events from the file descriptor returned by
\fBsd_journal_get_fd()\fR
are known to be immediately triggered\&. On certain file systems where file change events from the OS are not available (such as NFS) changes need to be polled for repeatedly, and hence are detected only with a certain latency\&. This call will return a positive value if the journal changes are detected immediately and zero when they need to be polled for and hence might be noticed only with a certain latency\&. Note that there\*(Aqs usually no need to invoke this function directly as
\fBsd_journal_get_timeout()\fR
on these file systems will ask for timeouts explicitly anyway\&.
.SH "RETURN VALUE"
.PP
\fBsd_journal_get_fd()\fR
returns a valid file descriptor on success or a negative errno\-style error code\&.
.PP
\fBsd_journal_get_events()\fR
returns a combination of
\fBPOLLIN\fR,
\fBPOLLOUT\fR
and suchlike on success or a negative errno\-style error code\&.
.PP
\fBsd_journal_reliable_fd()\fR
returns a positive integer if the file descriptor returned by
\fBsd_journal_get_fd()\fR
will generate wake\-ups immediately for all journal changes\&. Returns 0 if there might be a latency involved\&.
.PP
\fBsd_journal_process()\fR
and
\fBsd_journal_wait()\fR
return one of
\fBSD_JOURNAL_NOP\fR,
\fBSD_JOURNAL_APPEND\fR
or
\fBSD_JOURNAL_INVALIDATE\fR
on success or a negative errno\-style error code\&. If
\fBSD_JOURNAL_NOP\fR
is returned, the journal did not change since the last invocation\&. If
\fBSD_JOURNAL_APPEND\fR
is returned, new entries have been appended to the end of the journal\&. If
\fBSD_JOURNAL_INVALIDATE\fR, journal files were added or removed (possibly due to rotation)\&. In the latter event, live\-view UIs should probably refresh their entire display, while in the case of
\fBSD_JOURNAL_APPEND\fR, it is sufficient to simply continue reading at the previous end of the journal\&.
.SH "NOTES"
.PP
The
\fBsd_journal_get_fd()\fR,
\fBsd_journal_get_events()\fR,
\fBsd_journal_reliable_fd()\fR,
\fBsd_journal_process()\fR
and
\fBsd_journal_wait()\fR
interfaces are available as a shared library, which can be compiled and linked to with the
\fBlibsystemd\fR\ \&\fBpkg-config\fR(1)
file\&.
.SH "EXAMPLES"
.PP
Iterating through the journal, in a live view tracking all changes:
.sp
.if n \{\
.RS 4
.\}
.nf
#include <stdio\&.h>
#include <string\&.h>
#include <systemd/sd\-journal\&.h>

int main(int argc, char *argv[]) {
  int r;
  sd_journal *j;
  r = sd_journal_open(&j, SD_JOURNAL_LOCAL_ONLY);
  if (r < 0) {
    fprintf(stderr, "Failed to open journal: %s\en", strerror(\-r));
    return 1;
  }
  for (;;)  {
    const void *d;
    size_t l;
    r = sd_journal_next(j);
    if (r < 0) {
      fprintf(stderr, "Failed to iterate to next entry: %s\en", strerror(\-r));
      break;
    }
    if (r == 0) {
      /* Reached the end, let\*(Aqs wait for changes, and try again */
      r = sd_journal_wait(j, (uint64_t) \-1);
      if (r < 0) {
        fprintf(stderr, "Failed to wait for changes: %s\en", strerror(\-r));
        break;
      }
      continue;
    }
    r = sd_journal_get_data(j, "MESSAGE", &d, &l);
    if (r < 0) {
      fprintf(stderr, "Failed to read message field: %s\en", strerror(\-r));
      continue;
    }
    printf("%\&.*s\en", (int) l, (const char*) d);
  }
  sd_journal_close(j);
  return 0;
}
.fi
.if n \{\
.RE
.\}
.PP
Waiting with
\fBpoll()\fR
(this example lacks all error checking for the sake of simplicity):
.sp
.if n \{\
.RS 4
.\}
.nf
#include <poll\&.h>
#include <systemd/sd\-journal\&.h>

int wait_for_changes(sd_journal *j) {
  struct pollfd pollfd;
  int msec;

  sd_journal_get_timeout(m, &t);
  if (t == (uint64_t) \-1)
    msec = \-1;
  else {
    struct timespec ts;
    uint64_t n;
    clock_getttime(CLOCK_MONOTONIC, &ts);
    n = (uint64_t) ts\&.tv_sec * 1000000 + ts\&.tv_nsec / 1000;
    msec = t > n ? (int) ((t \- n + 999) / 1000) : 0;
  }

  pollfd\&.fd = sd_journal_get_fd(j);
  pollfd\&.events = sd_journal_get_events(j);
  poll(&pollfd, 1, msec);
  return sd_journal_process(j);
}
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd-journal\fR(3),
\fBsd_journal_open\fR(3),
\fBsd_journal_next\fR(3),
\fBpoll\fR(2),
\fBclock_gettime\fR(2)
