'\" t
.TH "SD_JOURNAL_ADD_MATCH" "3" "" "systemd 215" "sd_journal_add_match"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd_journal_add_match, sd_journal_add_disjunction, sd_journal_add_conjunction, sd_journal_flush_matches \- Add or remove entry matches
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-journal\&.h>
.fi
.ft
.HP \w'int\ sd_journal_add_match('u
.BI "int sd_journal_add_match(sd_journal\ *" "j" ", const\ void\ *" "data" ", size_t\ " "size" ");"
.HP \w'int\ sd_journal_add_disjunction('u
.BI "int sd_journal_add_disjunction(sd_journal\ *" "j" ");"
.HP \w'int\ sd_journal_add_conjunction('u
.BI "int sd_journal_add_conjunction(sd_journal\ *" "j" ");"
.HP \w'void\ sd_journal_flush_matches('u
.BI "void sd_journal_flush_matches(sd_journal\ *" "j" ");"
.SH "DESCRIPTION"
.PP
\fBsd_journal_add_match()\fR
adds a match by which to filter the entries of the journal file\&. Matches applied with this call will filter what can be iterated through and read from the journal file via calls like
\fBsd_journal_next\fR(3)
and
\fBsd_journal_get_data\fR(3)\&. Matches are of the form
"FIELD=value", where the field part is a short uppercase string consisting only of 0\-9, A\-Z and the underscore\&. It may not begin with two underscores or be the empty string\&. The value part may be any value, including binary\&. If a match is applied, only entries with this field set will be iterated\&. Multiple matches may be active at the same time: If they apply to different fields, only entries with both fields set like this will be iterated\&. If they apply to the same fields, only entries where the field takes one of the specified values will be iterated\&. Well known fields are documented in
\fBsystemd.journal-fields\fR(7)\&. Whenever a new match is added the current entry position is reset, and
\fBsd_journal_next\fR(3)
(or a similar call) needs to be called before entries can be read again\&.
.PP
\fBsd_journal_add_disjunction()\fR
may be used to insert a disjunction (i\&.e\&. logical OR) in the match list\&. If this call is invoked, all previously added matches since the last invocation of
\fBsd_journal_add_disjunction()\fR
or
\fBsd_journal_add_conjunction()\fR
are combined in an OR with all matches added afterwards, until
\fBsd_journal_add_disjunction()\fR
or
\fBsd_journal_add_conjunction()\fR
is invoked again to begin the next OR or AND term\&.
.PP
\fBsd_journal_add_conjunction()\fR
may be used to insert a conjunction (i\&.e\&. logical AND) in the match list\&. If this call is invoked, all previously added matches since the last invocation of
\fBsd_journal_add_conjunction()\fR
are combined in an AND with all matches added afterwards, until
\fBsd_journal_add_conjunction()\fR
is invoked again to begin the next AND term\&. The combination of
\fBsd_journal_add_match()\fR,
\fBsd_journal_add_disjunction()\fR
and
\fBsd_journal_add_conjunction()\fR
may be used to build complex search terms, even though full logical expressions are not available\&. Note that
\fBsd_journal_add_conjunction()\fR
operates one level \*(Aqhigher\*(Aq than
\fBsd_journal_add_disjunction()\fR\&. It is hence possible to build an expression of AND terms, consisting of OR terms, consisting of AND terms, consisting of OR terms of matches (the latter OR expression is implicitly created for matches with the same field name, see above)\&.
.PP
\fBsd_journal_flush_matches()\fR
may be used to flush all matches, disjunction and conjunction terms again\&. After this call all filtering is removed and all entries in the journal will be iterated again\&.
.PP
Note that filtering via matches only applies to the way the journal is read, it has no effect on storage on disk\&.
.SH "RETURN VALUE"
.PP
\fBsd_journal_add_match()\fR,
\fBsd_journal_add_disjunction()\fR
and
\fBsd_journal_add_conjunction()\fR
return 0 on success or a negative errno\-style error code\&.
\fBsd_journal_flush_matches()\fR
returns nothing\&.
.SH "NOTES"
.PP
The
\fBsd_journal_add_match()\fR,
\fBsd_journal_add_disjunction()\fR,
\fBsd_journal_add_conjunction()\fR
and
\fBsd_journal_flush_matches()\fR
interfaces are available as a shared library, which can be compiled and linked to with the
\fBlibsystemd\fR\ \&\fBpkg-config\fR(1)
file\&.
.SH "EXAMPLES"
.PP
The following example adds matches to a journal context object to iterate only through messages generated by the Avahi service at the four error log levels, plus all messages of the message ID 03bb1dab98ab4ecfbf6fff2738bdd964 coming from any service (this example lacks the necessary error checking):
.sp
.if n \{\
.RS 4
.\}
.nf
\&.\&.\&.
int add_matches(sd_journal *j) {
        sd_journal_add_match(j, "_SYSTEMD_UNIT=avahi\-daemon\&.service", 0);
        sd_journal_add_match(j, "PRIORITY=0", 0);
        sd_journal_add_match(j, "PRIORITY=1", 0);
        sd_journal_add_match(j, "PRIORITY=2", 0);
        sd_journal_add_match(j, "PRIORITY=3", 0);
        sd_journal_add_disjunction(j);
        sd_journal_add_match(j, "MESSAGE_ID=03bb1dab98ab4ecfbf6fff2738bdd964", 0);
}
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd-journal\fR(3),
\fBsd_journal_open\fR(3),
\fBsd_journal_next\fR(3),
\fBsd_journal_get_data\fR(3),
\fBsystemd.journal-fields\fR(7)
