'\" t
.TH "SD_MACHINE_GET_CLASS" "3" "" "systemd 221" "sd_machine_get_class"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sd_machine_get_class, sd_machine_get_ifindices \- Determine the class and network interface indices of a locally running virtual machine or container\&.
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <systemd/sd\-login\&.h>
.fi
.ft
.HP \w'int\ sd_machine_get_class('u
.BI "int sd_machine_get_class(const\ char*\ " "machine" ", char\ *" "class" ");"
.HP \w'int\ sd_machine_get_ifindices('u
.BI "int sd_machine_get_ifindices(const\ char*\ " "machine" ", int\ **" "ifindices" ");"
.SH "DESCRIPTION"
.PP
\fBsd_machine_get_class()\fR
may be used to determine the class of a locally running virtual machine or container that is registered with
\fBsystemd-machined.service\fR(8)\&. The string returned is either
"vm"
or
"container"\&. The returned string needs to be freed with the libc
\fBfree\fR(3)
call after use\&.
.PP
\fBsd_machine_get_ifindices()\fR
may be used to determine the numeric indices of the network interfaces on the host that are pointing towards the specified locally running virtual machine or container that is registered with
\fBsystemd-machined.service\fR(8)\&. The returned array needs to be freed with the libc
\fBfree\fR(3)
call after use\&.
.SH "RETURN VALUE"
.PP
On success, these calls return 0 or a positive integer\&. On failure, these calls return a negative errno\-style error code\&.
.SH "NOTES"
.PP
The
\fBsd_machine_get_class()\fR
and
\fBsd_machine_get_ifindices()\fR
interfaces are available as a shared library, which can be compiled and linked to with the
\fBlibsystemd\fR\ \&\fBpkg-config\fR(1)
file\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsd-login\fR(3),
\fBsystemd-machined.service\fR(8),
\fBsd_pid_get_machine_name\fR(3)
