'\" t
.TH "SHUTDOWN" "8" "" "systemd 215" "shutdown"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
shutdown \- Halt, power\-off or reboot the machine
.SH "SYNOPSIS"
.HP \w'\fBshutdown\ \fR\fB[OPTIONS...]\fR\fB\ \fR\fB[TIME]\fR\fB\ \fR\fB[WALL...]\fR\ 'u
\fBshutdown \fR\fB[OPTIONS...]\fR\fB \fR\fB[TIME]\fR\fB \fR\fB[WALL...]\fR
.SH "DESCRIPTION"
.PP
\fBshutdown\fR
may be used to halt, power\-off or reboot the machine\&.
.PP
The first argument may be a time string (which is usually
"now")\&. Optionally, this may be followed by a wall message to be sent to all logged\-in users before going down\&.
.PP
The time string may either be in the format
"hh:mm"
for hour/minutes specifying the time to execute the shutdown at, specified in 24h clock format\&. Alternatively it may be in the syntax
"+m"
referring to the specified number of minutes m from now\&.
"now"
is an alias for
"+0", i\&.e\&. for triggering an immediate shutdown\&. If no time argument is specified,
"+1"
is implied\&.
.PP
Note that to specify a wall message you must specify a time argument, too\&.
.PP
If the time argument is used, 5 minutes before the system goes down the
/run/nologin
file is created to ensure that further logins shall not be allowed\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-H\fR, \fB\-\-halt\fR
.RS 4
Halt the machine\&.
.RE
.PP
\fB\-P\fR, \fB\-\-poweroff\fR
.RS 4
Power\-off the machine (the default)\&.
.RE
.PP
\fB\-r\fR, \fB\-\-reboot\fR
.RS 4
Reboot the machine\&.
.RE
.PP
\fB\-h\fR
.RS 4
Equivalent to
\fB\-\-poweroff\fR, unless
\fB\-\-halt\fR
is specified\&.
.RE
.PP
\fB\-k\fR
.RS 4
Do not halt, power\-off, reboot, just write wall message\&.
.RE
.PP
\fB\-\-no\-wall\fR
.RS 4
Do not send wall message before halt, power\-off, reboot\&.
.RE
.PP
\fB\-c\fR
.RS 4
Cancel a pending shutdown\&. This may be used cancel the effect of an invocation of
\fBshutdown\fR
with a time argument that is not
"+0"
or
"now"\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBhalt\fR(8),
\fBwall\fR(1)
