'\" t
.TH "SYSTEMD\-COREDUMP" "8" "" "systemd 220" "systemd-coredump"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-coredump \- Log and store core dumps
.SH "SYNOPSIS"
.PP
/usr/lib/systemd/systemd\-coredump
.SH "DESCRIPTION"
.PP
\fBsystemd\-coredump\fR
can be used as a helper binary by the kernel when a user space program receives a fatal signal and dumps core\&. For it to be used in this capacity, it must be specified by the
\fIkernel\&.core_pattern\fR\ \&\fBsysctl\fR(8)
setting\&. Systemd installs
/usr/lib/sysctl\&.d/50\-coredump\&.conf
which configures
\fIkernel\&.core_pattern\fR
to invoke
\fBsystemd\-coredump\fR\&. This file may be masked or overridden to use a different setting following normal
\fBsysctl.d\fR(5)
rules\&.
.PP
The behaviour of a specific program upon reception of a signal is governed by a few factors which are described in detail in
\fBcore\fR(5)\&. In particular, the coredump will only be processed when the related resource limits are high enough\&. For programs started by
\fBsystemd\fR
those may be set using
\fILimitCore=\fR
(see
\fBsystemd.exec\fR(5))\&.
.PP
\fBsystemd\-coredump\fR
will log the coredump including a backtrace if possible, and store the core (contents of process\*(Aq memory contents) in an external file on disk in
/var/lib/systemd/coredump, or directly in the journal\&. This behaviour may be modified using
\fBcoredump.conf\fR(5)\&.
.PP
Apart from the
\fBjournalctl\fR(1)
log viewer,
\fBcoredumpctl\fR(1)
may be used to list and extract coredumps\&.
.SH "SEE ALSO"
.PP
\fBcoredump.conf\fR(5),
\fBcoredumpctl\fR(1),
\fBsystemd-journald.service\fR(8),
\fBcore\fR(5),
\fBsysctl.d\fR(5),
\fBsystemd-sysctl.service\fR(8)\&.
