'\" t
.TH "SYSTEMD\-EFI\-BOOT\-GENERATOR" "8" "" "systemd 221" "systemd-efi-boot-generator"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-efi-boot-generator \- Generator for automatically mounting the EFI System Partition used by the current boot to /boot
.SH "SYNOPSIS"
.PP
/usr/lib/systemd/system\-generators/systemd\-efi\-boot\-generator
.SH "DESCRIPTION"
.PP
systemd\-efi\-boot\-generator
is a generator that automatically creates mount and automount units for the EFI System Partition (ESP), mounting it to
/boot\&. Note that this generator will execute no operation on non\-EFI systems, on systems where the boot loader does not communicate the used ESP to the OS, on systems where
/boot
is an explicitly configured mount (for example, listed in
\fBfstab\fR(5)) or where the
/boot
mount point is non\-empty\&. Since this generator creates an automount unit, the mount will only be activated on\-demand, when accessed\&.
.PP
systemd\-efi\-boot\-generator
implements
\fBsystemd.generator\fR(7)\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd.mount\fR(5),
\fBsystemd.automount\fR(5),
\fBsystemd-gpt-auto-generator\fR(8),
\fBfstab\fR(5)
