'\" t
.TH "SYSTEMD\&.UNIT" "5" "" "systemd 215" "systemd.unit"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.unit \- Unit configuration
.SH "SYNOPSIS"
.PP
\fIservice\fR\&.service,
\fIsocket\fR\&.socket,
\fIdevice\fR\&.device,
\fImount\fR\&.mount,
\fIautomount\fR\&.automount,
\fIswap\fR\&.swap,
\fItarget\fR\&.target,
\fIpath\fR\&.path,
\fItimer\fR\&.timer,
\fIsnapshot\fR\&.snapshot,
\fIslice\fR\&.slice,
\fIscope\fR\&.scope
.PP
.nf
/etc/systemd/system/*
/run/systemd/system/*
/usr/lib/systemd/system/*
\&.\&.\&.
                
.fi
.PP
.nf
$XDG_CONFIG_HOME/systemd/user/*
$HOME/\&.config/systemd/user/*
/etc/systemd/user/*
/run/systemd/user/*
/usr/lib/systemd/user/*
\&.\&.\&.
                
.fi
.SH "DESCRIPTION"
.PP
A unit configuration file encodes information about a service, a socket, a device, a mount point, an automount point, a swap file or partition, a start\-up target, a watched file system path, a timer controlled and supervised by
\fBsystemd\fR(1), a temporary system state snapshot, a resource management slice or a group of externally created processes\&. The syntax is inspired by
\m[blue]\fBXDG Desktop Entry Specification\fR\m[]\&\s-2\u[1]\d\s+2\&.desktop
files, which are in turn inspired by Microsoft Windows
\&.ini
files\&.
.PP
This man page lists the common configuration options of all the unit types\&. These options need to be configured in the [Unit] or [Install] sections of the unit files\&.
.PP
In addition to the generic [Unit] and [Install] sections described here, each unit may have a type\-specific section, e\&.g\&. [Service] for a service unit\&. See the respective man pages for more information:
\fBsystemd.service\fR(5),
\fBsystemd.socket\fR(5),
\fBsystemd.device\fR(5),
\fBsystemd.mount\fR(5),
\fBsystemd.automount\fR(5),
\fBsystemd.swap\fR(5),
\fBsystemd.target\fR(5),
\fBsystemd.path\fR(5),
\fBsystemd.timer\fR(5),
\fBsystemd.snapshot\fR(5)\&.
\fBsystemd.slice\fR(5)\&.
\fBsystemd.scope\fR(5)\&.
.PP
Various settings are allowed to be specified more than once, in which case the interpretation depends on the setting\&. Often, multiple settings form a list, and setting to an empty value "resets", which means that previous assignments are ignored\&. When this is allowed, it is mentioned in the description of the setting\&. Note that using multiple assignments to the same value makes the unit file incompatible with parsers for the XDG
\&.desktop
file format\&.
.PP
Unit files are loaded from a set of paths determined during compilation, described in the next section\&.
.PP
Unit files may contain additional options on top of those listed here\&. If systemd encounters an unknown option, it will write a warning log message but continue loading the unit\&. If an option or section name is prefixed with
\fBX\-\fR, it is ignored completely by systemd\&. Options within an ignored section do not need the prefix\&. Applications may use this to include additional information in the unit files\&.
.PP
Boolean arguments used in unit files can be written in various formats\&. For positive settings the strings
\fB1\fR,
\fByes\fR,
\fBtrue\fR
and
\fBon\fR
are equivalent\&. For negative settings, the strings
\fB0\fR,
\fBno\fR,
\fBfalse\fR
and
\fBoff\fR
are equivalent\&.
.PP
Time span values encoded in unit files can be written in various formats\&. A stand\-alone number specifies a time in seconds\&. If suffixed with a time unit, the unit is honored\&. A concatenation of multiple values with units is supported, in which case the values are added up\&. Example: "50" refers to 50 seconds; "2min 200ms" refers to 2 minutes plus 200 milliseconds, i\&.e\&. 120200ms\&. The following time units are understood: s, min, h, d, w, ms, us\&. For details see
\fBsystemd.time\fR(7)\&.
.PP
Empty lines and lines starting with # or ; are ignored\&. This may be used for commenting\&. Lines ending in a backslash are concatenated with the following line while reading and the backslash is replaced by a space character\&. This may be used to wrap long lines\&.
.PP
Along with a unit file
foo\&.service, the directory
foo\&.service\&.wants/
may exist\&. All unit files symlinked from such a directory are implicitly added as dependencies of type
\fIWanted=\fR
to the unit\&. This is useful to hook units into the start\-up of other units, without having to modify their unit files\&. For details about the semantics of
\fIWanted=\fR, see below\&. The preferred way to create symlinks in the
\&.wants/
directory of a unit file is with the
\fBenable\fR
command of the
\fBsystemctl\fR(1)
tool which reads information from the [Install] section of unit files (see below)\&. A similar functionality exists for
\fIRequires=\fR
type dependencies as well, the directory suffix is
\&.requires/
in this case\&.
.PP
Along with a unit file
foo\&.service, a directory
foo\&.service\&.d/
may exist\&. All files with the suffix
"\&.conf"
from this directory will be parsed after the file itself is parsed\&. This is useful to alter or add configuration settings to a unit, without having to modify their unit files\&. Make sure that the file that is included has the appropriate section headers before any directive\&.
.PP
Note that while systemd offers a flexible dependency system between units it is recommended to use this functionality only sparingly and instead rely on techniques such as bus\-based or socket\-based activation which make dependencies implicit, resulting in a both simpler and more flexible system\&.
.PP
Some unit names reflect paths existing in the file system namespace\&. Example: a device unit
dev\-sda\&.device
refers to a device with the device node
/dev/sda
in the file system namespace\&. If this applies, a special way to escape the path name is used, so that the result is usable as part of a filename\&. Basically, given a path, "/" is replaced by "\-", and all unprintable characters and the "\-" are replaced by C\-style "\ex20" escapes\&. The root directory "/" is encoded as single dash, while otherwise the initial and ending "/" is removed from all paths during transformation\&. This escaping is reversible\&.
.PP
Optionally, units may be instantiated from a template file at runtime\&. This allows creation of multiple units from a single configuration file\&. If systemd looks for a unit configuration file, it will first search for the literal unit name in the file system\&. If that yields no success and the unit name contains an
"@"
character, systemd will look for a unit template that shares the same name but with the instance string (i\&.e\&. the part between the
"@"
character and the suffix) removed\&. Example: if a service
getty@tty3\&.service
is requested and no file by that name is found, systemd will look for
getty@\&.service
and instantiate a service from that configuration file if it is found\&.
.PP
To refer to the instance string from within the configuration file you may use the special
"%i"
specifier in many of the configuration options\&. See below for details\&.
.PP
If a unit file is empty (i\&.e\&. has the file size 0) or is symlinked to
/dev/null, its configuration will not be loaded and it appears with a load state of
"masked", and cannot be activated\&. Use this as an effective way to fully disable a unit, making it impossible to start it even manually\&.
.PP
The unit file format is covered by the
\m[blue]\fBInterface Stability Promise\fR\m[]\&\s-2\u[2]\d\s+2\&.
.SH "UNIT LOAD PATH"
.PP
Unit files are loaded from a set of paths determined during compilation, described in the two tables below\&. Unit files found in directories listed earlier override files with the same name in directories lower in the list\&.
.PP
When systemd is running in user mode (\fB\-\-user\fR) and the variable
\fI$SYSTEMD_UNIT_PATH\fR
is set, this contents of this variable overrides the unit load path\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \& Load path when running in system mode (\-\-system).
.TS
allbox tab(:);
lB lB.
T{
Path
T}:T{
Description
T}
.T&
l l
l l
l l.
T{
/etc/systemd/system
T}:T{
Local configuration
T}
T{
/run/systemd/system
T}:T{
Runtime units
T}
T{
/usr/lib/systemd/system
T}:T{
Units of installed packages
T}
.TE
.sp 1
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&2.\ \& Load path when running in user mode (\-\-user).
.TS
allbox tab(:);
lB lB.
T{
Path
T}:T{
Description
T}
.T&
l l
l l
l l
l l
l l.
T{
$XDG_CONFIG_HOME/systemd/user
T}:T{
User configuration (only used when $XDG_CONFIG_HOME is set)
T}
T{
$HOME/\&.config/systemd/user
T}:T{
User configuration (only used when $XDG_CONFIG_HOME is not set)
T}
T{
/etc/systemd/user
T}:T{
Local configuration
T}
T{
/run/systemd/user
T}:T{
Runtime units
T}
T{
/usr/lib/systemd/user
T}:T{
Units of installed packages
T}
.TE
.sp 1
.PP
Additional units might be loaded into systemd ("linked") from directories not on the unit load path\&. See the
\fBlink\fR
command for
\fBsystemctl\fR(1)\&. Also, some units are dynamically created via generators
\m[blue]\fBGenerators\fR\m[]\&\s-2\u[3]\d\s+2\&.
.SH "[UNIT] SECTION OPTIONS"
.PP
Unit file may include a [Unit] section, which carries generic information about the unit that is not dependent on the type of unit:
.PP
\fIDescription=\fR
.RS 4
A free\-form string describing the unit\&. This is intended for use in UIs to show descriptive information along with the unit name\&. The description should contain a name that means something to the end user\&.
"Apache2 Web Server"
is a good example\&. Bad examples are
"high\-performance light\-weight HTTP server"
(too generic) or
"Apache2"
(too specific and meaningless for people who do not know Apache)\&.
.RE
.PP
\fIDocumentation=\fR
.RS 4
A space\-separated list of URIs referencing documentation for this unit or its configuration\&. Accepted are only URIs of the types
"http://",
"https://",
"file:",
"info:",
"man:"\&. For more information about the syntax of these URIs, see
\fBuri\fR(7)\&. The URIs should be listed in order of relevance, starting with the most relevant\&. It is a good idea to first reference documentation that explains what the unit\*(Aqs purpose is, followed by how it is configured, followed by any other related documentation\&. This option may be specified more than once, in which case the specified list of URIs is merged\&. If the empty string is assigned to this option, the list is reset and all prior assignments will have no effect\&.
.RE
.PP
\fIRequires=\fR
.RS 4
Configures requirement dependencies on other units\&. If this unit gets activated, the units listed here will be activated as well\&. If one of the other units gets deactivated or its activation fails, this unit will be deactivated\&. This option may be specified more than once or multiple space\-separated units may be specified in one option in which case requirement dependencies for all listed names will be created\&. Note that requirement dependencies do not influence the order in which services are started or stopped\&. This has to be configured independently with the
\fIAfter=\fR
or
\fIBefore=\fR
options\&. If a unit
foo\&.service
requires a unit
bar\&.service
as configured with
\fIRequires=\fR
and no ordering is configured with
\fIAfter=\fR
or
\fIBefore=\fR, then both units will be started simultaneously and without any delay between them if
foo\&.service
is activated\&. Often it is a better choice to use
\fIWants=\fR
instead of
\fIRequires=\fR
in order to achieve a system that is more robust when dealing with failing services\&.
.sp
Note that dependencies of this type may also be configured outside of the unit configuration file by adding a symlink to a
\&.requires/
directory accompanying the unit file\&. For details see above\&.
.RE
.PP
\fIRequiresOverridable=\fR
.RS 4
Similar to
\fIRequires=\fR\&. Dependencies listed in
\fIRequiresOverridable=\fR
which cannot be fulfilled or fail to start are ignored if the startup was explicitly requested by the user\&. If the start\-up was pulled in indirectly by some dependency or automatic start\-up of units that is not requested by the user, this dependency must be fulfilled and otherwise the transaction fails\&. Hence, this option may be used to configure dependencies that are normally honored unless the user explicitly starts up the unit, in which case whether they failed or not is irrelevant\&.
.RE
.PP
\fIRequisite=\fR, \fIRequisiteOverridable=\fR
.RS 4
Similar to
\fIRequires=\fR
and
\fIRequiresOverridable=\fR, respectively\&. However, if the units listed here are not started already, they will not be started and the transaction will fail immediately\&.
.RE
.PP
\fIWants=\fR
.RS 4
A weaker version of
\fIRequires=\fR\&. Units listed in this option will be started if the configuring unit is\&. However, if the listed units fail to start or cannot be added to the transaction, this has no impact on the validity of the transaction as a whole\&. This is the recommended way to hook start\-up of one unit to the start\-up of another unit\&.
.sp
Note that dependencies of this type may also be configured outside of the unit configuration file by adding symlinks to a
\&.wants/
directory accompanying the unit file\&. For details, see above\&.
.RE
.PP
\fIBindsTo=\fR
.RS 4
Configures requirement dependencies, very similar in style to
\fIRequires=\fR, however in addition to this behavior, it also declares that this unit is stopped when any of the units listed suddenly disappears\&. Units can suddenly, unexpectedly disappear if a service terminates on its own choice, a device is unplugged or a mount point unmounted without involvement of systemd\&.
.RE
.PP
\fIPartOf=\fR
.RS 4
Configures dependencies similar to
\fIRequires=\fR, but limited to stopping and restarting of units\&. When systemd stops or restarts the units listed here, the action is propagated to this unit\&. Note that this is a one\-way dependency\ \&\(em changes to this unit do not affect the listed units\&.
.RE
.PP
\fIConflicts=\fR
.RS 4
A space\-separated list of unit names\&. Configures negative requirement dependencies\&. If a unit has a
\fIConflicts=\fR
setting on another unit, starting the former will stop the latter and vice versa\&. Note that this setting is independent of and orthogonal to the
\fIAfter=\fR
and
\fIBefore=\fR
ordering dependencies\&.
.sp
If a unit A that conflicts with a unit B is scheduled to be started at the same time as B, the transaction will either fail (in case both are required part of the transaction) or be modified to be fixed (in case one or both jobs are not a required part of the transaction)\&. In the latter case, the job that is not the required will be removed, or in case both are not required, the unit that conflicts will be started and the unit that is conflicted is stopped\&.
.RE
.PP
\fIBefore=\fR, \fIAfter=\fR
.RS 4
A space\-separated list of unit names\&. Configures ordering dependencies between units\&. If a unit
foo\&.service
contains a setting
\fBBefore=bar\&.service\fR
and both units are being started,
bar\&.service\*(Aqs start\-up is delayed until
foo\&.service
is started up\&. Note that this setting is independent of and orthogonal to the requirement dependencies as configured by
\fIRequires=\fR\&. It is a common pattern to include a unit name in both the
\fIAfter=\fR
and
\fIRequires=\fR
option, in which case the unit listed will be started before the unit that is configured with these options\&. This option may be specified more than once, in which case ordering dependencies for all listed names are created\&.
\fIAfter=\fR
is the inverse of
\fIBefore=\fR, i\&.e\&. while
\fIAfter=\fR
ensures that the configured unit is started after the listed unit finished starting up,
\fIBefore=\fR
ensures the opposite, i\&.e\&. that the configured unit is fully started up before the listed unit is started\&. Note that when two units with an ordering dependency between them are shut down, the inverse of the start\-up order is applied\&. i\&.e\&. if a unit is configured with
\fIAfter=\fR
on another unit, the former is stopped before the latter if both are shut down\&. If one unit with an ordering dependency on another unit is shut down while the latter is started up, the shut down is ordered before the start\-up regardless of whether the ordering dependency is actually of type
\fIAfter=\fR
or
\fIBefore=\fR\&. If two units have no ordering dependencies between them, they are shut down or started up simultaneously, and no ordering takes place\&.
.RE
.PP
\fIOnFailure=\fR
.RS 4
A space\-separated list of one or more units that are activated when this unit enters the
"failed"
state\&.
.RE
.PP
\fIPropagatesReloadTo=\fR, \fIReloadPropagatedFrom=\fR
.RS 4
A space\-separated list of one or more units where reload requests on this unit will be propagated to, or reload requests on the other unit will be propagated to this unit, respectively\&. Issuing a reload request on a unit will automatically also enqueue a reload request on all units that the reload request shall be propagated to via these two settings\&.
.RE
.PP
\fIJoinsNamespaceOf=\fR
.RS 4
For units that start processes (such as service units), lists one or more other units whose network and/or temporary file namespace to join\&. This only applies to unit types which support the
\fIPrivateNetwork=\fR
and
\fIPrivateTmp=\fR
directives (see
\fBsystemd.exec\fR(5)
for details)\&. If a unit that has this setting set is started, its processes will see the same
/tmp,
/tmp/var
and network namespace as one listed unit that is started\&. If multiple listed units are already started, it is not defined which namespace is joined\&. Note that this setting only has an effect if
\fIPrivateNetwork=\fR
and/or
\fIPrivateTmp=\fR
is enabled for both the unit that joins the namespace and the unit whose namespace is joined\&.
.RE
.PP
\fIRequiresMountsFor=\fR
.RS 4
Takes a space\-separated list of absolute paths\&. Automatically adds dependencies of type
\fIRequires=\fR
and
\fIAfter=\fR
for all mount units required to access the specified path\&.
.sp
Mount points marked with
\fBnoauto\fR
are not mounted automatically and will be ignored for the purposes of this option\&. If such a mount should be a requirement for this unit, direct dependencies on the mount units may be added (\fIRequires=\fR
and
\fIAfter=\fR
or some other combination)\&.
.RE
.PP
\fIOnFailureJobMode=\fR
.RS 4
Takes a value of
"fail",
"replace",
"replace\-irreversibly",
"isolate",
"flush",
"ignore\-dependencies"
or
"ignore\-requirements"\&. Defaults to
"replace"\&. Specifies how the units listed in
\fIOnFailure=\fR
will be enqueued\&. See
\fBsystemctl\fR(1)\*(Aqs
\fB\-\-job\-mode=\fR
option for details on the possible values\&. If this is set to
"isolate", only a single unit may be listed in
\fIOnFailure=\fR\&.\&.
.RE
.PP
\fIIgnoreOnIsolate=\fR
.RS 4
Takes a boolean argument\&. If
\fBtrue\fR, this unit will not be stopped when isolating another unit\&. Defaults to
\fBfalse\fR\&.
.RE
.PP
\fIIgnoreOnSnapshot=\fR
.RS 4
Takes a boolean argument\&. If
\fBtrue\fR, this unit will not be included in snapshots\&. Defaults to
\fBtrue\fR
for device and snapshot units,
\fBfalse\fR
for the others\&.
.RE
.PP
\fIStopWhenUnneeded=\fR
.RS 4
Takes a boolean argument\&. If
\fBtrue\fR, this unit will be stopped when it is no longer used\&. Note that in order to minimize the work to be executed, systemd will not stop units by default unless they are conflicting with other units, or the user explicitly requested their shut down\&. If this option is set, a unit will be automatically cleaned up if no other active unit requires it\&. Defaults to
\fBfalse\fR\&.
.RE
.PP
\fIRefuseManualStart=\fR, \fIRefuseManualStop=\fR
.RS 4
Takes a boolean argument\&. If
\fBtrue\fR, this unit can only be activated or deactivated indirectly\&. In this case, explicit start\-up or termination requested by the user is denied, however if it is started or stopped as a dependency of another unit, start\-up or termination will succeed\&. This is mostly a safety feature to ensure that the user does not accidentally activate units that are not intended to be activated explicitly, and not accidentally deactivate units that are not intended to be deactivated\&. These options default to
\fBfalse\fR\&.
.RE
.PP
\fIAllowIsolate=\fR
.RS 4
Takes a boolean argument\&. If
\fBtrue\fR, this unit may be used with the
\fBsystemctl isolate\fR
command\&. Otherwise, this will be refused\&. It probably is a good idea to leave this disabled except for target units that shall be used similar to runlevels in SysV init systems, just as a precaution to avoid unusable system states\&. This option defaults to
\fBfalse\fR\&.
.RE
.PP
\fIDefaultDependencies=\fR
.RS 4
Takes a boolean argument\&. If
\fBtrue\fR, (the default), a few default dependencies will implicitly be created for the unit\&. The actual dependencies created depend on the unit type\&. For example, for service units, these dependencies ensure that the service is started only after basic system initialization is completed and is properly terminated on system shutdown\&. See the respective man pages for details\&. Generally, only services involved with early boot or late shutdown should set this option to
\fBfalse\fR\&. It is highly recommended to leave this option enabled for the majority of common units\&. If set to
\fBfalse\fR, this option does not disable all implicit dependencies, just non\-essential ones\&.
.RE
.PP
\fIJobTimeoutSec=\fR
.RS 4
When clients are waiting for a job of this unit to complete, time out after the specified time\&. If this time limit is reached, the job will be cancelled, the unit however will not change state or even enter the
"failed"
mode\&. This value defaults to 0 (job timeouts disabled), except for device units\&. NB: this timeout is independent from any unit\-specific timeout (for example, the timeout set with
\fITimeout=\fR
in service units) as the job timeout has no effect on the unit itself, only on the job that might be pending for it\&. Or in other words: unit\-specific timeouts are useful to abort unit state changes, and revert them\&. The job timeout set with this option however is useful to abort only the job waiting for the unit state to change\&.
.RE
.PP
\fIConditionArchitecture=\fR, \fIConditionVirtualization=\fR, \fIConditionHost=\fR, \fIConditionKernelCommandLine=\fR, \fIConditionSecurity=\fR, \fIConditionCapability=\fR, \fIConditionACPower=\fR, \fIConditionNeedsUpdate=\fR, \fIConditionPathExists=\fR, \fIConditionPathExistsGlob=\fR, \fIConditionPathIsDirectory=\fR, \fIConditionPathIsSymbolicLink=\fR, \fIConditionPathIsMountPoint=\fR, \fIConditionPathIsReadWrite=\fR, \fIConditionDirectoryNotEmpty=\fR, \fIConditionFileNotEmpty=\fR, \fIConditionFileIsExecutable=\fR, \fIConditionNull=\fR
.RS 4
Before starting a unit verify that the specified condition is true\&. If it is not true, the starting of the unit will be skipped, however all ordering dependencies of it are still respected\&. A failing condition will not result in the unit being moved into a failure state\&. The condition is checked at the time the queued start job is to be executed\&.
.sp
\fIConditionArchitecture=\fR
may be used to check whether the system is running on a specific architecture\&. Takes one of
\fIx86\fR,
\fIx86\-64\fR,
\fIppc\fR,
\fIppc64\fR,
\fIia64\fR,
\fIparisc\fR,
\fIparisc64\fR,
\fIs390\fR,
\fIs390x\fR,
\fIsparc\fR,
\fIsparc64\fR,
\fImips\fR,
\fImips64\fR,
\fIalpha\fR,
\fIarm\fR,
\fIarm\-be\fR,
\fIarm64\fR,
\fIarm64\-be\fR,
\fIsh\fR,
\fIsh64\fR,
\fIm86k\fR
to test against a specific architecture\&. The architecture is determined from the information returned by
\fBuname\fR(2)
and is thus subject to
\fBpersonality\fR(2)\&. Note that a
\fIPersonality=\fR
setting in the same unit file has no effect on this condition\&. A special architecture name
\fInative\fR
is mapped to the architecture the system manager itself is compiled for\&. The test may be negated by prepending an exclamation mark\&.
.sp
\fIConditionVirtualization=\fR
may be used to check whether the system is executed in a virtualized environment and optionally test whether it is a specific implementation\&. Takes either boolean value to check if being executed in any virtualized environment, or one of
\fIvm\fR
and
\fIcontainer\fR
to test against a generic type of virtualization solution, or one of
\fIqemu\fR,
\fIkvm\fR,
\fIvmware\fR,
\fImicrosoft\fR,
\fIoracle\fR,
\fIxen\fR,
\fIbochs\fR,
\fIchroot\fR,
\fIuml\fR,
\fIopenvz\fR,
\fIlxc\fR,
\fIlxc\-libvirt\fR,
\fIsystemd\-nspawn\fR
to test against a specific implementation\&. If multiple virtualization technologies are nested, only the innermost is considered\&. The test may be negated by prepending an exclamation mark\&.
.sp
\fIConditionHost=\fR
may be used to match against the hostname or machine ID of the host\&. This either takes a hostname string (optionally with shell style globs) which is tested against the locally set hostname as returned by
\fBgethostname\fR(2), or a machine ID formatted as string (see
\fBmachine-id\fR(5))\&. The test may be negated by prepending an exclamation mark\&.
.sp
\fIConditionKernelCommandLine=\fR
may be used to check whether a specific kernel command line option is set (or if prefixed with the exclamation mark unset)\&. The argument must either be a single word, or an assignment (i\&.e\&. two words, separated
"=")\&. In the former case the kernel command line is searched for the word appearing as is, or as left hand side of an assignment\&. In the latter case, the exact assignment is looked for with right and left hand side matching\&.
.sp
\fIConditionSecurity=\fR
may be used to check whether the given security module is enabled on the system\&. Currently the recognized values values are
\fIselinux\fR,
\fIapparmor\fR,
\fIima\fR
and
\fIsmack\fR\&. The test may be negated by prepending an exclamation mark\&.
.sp
\fIConditionCapability=\fR
may be used to check whether the given capability exists in the capability bounding set of the service manager (i\&.e\&. this does not check whether capability is actually available in the permitted or effective sets, see
\fBcapabilities\fR(7)
for details)\&. Pass a capability name such as
"CAP_MKNOD", possibly prefixed with an exclamation mark to negate the check\&.
.sp
\fIConditionACPower=\fR
may be used to check whether the system has AC power, or is exclusively battery powered at the time of activation of the unit\&. This takes a boolean argument\&. If set to
\fItrue\fR, the condition will hold only if at least one AC connector of the system is connected to a power source, or if no AC connectors are known\&. Conversely, if set to
\fIfalse\fR, the condition will hold only if there is at least one AC connector known and all AC connectors are disconnected from a power source\&.
.sp
\fIConditionNeedsUpdate=\fR
takes one of
/var
or
/etc
as argument, possibly prefixed with a
"!"
(for inverting the condition)\&. This condition may be used to conditionalize units on whether the specified directory requires an update because
/usr\*(Aqs modification time is newer than the stamp file
\&.updated
in the specified directory\&. This is useful to implement offline updates of the vendor operating system resources in
/usr
that require updating of
/etc
or
/var
on the next following boot\&. Units making use of this condition should order themselves before
\fBsystemd-update-done.service\fR(8), to make sure they run before the stamp files\*(Aqs modification time gets reset indicating a completed update\&.
.sp
With
\fIConditionPathExists=\fR
a file existence condition is checked before a unit is started\&. If the specified absolute path name does not exist, the condition will fail\&. If the absolute path name passed to
\fIConditionPathExists=\fR
is prefixed with an exclamation mark ("!"), the test is negated, and the unit is only started if the path does not exist\&.
.sp
\fIConditionPathExistsGlob=\fR
is similar to
\fIConditionPathExists=\fR, but checks for the existence of at least one file or directory matching the specified globbing pattern\&.
.sp
\fIConditionPathIsDirectory=\fR
is similar to
\fIConditionPathExists=\fR
but verifies whether a certain path exists and is a directory\&.
.sp
\fIConditionPathIsSymbolicLink=\fR
is similar to
\fIConditionPathExists=\fR
but verifies whether a certain path exists and is a symbolic link\&.
.sp
\fIConditionPathIsMountPoint=\fR
is similar to
\fIConditionPathExists=\fR
but verifies whether a certain path exists and is a mount point\&.
.sp
\fIConditionPathIsReadWrite=\fR
is similar to
\fIConditionPathExists=\fR
but verifies whether the underlying file system is readable and writable (i\&.e\&. not mounted read\-only)\&.
.sp
\fIConditionDirectoryNotEmpty=\fR
is similar to
\fIConditionPathExists=\fR
but verifies whether a certain path exists and is a non\-empty directory\&.
.sp
\fIConditionFileNotEmpty=\fR
is similar to
\fIConditionPathExists=\fR
but verifies whether a certain path exists and refers to a regular file with a non\-zero size\&.
.sp
\fIConditionFileIsExecutable=\fR
is similar to
\fIConditionPathExists=\fR
but verifies whether a certain path exists, is a regular file and marked executable\&.
.sp
Finally,
\fIConditionNull=\fR
may be used to add a constant condition check value to the unit\&. It takes a boolean argument\&. If set to
\fIfalse\fR, the condition will always fail, otherwise succeed\&.
.sp
If multiple conditions are specified, the unit will be executed if all of them apply (i\&.e\&. a logical AND is applied)\&. Condition checks can be prefixed with a pipe symbol (|) in which case a condition becomes a triggering condition\&. If at least one triggering condition is defined for a unit, then the unit will be executed if at least one of the triggering conditions apply and all of the non\-triggering conditions\&. If you prefix an argument with the pipe symbol and an exclamation mark, the pipe symbol must be passed first, the exclamation second\&. Except for
\fIConditionPathIsSymbolicLink=\fR, all path checks follow symlinks\&. If any of these options is assigned the empty string, the list of conditions is reset completely, all previous condition settings (of any kind) will have no effect\&.
.RE
.PP
\fISourcePath=\fR
.RS 4
A path to a configuration file this unit has been generated from\&. This is primarily useful for implementation of generator tools that convert configuration from an external configuration file format into native unit files\&. This functionality should not be used in normal units\&.
.RE
.SH "[INSTALL] SECTION OPTIONS"
.PP
Unit file may include a [Install] section, which carries installation information for the unit\&. This section is not interpreted by
\fBsystemd\fR(1)
during runtime\&. It is used exclusively by the
\fBenable\fR
and
\fBdisable\fR
commands of the
\fBsystemctl\fR(1)
tool during installation of a unit:
.PP
\fIAlias=\fR
.RS 4
A space\-seperated list of additional names this unit shall be installed under\&. The names listed here must have the same suffix (i\&.e\&. type) as the unit file name\&. This option may be specified more than once, in which case all listed names are used\&. At installation time,
\fBsystemctl enable\fR
will create symlinks from these names to the unit filename\&.
.RE
.PP
\fIWantedBy=\fR, \fIRequiredBy=\fR
.RS 4
This option may be used more than once, or a space\-separated list of unit names may be given\&. A symbolic link is created in the
\&.wants/
or
\&.requires/
directory of each of the listed units when this unit is installed by
\fBsystemctl enable\fR\&. This has the effect that a dependency of type
\fIWants=\fR
or
\fIRequires=\fR
is added from the listed unit to the current unit\&. The primary result is that the current unit will be started when the listed unit is started\&. See the description of
\fIWants=\fR
and
\fIRequires=\fR
in the [Unit] section for details\&.
.sp
\fBWantedBy=foo\&.service\fR
in a service
bar\&.service
is mostly equivalent to
\fBAlias=foo\&.service\&.wants/bar\&.service\fR
in the same file\&. In case of template units,
\fBsystemctl enable\fR
must be called with an instance name, and this instance will be added to the
\&.wants/
or
\&.requires/
list of the listed unit\&. E\&.g\&.
\fBWantedBy=getty\&.target\fR
in a service
getty@\&.service
will result in
\fBsystemctl enable getty@tty2\&.service\fR
creating a
getty\&.target\&.wants/getty@tty2\&.service
link to
getty@\&.service\&.
.RE
.PP
\fIAlso=\fR
.RS 4
Additional units to install/deinstall when this unit is installed/deinstalled\&. If the user requests installation/deinstallation of a unit with this option configured,
\fBsystemctl enable\fR
and
\fBsystemctl disable\fR
will automatically install/uninstall units listed in this option as well\&.
.sp
This option may be used more than once, or a space\-separated list of unit names may be given\&.
.RE
.PP
\fIDefaultInstance=\fR
.RS 4
In template unit files, this specifies for which instance the unit shall be enabled if the template is enabled without any explicitly set instance\&. This option has no effect in non\-template unit files\&. The specified string must be usable as instance identifier\&.
.RE
.PP
The following specifiers are interpreted in the Install section: %n, %N, %p, %i, %U, %u, %m, %H, %b, %v\&. For their meaning see the next section\&.
.SH "SPECIFIERS"
.PP
Many settings resolve specifiers which may be used to write generic unit files referring to runtime or unit parameters that are replaced when the unit files are loaded\&. The following specifiers are understood:
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&3.\ \&Specifiers available in unit files
.TS
allbox tab(:);
lB lB lB.
T{
Specifier
T}:T{
Meaning
T}:T{
Details
T}
.T&
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l
l l l.
T{
"%n"
T}:T{
Full unit name
T}:T{
\ \&
T}
T{
"%N"
T}:T{
Unescaped full unit name
T}:T{
Same as "%n", but with escaping undone
T}
T{
"%p"
T}:T{
Prefix name
T}:T{
For instantiated units, this refers to the string before the "@" character of the unit name\&. For non\-instantiated units, this refers to the name of the unit with the type suffix removed\&.
T}
T{
"%P"
T}:T{
Unescaped prefix name
T}:T{
Same as "%p", but with escaping undone
T}
T{
"%i"
T}:T{
Instance name
T}:T{
For instantiated units: this is the string between the "@" character and the suffix of the unit name\&.
T}
T{
"%I"
T}:T{
Unescaped instance name
T}:T{
Same as "%i", but with escaping undone
T}
T{
"%f"
T}:T{
Unescaped filename
T}:T{
This is either the unescaped instance name (if applicable) with / prepended (if applicable), or the prefix name prepended with /\&.
T}
T{
"%c"
T}:T{
Control group path of the unit
T}:T{
This path does not include the /sys/fs/cgroup/systemd/ prefix\&.
T}
T{
"%r"
T}:T{
Control group path of the slice the unit is placed in
T}:T{
This usually maps to the parent cgroup path of "%c"\&.
T}
T{
"%R"
T}:T{
Root control group path below which slices and units are placed
T}:T{
For system instances, this resolves to /, except in containers, where this maps to the container\*(Aqs root control group path\&.
T}
T{
"%t"
T}:T{
Runtime directory
T}:T{
This is either /run (for the system manager) or the path "$XDG_RUNTIME_DIR" resolves to (for user managers)\&.
T}
T{
"%u"
T}:T{
User name
T}:T{
This is the name of the configured user of the unit, or (if none is set) the user running the systemd instance\&.
T}
T{
"%U"
T}:T{
User UID
T}:T{
This is the numeric UID of the configured user of the unit, or (if none is set) the user running the systemd user instance\&. Note that this specifier is not available for units run by the systemd system instance (as opposed to those run by a systemd user instance), unless the user has been configured as a numeric UID in the first place or the configured user is the root user\&.
T}
T{
"%h"
T}:T{
User home directory
T}:T{
This is the home directory of the configured user of the unit, or (if none is set) the user running the systemd user instance\&. Similar to "%U", this specifier is not available for units run by the systemd system instance, unless the configured user is the root user\&.
T}
T{
"%s"
T}:T{
User shell
T}:T{
This is the shell of the configured user of the unit, or (if none is set) the user running the systemd user instance\&. Similar to "%U", this specifier is not available for units run by the systemd system instance, unless the configured user is the root user\&.
T}
T{
"%m"
T}:T{
Machine ID
T}:T{
The machine ID of the running system, formatted as string\&. See \fBmachine-id\fR(5) for more information\&.
T}
T{
"%b"
T}:T{
Boot ID
T}:T{
The boot ID of the running system, formatted as string\&. See \fBrandom\fR(4) for more information\&.
T}
T{
"%H"
T}:T{
Host name
T}:T{
The hostname of the running system at the point in time the unit configuation is loaded\&.
T}
T{
"%v"
T}:T{
Kernel release
T}:T{
Identical to \fBuname \-r\fR output
T}
T{
"%%"
T}:T{
Single percent sign
T}:T{
Use "%%" in place of "%" to specify a single percent sign\&.
T}
.TE
.sp 1
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(8),
\fBsystemd.special\fR(7),
\fBsystemd.service\fR(5),
\fBsystemd.socket\fR(5),
\fBsystemd.device\fR(5),
\fBsystemd.mount\fR(5),
\fBsystemd.automount\fR(5),
\fBsystemd.swap\fR(5),
\fBsystemd.target\fR(5),
\fBsystemd.path\fR(5),
\fBsystemd.timer\fR(5),
\fBsystemd.snapshot\fR(5),
\fBsystemd.scope\fR(5),
\fBsystemd.slice\fR(5),
\fBsystemd.time\fR(7),
\fBcapabilities\fR(7),
\fBsystemd.directives\fR(7),
\fBuname\fR(1)
.SH "NOTES"
.IP " 1." 4
XDG Desktop Entry Specification
.RS 4
\%http://standards.freedesktop.org/desktop-entry-spec/latest/
.RE
.IP " 2." 4
Interface Stability Promise
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/InterfaceStabilityPromise
.RE
.IP " 3." 4
Generators
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/Generators/
.RE
