'\" t
.TH "SYSTEMD\-CAT" "1" "" "systemd 220" "systemd-cat"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-cat \- Connect a pipeline or program\*(Aqs output with the journal
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-cat\ \fR\fB[OPTIONS...]\fR\fB\ \fR\fB[COMMAND]\fR\fB\ \fR\fB[ARGUMENTS...]\fR\ 'u
\fBsystemd\-cat \fR\fB[OPTIONS...]\fR\fB \fR\fB[COMMAND]\fR\fB \fR\fB[ARGUMENTS...]\fR
.HP \w'\fBsystemd\-cat\ \fR\fB[OPTIONS...]\fR\ 'u
\fBsystemd\-cat \fR\fB[OPTIONS...]\fR
.SH "DESCRIPTION"
.PP
\fBsystemd\-cat\fR
may be used to connect the standard input and output of a process to the journal, or as a filter tool in a shell pipeline to pass the output the previous pipeline element generates to the journal\&.
.PP
If no parameter is passed,
\fBsystemd\-cat\fR
will write everything it reads from standard input (stdin) to the journal\&.
.PP
If parameters are passed, they are executed as command line with standard output (stdout) and standard error output (stderr) connected to the journal, so that all it writes is stored in the journal\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.PP
\fB\-t\fR, \fB\-\-identifier=\fR
.RS 4
Specify a short string that is used to identify the logging tool\&. If not specified, no identification string is written to the journal\&.
.RE
.PP
\fB\-p\fR, \fB\-\-priority=\fR
.RS 4
Specify the default priority level for the logged messages\&. Pass one of
"emerg",
"alert",
"crit",
"err",
"warning",
"notice",
"info",
"debug", or a value between 0 and 7 (corresponding to the same named levels)\&. These priority values are the same as defined by
\fBsyslog\fR(3)\&. Defaults to
"info"\&. Note that this simply controls the default, individual lines may be logged with different levels if they are prefixed accordingly\&. For details see
\fB\-\-level\-prefix=\fR
below\&.
.RE
.PP
\fB\-\-level\-prefix=\fR
.RS 4
Controls whether lines read are parsed for syslog priority level prefixes\&. If enabled (the default), a line prefixed with a priority prefix such as
"<5>"
is logged at priority 5 ("notice"), and similar for the other priority levels\&. Takes a boolean argument\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&Invoke a program\fR
.PP
This calls
/bin/ls
with standard output and error connected to the journal:
.sp
.if n \{\
.RS 4
.\}
.nf
# systemd\-cat ls
.fi
.if n \{\
.RE
.\}
.PP
\fBExample\ \&2.\ \&Usage in a shell pipeline\fR
.PP
This builds a shell pipeline also invoking
/bin/ls
and writes the output it generates to the journal:
.sp
.if n \{\
.RS 4
.\}
.nf
# ls | systemd\-cat
.fi
.if n \{\
.RE
.\}
.PP
Even though the two examples have very similar effects the first is preferable since only one process is running at a time, and both stdout and stderr are captured while in the second example, only stdout is captured\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBlogger\fR(1)
