'\" t
.TH "SYSTEMD\-LOCALED\&.SERVICE" "8" "" "systemd 221" "systemd-localed.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-localed.service, systemd-localed \- Locale bus mechanism
.SH "SYNOPSIS"
.PP
systemd\-localed\&.service
.PP
/usr/lib/systemd/systemd\-localed
.SH "DESCRIPTION"
.PP
systemd\-localed
is a system service that may be used as mechanism to change the system locale settings, as well as the console key mapping and default X11 key mapping\&.
systemd\-localed
is automatically activated on request and terminates itself when it is unused\&.
.PP
The tool
\fBlocalectl\fR(1)
is a command line client to this service\&.
.PP
See the
\m[blue]\fBdeveloper documentation\fR\m[]\&\s-2\u[1]\d\s+2
for information about the APIs
systemd\-localed
provides\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBlocale.conf\fR(5),
\fBvconsole.conf\fR(5),
\fBlocalectl\fR(1),
\fBloadkeys\fR(1)
.SH "NOTES"
.IP " 1." 4
developer documentation
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/localed
.RE
