'\" t
.TH "SYSTEMD\-GPT\-AUTO\-GENERATOR" "8" "" "systemd 221" "systemd-gpt-auto-generator"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-gpt-auto-generator \- Generator for automatically discovering and mounting root, /home and /srv partitions, as well as discovering and enabling swap partitions, based on GPT partition type GUIDs\&.
.SH "SYNOPSIS"
.PP
/usr/lib/systemd/system\-generators/systemd\-gpt\-auto\-generator
.SH "DESCRIPTION"
.PP
systemd\-gpt\-auto\-generator
is a unit generator that automatically discovers root,
/home,
/srv
and swap partitions and creates mount and swap units for them, based on the partition type GUIDs of GUID partition tables (GPT)\&. It implements the
\m[blue]\fBDiscoverable Partitions Specification\fR\m[]\&\s-2\u[1]\d\s+2\&. Note that this generator has no effect on non\-GPT systems, or where the directories under the mount points are already non\-empty\&. Also, on systems where the units are explicitly configured (for example, listed in
\fBfstab\fR(5)), the units this generator creates are overriden, but additional automatic dependencies might be created\&.
.PP
This generator will only look for root partitions on the same physical disk the EFI System Partition (ESP) is located on\&. It will only look for the other partitions on the same physical disk the root file system is located on\&. These partitions will not be searched on systems where the root file system is distributed on multiple disks, for example via btrfs RAID\&.
.PP
systemd\-gpt\-auto\-generator
is useful for centralizing file system configuration in the partition table and making manual configuration in
/etc/fstab
or suchlike unnecessary\&.
.PP
This generator looks for the partitions based on their partition type GUID\&. The following partition type GUIDs are identified:
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \&Partition Type GUIDs
.TS
allbox tab(:);
lB lB lB.
T{
Partition Type GUID
T}:T{
Name
T}:T{
Explanation
T}
.T&
l l l
l l l
l l l
l l l
l l l
l l l
l l l.
T{
44479540\-f297\-41b2\-9af7\-d131d5f0458a
T}:T{
Root Partition (x86)
T}:T{
On 32\-bit x86 systems, the first x86 root partition on the disk the EFI ESP is located on is mounted to the root directory /\&.
T}
T{
4f68bce3\-e8cd\-4db1\-96e7\-fbcaf984b709
T}:T{
Root Partition (x86\-64)
T}:T{
On 64\-bit x86 systems, the first x86\-64 root partition on the disk the EFI ESP is located on is mounted to the root directory /\&.
T}
T{
69dad710\-2ce4\-4e3c\-b16c\-21a1d49abed3
T}:T{
Root Partition (32\-bit ARM)
T}:T{
On 32\-bit ARM systems, the first ARM root partition on the disk the EFI ESP is located on is mounted to the root directory /\&.
T}
T{
b921b045\-1df0\-41c3\-af44\-4c6f280d3fae
T}:T{
Root Partition (64\-bit ARM)
T}:T{
On 64\-bit ARM systems, the first ARM root partition on the disk the EFI ESP is located on is mounted to the root directory /\&.
T}
T{
933ac7e1\-2eb4\-4f13\-b844\-0e14e2aef915
T}:T{
Home Partition
T}:T{
The first home partition on the disk the root partition is located on is mounted to /home\&.
T}
T{
3b8f8425\-20e0\-4f3b\-907f\-1a25a76f98e8
T}:T{
Server Data Partition
T}:T{
The first server data partition on the disk the root partition is located on is mounted to /srv\&.
T}
T{
0657fd6d\-a4ab\-43c4\-84e5\-0933c84b4f4f
T}:T{
Swap
T}:T{
All swap partitions located on the disk the root partition is located on are enabled\&.
T}
.TE
.sp 1
.PP
The
/home
and
/srv
partitions may be encrypted in LUKS format\&. In this case a device mapper device is set up under the names
/dev/mapper/home
and
/dev/mapper/srv\&. Note that this might create conflicts if the same partition is listed in
/etc/crypttab
with a different device mapper device name\&.
.PP
Also note that
\fBsystemd-efi-boot-generator\fR(8)
will mount the EFI System Partition (ESP) to
/boot
if not otherwise mounted\&.
.PP
When using this generator in conjunction with btrfs file systems, make sure to set the correct default subvolumes on them, using
\fBbtrfs subvolume set\-default\fR\&.
.PP
systemd\-gpt\-auto\-generator
implements
\fBsystemd.generator\fR(7)\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd.mount\fR(5),
\fBsystemd.swap\fR(5),
\fBsystemd-fstab-generator\fR(8),
\fBsystemd-efi-boot-generator\fR(8),
\fBsystemd-cryptsetup@.service\fR(8),
\fBcryptsetup\fR(8),
\fBfstab\fR(5),
\fBbtrfs\fR(8)
.SH "NOTES"
.IP " 1." 4
Discoverable Partitions Specification
.RS 4
\%http://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/
.RE
