'\" t
.TH "SYSTEMD\-CRYPTSETUP\-GENERATOR" "8" "" "systemd 220" "systemd-cryptsetup-generator"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-cryptsetup-generator \- Unit generator for /etc/crypttab
.SH "SYNOPSIS"
.PP
/usr/lib/systemd/system\-generators/systemd\-cryptsetup\-generator
.SH "DESCRIPTION"
.PP
systemd\-cryptsetup\-generator
is a generator that translates
/etc/crypttab
into native systemd units early at boot and when configuration of the system manager is reloaded\&. This will create
\fBsystemd-cryptsetup@.service\fR(8)
units as necessary\&.
.PP
systemd\-cryptsetup\-generator
implements
\fBsystemd.generator\fR(7)\&.
.SH "KERNEL COMMAND LINE"
.PP
systemd\-cryptsetup\-generator
understands the following kernel command line parameters:
.PP
\fIluks=\fR, \fIrd\&.luks=\fR
.RS 4
Takes a boolean argument\&. Defaults to
"yes"\&. If
"no", disables the generator entirely\&.
\fIrd\&.luks=\fR
is honored only by initial RAM disk (initrd) while
\fIluks=\fR
is honored by both the main system and the initrd\&.
.RE
.PP
\fIluks\&.crypttab=\fR, \fIrd\&.luks\&.crypttab=\fR
.RS 4
Takes a boolean argument\&. Defaults to
"yes"\&. If
"no", causes the generator to ignore any devices configured in
/etc/crypttab
(\fIluks\&.uuid=\fR
will still work however)\&.
\fIrd\&.luks\&.crypttab=\fR
is honored only by initial RAM disk (initrd) while
\fIluks\&.crypttab=\fR
is honored by both the main system and the initrd\&.
.RE
.PP
\fIluks\&.uuid=\fR, \fIrd\&.luks\&.uuid=\fR
.RS 4
Takes a LUKS superblock UUID as argument\&. This will activate the specified device as part of the boot process as if it was listed in
/etc/crypttab\&. This option may be specified more than once in order to set up multiple devices\&.
\fIrd\&.luks\&.uuid=\fR
is honored only by initial RAM disk (initrd) while
\fIluks\&.uuid=\fR
is honored by both the main system and the initrd\&.
.sp
If /etc/crypttab contains entries with the same UUID, then the name, keyfile and options specified there will be used\&. Otherwise the device will have the name
"luks\-UUID"\&.
.sp
If /etc/crypttab exists, only those UUIDs specified on the kernel command line will be activated in the initrd or the real root\&.
.RE
.PP
\fIluks\&.name=\fR, \fIrd\&.luks\&.name=\fR
.RS 4
Takes a LUKS super block UUID followed by an
"="
and a name\&. This implies
\fIrd\&.luks\&.uuid=\fR
or
\fIluks\&.uuid=\fR
and will additionally make the LUKS device given by the UUID appear under the provided name\&.
.sp
\fIrd\&.luks\&.name=\fR
is honored only by initial RAM disk (initrd) while
\fIluks\&.name=\fR
is honored by both the main system and the initrd\&.
.RE
.PP
\fIluks\&.options=\fR, \fIrd\&.luks\&.options=\fR
.RS 4
Takes a LUKS super block UUID followed by an
"="
and a string of options separated by commas as argument\&. This will override the options for the given UUID\&.
.sp
If only a list of options, without an UUID, is specified, they apply to any UUIDs not specified elsewhere, and without an entry in
/etc/crypttab\&.
.sp
\fIrd\&.luks\&.options=\fR
is honored only by initial RAM disk (initrd) while
\fIluks\&.options=\fR
is honored by both the main system and the initrd\&.
.RE
.PP
\fIluks\&.key=\fR, \fIrd\&.luks\&.key=\fR
.RS 4
Takes a password file name as argument or a LUKS super block UUID followed by a
"="
and a password file name\&.
.sp
For those entries specified with
\fIrd\&.luks\&.uuid=\fR
or
\fIluks\&.uuid=\fR, the password file will be set to the one specified by
\fIrd\&.luks\&.key=\fR
or
\fIluks\&.key=\fR
of the corresponding UUID, or the password file that was specified without a UUID\&.
.sp
\fIrd\&.luks\&.key=\fR
is honored only by initial RAM disk (initrd) while
\fIluks\&.key=\fR
is honored by both the main system and the initrd\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBcrypttab\fR(5),
\fBsystemd-cryptsetup@.service\fR(8),
\fBcryptsetup\fR(8),
\fBsystemd-fstab-generator\fR(8)
