'\" t
.TH "SYSTEMD\-ASK\-PASSWORD\-CONSOLE\&.SERVICE" "8" "" "systemd 220" "systemd-ask-password-console.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-ask-password-console.service, systemd-ask-password-console.path, systemd-ask-password-wall.service, systemd-ask-password-wall.path \- Query the user for system passwords on the console and via wall
.SH "SYNOPSIS"
.PP
systemd\-ask\-password\-console\&.service
.PP
systemd\-ask\-password\-console\&.path
.PP
systemd\-ask\-password\-wall\&.service
.PP
systemd\-ask\-password\-wall\&.path
.SH "DESCRIPTION"
.PP
systemd\-ask\-password\-console\&.service
is a system service that queries the user for system passwords (such as hard disk encryption keys and SSL certificate passphrases) on the console\&. It is intended to be used during boot to ensure proper handling of passwords necessary for boot\&.
systemd\-ask\-password\-wall\&.service
is a system service that informs all logged in users for system passwords via
\fBwall\fR(1)\&. It is intended to be used after boot to ensure that users are properly notified\&.
.PP
See the
\m[blue]\fBdeveloper documentation\fR\m[]\&\s-2\u[1]\d\s+2
for more information about the system password logic\&.
.PP
Note that these services invoke
\fBsystemd-tty-ask-password-agent\fR(1)
with either the
\fB\-\-watch \-\-console\fR
or
\fB\-\-watch \-\-wall\fR
command line parameters\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-tty-ask-password-agent\fR(1),
\fBwall\fR(1)
.SH "NOTES"
.IP " 1." 4
developer documentation
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/PasswordAgents
.RE
