'\" t
.TH "SYSTEMD\-MACHINED\&.SERVICE" "8" "" "systemd 215" "systemd-machined.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-machined.service, systemd-machined \- Virtual machine and container registration manager
.SH "SYNOPSIS"
.PP
systemd\-machined\&.service
.PP
/usr/lib/systemd/systemd\-machined
.SH "DESCRIPTION"
.PP
\fBsystemd\-machined\fR
is a system service that keeps track of virtual machines and containers, and processes belonging to them\&.
.PP
See
\fBsystemd-nspawn\fR(1)
for some examples on how to start a container the systemd way\&.
.PP
See the
\m[blue]\fBmachined D\-Bus API Documentation\fR\m[]\&\s-2\u[1]\d\s+2
for information about the APIs
systemd\-machined
provides\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBmachinectl\fR(1),
\fBsystemd.special\fR(7)\&.
.SH "NOTES"
.IP " 1." 4
machined D-Bus API Documentation
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/machined
.RE
