'\" t
.TH "SYSTEMD\-MACHINE\-ID\-COMMIT" "1" "" "systemd 221" "systemd-machine-id-commit"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-machine-id-commit \- Commit transient machine ID to /etc/machine\-id
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-machine\-id\-commit\fR\ 'u
\fBsystemd\-machine\-id\-commit\fR
.SH "DESCRIPTION"
.PP
\fBsystemd\-machine\-id\-commit\fR
may be used to write on disk any transient machine ID mounted as a temporary file system in
/etc/machine\-id
at boot time\&. See
\fBmachine-id\fR(5)
for more information about this file\&.
.PP
This tool will execute no operation if
/etc/machine\-id
doesn\*(Aqt contain any valid machine ID, isn\*(Aqt mounted as an independent temporary file system, of
/etc
is read\-only\&. If those conditions are met, it will then write current machine ID to disk and unmount the transient
/etc/machine\-id
file in a race\-free manner to ensure that this file is always valid for other processes\&.
.PP
Note that the traditional way to initialize the machine ID in
/etc/machine\-id
is to use
\fBsystemd\-machine\-id\-setup\fR
by system installer tools\&. You can also use
\fBsystemd-firstboot\fR(1)
to initialize the machine ID on mounted (but not booted) system images\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-root=\fR\fB\fIroot\fR\fR
.RS 4
Takes a directory path as an argument\&. All paths will be prefixed with the given alternate
\fIroot\fR
path, including config search paths\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-machine-id-commit.service\fR(8),
\fBsystemd-machine-id-setup\fR(1),
\fBmachine-id\fR(5),
\fBsystemd-firstboot\fR(1)
