'\" t
.TH "SYSTEMD\-INHIBIT" "1" "" "systemd 221" "systemd-inhibit"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-inhibit \- Execute a program with an inhibition lock taken
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-inhibit\ \fR\fB[OPTIONS...]\fR\fB\ \fR\fB[COMMAND]\fR\fB\ \fR\fB[ARGUMENTS...]\fR\ 'u
\fBsystemd\-inhibit \fR\fB[OPTIONS...]\fR\fB \fR\fB[COMMAND]\fR\fB \fR\fB[ARGUMENTS...]\fR
.HP \w'\fBsystemd\-inhibit\ \fR\fB[OPTIONS...]\fR\fB\ \-\-list\fR\ 'u
\fBsystemd\-inhibit \fR\fB[OPTIONS...]\fR\fB \-\-list\fR
.SH "DESCRIPTION"
.PP
\fBsystemd\-inhibit\fR
may be used to execute a program with a shutdown, sleep or idle inhibitor lock taken\&. The lock will be acquired before the specified command line is executed and released afterwards\&.
.PP
Inhibitor locks may be used to block or delay system sleep and shutdown requests from the user, as well as automatic idle handling of the OS\&. This is useful to avoid system suspends while an optical disc is being recorded, or similar operations that should not be interrupted\&.
.PP
For more information see the
\m[blue]\fBInhibitor Lock Developer Documentation\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-what=\fR
.RS 4
Takes a colon\-separated list of one or more operations to inhibit:
"shutdown",
"sleep",
"idle",
"handle\-power\-key",
"handle\-suspend\-key",
"handle\-hibernate\-key",
"handle\-lid\-switch", for inhibiting reboot/power\-off/halt/kexec, suspending/hibernating, the automatic idle detection, or the low\-level handling of the power/sleep key and the lid switch, respectively\&. If omitted, defaults to
"idle:sleep:shutdown"\&.
.RE
.PP
\fB\-\-who=\fR
.RS 4
Takes a short, human\-readable descriptive string for the program taking the lock\&. If not passed, defaults to the command line string\&.
.RE
.PP
\fB\-\-why=\fR
.RS 4
Takes a short, human\-readable descriptive string for the reason for taking the lock\&. Defaults to "Unknown reason"\&.
.RE
.PP
\fB\-\-mode=\fR
.RS 4
Takes either
"block"
or
"delay"
and describes how the lock is applied\&. If
"block"
is used (the default), the lock prohibits any of the requested operations without time limit, and only privileged users may override it\&. If
"delay"
is used, the lock can only delay the requested operations for a limited time\&. If the time elapses, the lock is ignored and the operation executed\&. The time limit may be specified in
\fBlogind.conf\fR(5)\&. Note that
"delay"
is only available for
"sleep"
and
"shutdown"\&.
.RE
.PP
\fB\-\-list\fR
.RS 4
Lists all active inhibition locks instead of acquiring one\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "EXIT STATUS"
.PP
Returns the exit status of the executed program\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
# systemd\-inhibit wodim foobar\&.iso
.fi
.if n \{\
.RE
.\}
.PP
This burns the ISO image
foobar\&.iso
on a CD using
\fBwodim\fR(1), and inhibits system sleeping, shutdown and idle while doing so\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBlogind.conf\fR(5)
.SH "NOTES"
.IP " 1." 4
Inhibitor Lock Developer Documentation
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/inhibit
.RE
