'\" t
.TH "SYSTEMD\&.MOUNT" "5" "" "systemd 221" "systemd.mount"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.mount \- Mount unit configuration
.SH "SYNOPSIS"
.PP
\fImount\fR\&.mount
.SH "DESCRIPTION"
.PP
A unit configuration file whose name ends in
"\&.mount"
encodes information about a file system mount point controlled and supervised by systemd\&.
.PP
This man page lists the configuration options specific to this unit type\&. See
\fBsystemd.unit\fR(5)
for the common options of all unit configuration files\&. The common configuration items are configured in the generic [Unit] and [Install] sections\&. The mount specific configuration options are configured in the [Mount] section\&.
.PP
Additional options are listed in
\fBsystemd.exec\fR(5), which define the execution environment the
\fBmount\fR(8)
binary is executed in, and in
\fBsystemd.kill\fR(5), which define the way the processes are terminated, and in
\fBsystemd.resource-control\fR(5), which configure resource control settings for the processes of the service\&. Note that the User= and Group= options are not particularly useful for mount units specifying a
"Type="
option or using configuration not specified in
/etc/fstab;
\fBmount\fR(8)
will refuse options that are not listed in
/etc/fstab
if it is not run as UID 0\&.
.PP
Mount units must be named after the mount point directories they control\&. Example: the mount point
/home/lennart
must be configured in a unit file
home\-lennart\&.mount\&. For details about the escaping logic used to convert a file system path to a unit name, see
\fBsystemd.unit\fR(5)\&.
.PP
Optionally, a mount unit may be accompanied by an automount unit, to allow on\-demand or parallelized mounting\&. See
\fBsystemd.automount\fR(5)\&.
.PP
If a mount point is beneath another mount point in the file system hierarchy, a dependency between both units is created automatically\&.
.PP
Mount points created at runtime (independently of unit files or
/etc/fstab) will be monitored by systemd and appear like any other mount unit in systemd\&. See
/proc/self/mountinfo
description in
\fBproc\fR(5)\&.
.PP
Some file systems have special semantics as API file systems for kernel\-to\-userspace and userspace\-to\-userspace interfaces\&. Some of them may not be changed via mount units, and cannot be disabled\&. For a longer discussion see
\m[blue]\fBAPI File Systems\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "FSTAB"
.PP
Mount units may either be configured via unit files, or via
/etc/fstab
(see
\fBfstab\fR(5)
for details)\&. Mounts listed in
/etc/fstab
will be converted into native units dynamically at boot and when the configuration of the system manager is reloaded\&. In general, configuring mount points through
/etc/fstab
is the preferred approach\&. See
\fBsystemd-fstab-generator\fR(8)
for details about the conversion\&.
.PP
When reading
/etc/fstab
a few special mount options are understood by systemd which influence how dependencies are created for mount points\&. systemd will create a dependency of type
\fBWants\fR
or
\fBRequires\fR
(see option
\fBnofail\fR
below), from either
local\-fs\&.target
or
remote\-fs\&.target, depending whether the file system is local or remote\&.
.PP
\fBx\-systemd\&.requires=\fR
.RS 4
Configures a
\fIRequires=\fR
and an
\fIAfter=\fR
dependency between the created mount unit and another systemd unit, such as a device or mount unit\&. The argument should be a unit name, or an absolute path to a device node or mount point\&. This option may be specified more than once\&. This option is particularly useful for mount point declarations that need an additional device to be around (such as an external journal device for journal file systems) or an additional mount to be in place (such as an overlay file system that merges multiple mount points)\&. See
\fIAfter=\fR
and
\fIRequires=\fR
in
\fBsystemd.unit\fR(5)
for details\&.
.RE
.PP
\fBx\-systemd\&.requires\-mounts\-for=\fR
.RS 4
Configures a
\fIRequiresMountsFor=\fR
dependency between the created mount unit and other mount units\&. The argument must be an absolute path\&. This option may be specified more than once\&. See
\fIRequiresMountsFor=\fR
in
\fBsystemd.unit\fR(5)
for details\&.
.RE
.PP
\fBx\-systemd\&.automount\fR
.RS 4
An automount unit will be created for the file system\&. See
\fBsystemd.automount\fR(5)
for details\&.
.RE
.PP
\fBx\-systemd\&.idle\-timeout=\fR
.RS 4
Configures the idleness timeout of the automount unit\&. See
\fITimeoutIdleSec=\fR
in
\fBsystemd.automount\fR(5)
for details\&.
.RE
.PP
\fBx\-systemd\&.device\-timeout=\fR
.RS 4
Configure how long systemd should wait for a device to show up before giving up on an entry from
/etc/fstab\&. Specify a time in seconds or explicitly append a unit as
"s",
"min",
"h",
"ms"\&.
.sp
Note that this option can only be used in
/etc/fstab, and will be ignored when part of
\fIOptions=\fR
setting in a unit file\&.
.RE
.PP
\fBnoauto\fR, \fBauto\fR
.RS 4
With
\fBnoauto\fR, this mount will not be added as a dependency for
local\-fs\&.target
or
remote\-fs\&.target\&. This means that it will not be mounted automatically during boot, unless it is pulled in by some other unit\&. Option
\fBauto\fR
has the opposite meaning and is the default\&.
.RE
.PP
\fBnofail\fR
.RS 4
With
\fBnofail\fR
this mount will be only wanted, not required, by
local\-fs\&.target
or
remote\-fs\&.target\&. This means that the boot will continue even if this mount point is not mounted successfully\&.
.RE
.PP
\fBx\-initrd\&.mount\fR
.RS 4
An additional filesystem to be mounted in the initramfs\&. See
initrd\-fs\&.target
description in
\fBsystemd.special\fR(7)\&.
.RE
.PP
If a mount point is configured in both
/etc/fstab
and a unit file that is stored below
/usr, the former will take precedence\&. If the unit file is stored below
/etc, it will take precedence\&. This means: native unit files take precedence over traditional configuration files, but this is superseded by the rule that configuration in
/etc
will always take precedence over configuration in
/usr\&.
.SH "OPTIONS"
.PP
Mount files must include a [Mount] section, which carries information about the file system mount points it supervises\&. A number of options that may be used in this section are shared with other unit types\&. These options are documented in
\fBsystemd.exec\fR(5)
and
\fBsystemd.kill\fR(5)\&. The options specific to the [Mount] section of mount units are the following:
.PP
\fIWhat=\fR
.RS 4
Takes an absolute path of a device node, file or other resource to mount\&. See
\fBmount\fR(8)
for details\&. If this refers to a device node, a dependency on the respective device unit is automatically created\&. (See
\fBsystemd.device\fR(5)
for more information\&.) This option is mandatory\&.
.RE
.PP
\fIWhere=\fR
.RS 4
Takes an absolute path of a directory of the mount point\&. If the mount point does not exist at the time of mounting, it is created\&. This string must be reflected in the unit filename\&. (See above\&.) This option is mandatory\&.
.RE
.PP
\fIType=\fR
.RS 4
Takes a string for the file system type\&. See
\fBmount\fR(8)
for details\&. This setting is optional\&.
.RE
.PP
\fIOptions=\fR
.RS 4
Mount options to use when mounting\&. This takes a comma\-separated list of options\&. This setting is optional\&.
.RE
.PP
\fISloppyOptions=\fR
.RS 4
Takes a boolean argument\&. If true, parsing of the options specified in
\fIOptions=\fR
is relaxed, and unknown mount options are tolerated\&. This corresponds with
\fBmount\fR(8)\*(Aqs
\fI\-s\fR
switch\&. Defaults to off\&.
.RE
.PP
\fIDirectoryMode=\fR
.RS 4
Directories of mount points (and any parent directories) are automatically created if needed\&. This option specifies the file system access mode used when creating these directories\&. Takes an access mode in octal notation\&. Defaults to 0755\&.
.RE
.PP
\fITimeoutSec=\fR
.RS 4
Configures the time to wait for the mount command to finish\&. If a command does not exit within the configured time, the mount will be considered failed and be shut down again\&. All commands still running will be terminated forcibly via
\fBSIGTERM\fR, and after another delay of this time with
\fBSIGKILL\fR\&. (See
\fBKillMode=\fR
in
\fBsystemd.kill\fR(5)\&.) Takes a unit\-less value in seconds, or a time span value such as "5min 20s"\&. Pass 0 to disable the timeout logic\&. The default value is set from the manager configuration file\*(Aqs
\fIDefaultTimeoutStart=\fR
variable\&.
.RE
.PP
Check
\fBsystemd.exec\fR(5)
and
\fBsystemd.kill\fR(5)
for more settings\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBsystemd.unit\fR(5),
\fBsystemd.exec\fR(5),
\fBsystemd.kill\fR(5),
\fBsystemd.resource-control\fR(5),
\fBsystemd.service\fR(5),
\fBsystemd.device\fR(5),
\fBproc\fR(5),
\fBmount\fR(8),
\fBsystemd-fstab-generator\fR(8),
\fBsystemd.directives\fR(7)
.SH "NOTES"
.IP " 1." 4
API File Systems
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
.RE
