'\" t
.TH "SYSTEMD\-USER\-SESSIONS\&.SERVICE" "8" "" "systemd 220" "systemd-user-sessions.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-user-sessions.service, systemd-user-sessions \- Permit user logins after boot, prohibit user logins at shutdown
.SH "SYNOPSIS"
.PP
systemd\-user\-sessions\&.service
.PP
/usr/lib/systemd/systemd\-user\-sessions
.SH "DESCRIPTION"
.PP
systemd\-user\-sessions\&.service
is a service that controls user logins through
\fBpam_nologin\fR(8)\&. After basic system initialization is complete it removes
/run/nologin, thus permitting logins\&. Before system shutdown it creates
/run/nologin, thus prohibiting further logins\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-logind.service\fR(8),
\fBpam_nologin\fR(8)
