'\" t
.TH "SYSTEMD\-BUS\-PROXYD" "8" "" "systemd 221" "systemd-bus-proxyd"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-bus-proxyd \- Connect STDIO or a socket to a given bus address
.SH "SYNOPSIS"
.HP \w'\fB/usr/lib/systemd/systemd\-bus\-proxyd\fR\ 'u
\fB/usr/lib/systemd/systemd\-bus\-proxyd\fR [OPTIONS...] [\fIPLACEHOLDER\fR]
.SH "DESCRIPTION"
.PP
\fBsystemd\-bus\-proxyd\fR
will proxy D\-Bus messages to and from a bus\&. The will be either the system bus or the bus specified with
\fB\-\-address\fR
when that option is given\&. Messages will be proxied to/from standard input and output, or the socket received through socket activation\&.
.PP
This program can be used to connect a program using classic D\-Bus to kdbus\&.
.SH "OPTIONS AND ARGUMENTS"
.PP
The following options are understood:
.PP
\fB\-\-address=\fR\fB\fIADDRESS\fR\fR\fB[:\fIADDRESS\&.\&.\&.\fR]\fR
.RS 4
Connect to the bus specified by
\fIADDRESS\fR\&. Multiple colon\-separated addresses can be specified, in which case
\fBsystemd\-bus\-proxyd\fR
will attempt to connect to them in turn\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.PP
\fIPLACEHOLDER\fR, if given, must be a string of
"x"
and will be used to display information about the process that
\fBsystemd\-bus\-proxyd\fR
is forwarding messages for\&.
.SH "SEE ALSO"
.PP
\fBdbus-daemon\fR(1),
\m[blue]\fBD\-Bus\fR\m[]\&\s-2\u[1]\d\s+2,
\m[blue]\fBkdbus\fR\m[]\&\s-2\u[2]\d\s+2
.SH "NOTES"
.IP " 1." 4
D-Bus
.RS 4
\%http://freedesktop.org/wiki/Software/dbus
.RE
.IP " 2." 4
kdbus
.RS 4
\%https://code.google.com/p/d-bus/
.RE
