'\" t
.TH "SYSTEMD\&.SLICE" "5" "" "systemd 220" "systemd.slice"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.slice \- Slice unit configuration
.SH "SYNOPSIS"
.PP
\fIslice\fR\&.slice
.SH "DESCRIPTION"
.PP
A unit configuration file whose name ends in
"\&.slice"
encodes information about a slice which is a concept for hierarchically managing resources of a group of processes\&. This management is performed by creating a node in the Linux Control Group (cgroup) tree\&. Units that manage processes (primarily scope and service units) may be assigned to a specific slice\&. For each slice, certain resource limits may be set that apply to all processes of all units contained in that slice\&. Slices are organized hierarchically in a tree\&. The name of the slice encodes the location in the tree\&. The name consists of a dash\-separated series of names, which describes the path to the slice from the root slice\&. The root slice is named,
\-\&.slice\&. Example:
foo\-bar\&.slice
is a slice that is located within
foo\&.slice, which in turn is located in the root slice
\-\&.slice\&.
.PP
By default, service and scope units are placed in
system\&.slice, virtual machines and containers registered with
\fBsystemd-machined\fR(1)
are found in
machine\&.slice, and user sessions handled by
\fBsystemd-logind\fR(1)
in
user\&.slice\&. See
\fBsystemd.special\fR(5)
for more information\&.
.PP
See
\fBsystemd.unit\fR(5)
for the common options of all unit configuration files\&. The common configuration items are configured in the generic [Unit] and [Install] sections\&. The slice specific configuration options are configured in the [Slice] section\&. Currently, only generic resource control settings as described in
\fBsystemd.resource-control\fR(7)
are allowed\&.
.PP
Unless
\fIDefaultDependencies=false\fR
is used, slice units will implicitly have dependencies of type
\fIConflicts=\fR
and
\fIBefore=\fR
on
shutdown\&.target\&. These ensure that slice units are removed prior to system shutdown\&. Only slice units involved with early boot or late system shutdown should disable this option\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd.unit\fR(5),
\fBsystemd.resource-control\fR(5),
\fBsystemd.service\fR(5),
\fBsystemd.scope\fR(5),
\fBsystemd.special\fR(7),
\fBsystemd.directives\fR(7)
