'\" t
.TH "SYSTEMD\-SHUTDOWND\&.SERVICE" "8" "" "systemd 215" "systemd-shutdownd.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-shutdownd.service, systemd-shutdownd.socket, systemd-shutdownd \- Scheduled shutdown service
.SH "SYNOPSIS"
.PP
systemd\-shutdownd\&.service
.PP
systemd\-shutdownd\&.socket
.PP
/usr/lib/systemd/systemd\-shutdownd
.SH "DESCRIPTION"
.PP
systemd\-shutdownd\&.service
is a system service that implements scheduled shutdowns, as exposed by
\fBshutdown\fR(8)\&.
systemd\-shutdownd\&.service
is automatically activated on request and terminates itself when it is unused\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBshutdown\fR(8)
