'\" t
.TH "SYSTEMD\-MACHINE\-ID\-SETUP" "1" "" "systemd 220" "systemd-machine-id-setup"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-machine-id-setup \- Initialize the machine ID in /etc/machine\-id
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-machine\-id\-setup\fR\ 'u
\fBsystemd\-machine\-id\-setup\fR
.SH "DESCRIPTION"
.PP
\fBsystemd\-machine\-id\-setup\fR
may be used by system installer tools to initialize the machine ID stored in
/etc/machine\-id
at install time with a randomly generated ID\&. See
\fBmachine-id\fR(5)
for more information about this file\&.
.PP
This tool will execute no operation if
/etc/machine\-id
is already initialized\&.
.PP
If a valid D\-Bus machine ID is already configured for the system, the D\-Bus machine ID is copied and used to initialize the machine ID in
/etc/machine\-id\&.
.PP
If run inside a KVM virtual machine and a UUID is passed via the
\fB\-uuid\fR
option, this UUID is used to initialize the machine ID instead of a randomly generated one\&. The caller must ensure that the UUID passed is sufficiently unique and is different for every booted instanced of the VM\&.
.PP
Similar, if run inside a Linux container environment and a UUID is set for the container this is used to initialize the machine ID\&. For details see the documentation of the
\m[blue]\fBContainer Interface\fR\m[]\&\s-2\u[1]\d\s+2\&.
.PP
Use
\fBsystemd-firstboot\fR(1)
to initialize the machine ID on mounted (but not booted) system images\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-root=\fR\fB\fIroot\fR\fR
.RS 4
Takes a directory path as an argument\&. All paths will be prefixed with the given alternate
\fIroot\fR
path, including config search paths\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBmachine-id\fR(5),
\fBdbus-uuidgen\fR(1),
\fBsystemd-firstboot\fR(1)
.SH "NOTES"
.IP " 1." 4
Container Interface
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/ContainerInterface
.RE
