'\" t
.TH "SYSTEMD\-UPDATE\-UTMP\&.SERVICE" "8" "" "systemd 221" "systemd-update-utmp.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-update-utmp.service, systemd-update-utmp-runlevel.service, systemd-update-utmp \- Write audit and utmp updates at bootup, runlevel changes and shutdown
.SH "SYNOPSIS"
.PP
systemd\-update\-utmp\&.service
.PP
systemd\-update\-utmp\-runlevel\&.service
.PP
/usr/lib/systemd/systemd\-update\-utmp
.SH "DESCRIPTION"
.PP
systemd\-update\-utmp\-runlevel\&.service
is a service that writes SysV runlevel changes to utmp and wtmp, as well as the audit logs, as they occur\&.
systemd\-update\-utmp\&.service
does the same for system reboots and shutdown requests\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fButmp\fR(5),
\fBauditd\fR(8)
