'\" t
.TH "SYSTEMD\-BUS\-PROXYD@\&.SERVICE" "8" "" "systemd 221" "systemd-bus-proxyd@.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-bus-proxyd@.service, systemd-bus-proxyd.socket \- Proxy classic D\-Bus clients to kdbus
.SH "SYNOPSIS"
.PP
systemd\-bus\-proxyd@\&.service
.PP
systemd\-bus\-proxyd\&.socket
.SH "DESCRIPTION"
.PP
systemd\-bus\-proxyd\&.socket
will launch
systemd\-bus\-proxyd@\&.service
for connections to the classic D\-Bus socket in
/var/run/dbus/system_bus_socket\&.
.PP
systemd\-bus\-proxyd@\&.service
is launched for an existing D\-Bus connection and will use
\fBsystemd\-bus\-proxyd\fR
to proxy messages from this connection to the system bus (either kdbus or classic D\-Bus)\&.
.SH "SEE ALSO"
.PP
\fBsystemd-bus-proxyd\fR(8),
\fBdbus-daemon\fR(1),
\m[blue]\fBD\-Bus\fR\m[]\&\s-2\u[1]\d\s+2,
\m[blue]\fBkdbus\fR\m[]\&\s-2\u[2]\d\s+2
.SH "NOTES"
.IP " 1." 4
D-Bus
.RS 4
\%http://freedesktop.org/wiki/Software/dbus
.RE
.IP " 2." 4
kdbus
.RS 4
\%https://code.google.com/p/d-bus/
.RE
