'\" t
.TH "SYSTEMD\-PATH" "1" "" "systemd 215" "systemd-path"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-path \- List and query system and user paths
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-path\ \fR\fB[OPTIONS...]\fR\fB\ \fR\fB[NAME...]\fR\ 'u
\fBsystemd\-path \fR\fB[OPTIONS...]\fR\fB \fR\fB[NAME...]\fR
.SH "DESCRIPTION"
.PP
\fBsystemd\-path\fR
may be used to query system and user paths\&. The tool makes many of the paths described in
\fBfile-hierarchy\fR(7)
queriable\&.
.PP
When invoked without arguments a list of known paths and their current values is shown\&. When at least one argument is passed the path with this is name is queried and its value shown\&. The variables whose name begins with
"search\-"
don\*(Aqt refer to individual paths, but instead a to a list of colon\-separated search paths, in their order of precedence\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-suffix=\fR
.RS 4
The printed paths are suffixed by the specified string\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBfile-hierarchy\fR(7)
