'\" t
.TH "SYSTEMD\&.SERVICE" "5" "" "systemd 215" "systemd.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.service \- Service unit configuration
.SH "SYNOPSIS"
.PP
\fIservice\fR\&.service
.SH "DESCRIPTION"
.PP
A unit configuration file whose name ends in
\&.service
encodes information about a process controlled and supervised by systemd\&.
.PP
This man page lists the configuration options specific to this unit type\&. See
\fBsystemd.unit\fR(5)
for the common options of all unit configuration files\&. The common configuration items are configured in the generic
"[Unit]"
and
"[Install]"
sections\&. The service specific configuration options are configured in the
"[Service]"
section\&.
.PP
Additional options are listed in
\fBsystemd.exec\fR(5), which define the execution environment the commands are executed in, and in
\fBsystemd.kill\fR(5), which define the way the processes of the service are terminated, and in
\fBsystemd.resource-control\fR(5), which configure resource control settings for the processes of the service\&.
.PP
Unless
\fIDefaultDependencies=\fR
is set to
\fBfalse\fR, service units will implicitly have dependencies of type
\fIRequires=\fR
and
\fIAfter=\fR
on
basic\&.target
as well as dependencies of type
\fIConflicts=\fR
and
\fIBefore=\fR
on
shutdown\&.target\&. These ensure that normal service units pull in basic system initialization, and are terminated cleanly prior to system shutdown\&. Only services involved with early boot or late system shutdown should disable this option\&.
.PP
If a service is requested under a certain name but no unit configuration file is found, systemd looks for a SysV init script by the same name (with the
\&.service
suffix removed) and dynamically creates a service unit from that script\&. This is useful for compatibility with SysV\&. Note that this compatibility is quite comprehensive but not 100%\&. For details about the incompatibilities, see the
\m[blue]\fBIncompatibilities with SysV\fR\m[]\&\s-2\u[1]\d\s+2
document\&.
.SH "OPTIONS"
.PP
Service files must include a
"[Service]"
section, which carries information about the service and the process it supervises\&. A number of options that may be used in this section are shared with other unit types\&. These options are documented in
\fBsystemd.exec\fR(5)
and
\fBsystemd.kill\fR(5)\&. The options specific to the
"[Service]"
section of service units are the following:
.PP
\fIType=\fR
.RS 4
Configures the process start\-up type for this service unit\&. One of
\fBsimple\fR,
\fBforking\fR,
\fBoneshot\fR,
\fBdbus\fR,
\fBnotify\fR
or
\fBidle\fR\&.
.sp
If set to
\fBsimple\fR
(the default value if neither
\fIType=\fR
nor
\fIBusName=\fR
are specified), it is expected that the process configured with
\fIExecStart=\fR
is the main process of the service\&. In this mode, if the process offers functionality to other processes on the system, its communication channels should be installed before the daemon is started up (e\&.g\&. sockets set up by systemd, via socket activation), as systemd will immediately proceed starting follow\-up units\&.
.sp
If set to
\fBforking\fR, it is expected that the process configured with
\fIExecStart=\fR
will call
\fBfork()\fR
as part of its start\-up\&. The parent process is expected to exit when start\-up is complete and all communication channels are set up\&. The child continues to run as the main daemon process\&. This is the behavior of traditional UNIX daemons\&. If this setting is used, it is recommended to also use the
\fIPIDFile=\fR
option, so that systemd can identify the main process of the daemon\&. systemd will proceed with starting follow\-up units as soon as the parent process exits\&.
.sp
Behavior of
\fBoneshot\fR
is similar to
\fBsimple\fR; however, it is expected that the process has to exit before systemd starts follow\-up units\&.
\fIRemainAfterExit=\fR
is particularly useful for this type of service\&.
.sp
Behavior of
\fBdbus\fR
is similar to
\fBsimple\fR; however, it is expected that the daemon acquires a name on the D\-Bus bus, as configured by
\fIBusName=\fR\&. systemd will proceed with starting follow\-up units after the D\-Bus bus name has been acquired\&. Service units with this option configured implicitly gain dependencies on the
dbus\&.socket
unit\&. This type is the default if
\fIBusName=\fR
is specified\&.
.sp
Behavior of
\fBnotify\fR
is similar to
\fBsimple\fR; however, it is expected that the daemon sends a notification message via
\fBsd_notify\fR(3)
or an equivalent call when it has finished starting up\&. systemd will proceed with starting follow\-up units after this notification message has been sent\&. If this option is used,
\fINotifyAccess=\fR
(see below) should be set to open access to the notification socket provided by systemd\&. If
\fINotifyAccess=\fR
is not set, it will be implicitly set to
\fBmain\fR\&. Note that currently
\fIType=\fR\fBnotify\fR
will not work if used in combination with
\fIPrivateNetwork=\fR\fByes\fR\&.
.sp
Behavior of
\fBidle\fR
is very similar to
\fBsimple\fR; however, actual execution of the service binary is delayed until all jobs are dispatched\&. This may be used to avoid interleaving of output of shell services with the status output on the console\&.
.RE
.PP
\fIRemainAfterExit=\fR
.RS 4
Takes a boolean value that specifies whether the service shall be considered active even when all its processes exited\&. Defaults to
\fBno\fR\&.
.RE
.PP
\fIGuessMainPID=\fR
.RS 4
Takes a boolean value that specifies whether systemd should try to guess the main PID of a service if it cannot be determined reliably\&. This option is ignored unless
\fBType=forking\fR
is set and
\fBPIDFile=\fR
is unset because for the other types or with an explicitly configured PID file, the main PID is always known\&. The guessing algorithm might come to incorrect conclusions if a daemon consists of more than one process\&. If the main PID cannot be determined, failure detection and automatic restarting of a service will not work reliably\&. Defaults to
\fByes\fR\&.
.RE
.PP
\fIPIDFile=\fR
.RS 4
Takes an absolute file name pointing to the PID file of this daemon\&. Use of this option is recommended for services where
\fIType=\fR
is set to
\fBforking\fR\&. systemd will read the PID of the main process of the daemon after start\-up of the service\&. systemd will not write to the file configured here\&.
.RE
.PP
\fIBusName=\fR
.RS 4
Takes a D\-Bus bus name that this service is reachable as\&. This option is mandatory for services where
\fIType=\fR
is set to
\fBdbus\fR, but its use is otherwise recommended if the process takes a name on the D\-Bus bus\&.
.RE
.PP
\fIExecStart=\fR
.RS 4
Commands with their arguments that are executed when this service is started\&. For each of the specified commands, the first argument must be an absolute and literal path to an executable\&.
.sp
When
\fIType\fR
is not
\fBoneshot\fR, only one command may be given\&. When
\fIType=oneshot\fR
is used, more than one command may be specified\&. Multiple command lines may be concatenated in a single directive by separating them with semicolons (these semicolons must be passed as separate words)\&. Alternatively, this directive may be specified more than once with the same effect\&. Lone semicolons may be escaped as
"\e;"\&. If the empty string is assigned to this option, the list of commands to start is reset, prior assignments of this option will have no effect\&.
.sp
Each command line is split on whitespace, with the first item being the command to execute, and the subsequent items being the arguments\&. Double quotes ("\&.\&.\&.") and single quotes (\*(Aq\&.\&.\&.\*(Aq) may be used, in which case everything until the next matching quote becomes part of the same argument\&. Quotes themselves are removed after parsing\&. In addition, a trailing backslash ("\e") may be used to merge lines\&. This syntax is intended to be very similar to shell syntax, but only the meta\-characters and expansions described in the following paragraphs are understood\&. Specifically, redirection using
"<",
"<<",
">", and
">>", pipes using
"|", and running programs in the background using
"&"
and
\fIother elements of shell syntax are not supported\fR\&.
.sp
If more than one command is specified, the commands are invoked sequentially in the order they appear in the unit file\&. If one of the commands fails (and is not prefixed with
"\-"), other lines are not executed, and the unit is considered failed\&.
.sp
Unless
\fIType=forking\fR
is set, the process started via this command line will be considered the main process of the daemon\&.
.sp
The command line accepts
"%"
specifiers as described in
\fBsystemd.unit\fR(5)\&. Note that the first argument of the command line (i\&.e\&. the program to execute) may not include specifiers\&.
.sp
Basic environment variable substitution is supported\&. Use
"${FOO}"
as part of a word, or as a word of its own, on the command line, in which case it will be replaced by the value of the environment variable including all whitespace it contains, resulting in a single argument\&. Use
"$FOO"
as a separate word on the command line, in which case it will be replaced by the value of the environment variable split at whitespace, resulting in zero or more arguments\&. To pass a literal dollar sign, use
"$$"\&. Variables whose value is not known at expansion time are treated as empty strings\&. Note that the first argument (i\&.e\&. the program to execute) may not be a variable\&.
.sp
Variables to be used in this fashion may be defined through
\fIEnvironment=\fR
and
\fIEnvironmentFile=\fR\&. In addition, variables listed in the section "Environment variables in spawned processes" in
\fBsystemd.exec\fR(5), which are considered "static configuration", may be used (this includes e\&.g\&.
\fI$USER\fR, but not
\fI$TERM\fR)\&.
.sp
Optionally, if the absolute file name is prefixed with
"@", the second token will be passed as
"argv[0]"
to the executed process, followed by the further arguments specified\&. If the absolute filename is prefixed with
"\-", an exit code of the command normally considered a failure (i\&.e\&. non\-zero exit status or abnormal exit due to signal) is ignored and considered success\&. If both
"\-"
and
"@"
are used, they can appear in either order\&.
.sp
Note that this setting does not directly support shell command lines\&. If shell command lines are to be used, they need to be passed explicitly to a shell implementation of some kind\&. Example:
.sp
.if n \{\
.RS 4
.\}
.nf
ExecStart=/bin/sh \-c \*(Aqdmesg | tac\*(Aq
.fi
.if n \{\
.RE
.\}
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
ExecStart=/bin/echo one ; /bin/echo "two two"
.fi
.if n \{\
.RE
.\}
.sp
This will execute
\fB/bin/echo\fR
two times, each time with one argument:
"one"
and
"two two", respectively\&. Because two commands are specified,
\fIType=oneshot\fR
must be used\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
ExecStart=/bin/echo / >/dev/null & \e; \e
/bin/ls
.fi
.if n \{\
.RE
.\}
.sp
This will execute
\fB/bin/echo\fR
with five arguments:
"/",
">/dev/null",
"&",
";", and
"/bin/ls"\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
Environment="ONE=one" \*(AqTWO=two two\*(Aq
ExecStart=/bin/echo $ONE $TWO ${TWO}
.fi
.if n \{\
.RE
.\}
.sp
This will execute
\fB/bin/echo\fR
with four arguments:
"one",
"two",
"two", and
"two two"\&.
.RE
.PP
\fIExecStartPre=\fR, \fIExecStartPost=\fR
.RS 4
Additional commands that are executed before or after the command in
\fIExecStart=\fR, respectively\&. Syntax is the same as for
\fIExecStart=\fR, except that multiple command lines are allowed and the commands are executed one after the other, serially\&.
.sp
If any of those commands (not prefixed with
"\-") fail, the rest are not executed and the unit is considered failed\&.
.RE
.PP
\fIExecReload=\fR
.RS 4
Commands to execute to trigger a configuration reload in the service\&. This argument takes multiple command lines, following the same scheme as described for
\fIExecStart=\fR
above\&. Use of this setting is optional\&. Specifier and environment variable substitution is supported here following the same scheme as for
\fIExecStart=\fR\&.
.sp
One additional, special environment variable is set: if known,
\fI$MAINPID\fR
is set to the main process of the daemon, and may be used for command lines like the following:
.sp
.if n \{\
.RS 4
.\}
.nf
/bin/kill \-HUP $MAINPID
.fi
.if n \{\
.RE
.\}
.sp
Note however that reloading a daemon by sending a signal (as with the example line above) is usually not a good choice, because this is an asynchronous operation and hence not suitable to order reloads of multiple services against each other\&. It is strongly recommended to set
\fIExecReload=\fR
to a command that not only triggers a configuration reload of the daemon, but also synchronously waits for it to complete\&.
.RE
.PP
\fIExecStop=\fR
.RS 4
Commands to execute to stop the service started via
\fIExecStart=\fR\&. This argument takes multiple command lines, following the same scheme as described for
\fIExecStart=\fR
above\&. Use of this setting is optional\&. After the commands configured in this option are run, all processes remaining for a service are terminated according to the
\fIKillMode=\fR
setting (see
\fBsystemd.kill\fR(5))\&. If this option is not specified, the process is terminated immediately when service stop is requested\&. Specifier and environment variable substitution is supported (including
\fI$MAINPID\fR, see above)\&.
.RE
.PP
\fIExecStopPost=\fR
.RS 4
Additional commands that are executed after the service was stopped\&. This includes cases where the commands configured in
\fIExecStop=\fR
were used, where the service does not have any
\fIExecStop=\fR
defined, or where the service exited unexpectedly\&. This argument takes multiple command lines, following the same scheme as described for
\fIExecStart\fR\&. Use of these settings is optional\&. Specifier and environment variable substitution is supported\&.
.RE
.PP
\fIRestartSec=\fR
.RS 4
Configures the time to sleep before restarting a service (as configured with
\fIRestart=\fR)\&. Takes a unit\-less value in seconds, or a time span value such as "5min 20s"\&. Defaults to 100ms\&.
.RE
.PP
\fITimeoutStartSec=\fR
.RS 4
Configures the time to wait for start\-up\&. If a daemon service does not signal start\-up completion within the configured time, the service will be considered failed and will be shut down again\&. Takes a unit\-less value in seconds, or a time span value such as "5min 20s"\&. Pass
"0"
to disable the timeout logic\&. Defaults to
\fITimeoutStartSec=\fR
from the manager configuration file, except when
\fIType=oneshot\fR
is used, in which case the timeout is disabled by default\&.
.RE
.PP
\fITimeoutStopSec=\fR
.RS 4
Configures the time to wait for stop\&. If a service is asked to stop, but does not terminate in the specified time, it will be terminated forcibly via
\fBSIGTERM\fR, and after another timeout of equal duration with
\fBSIGKILL\fR
(see
\fIKillMode=\fR
in
\fBsystemd.kill\fR(5))\&. Takes a unit\-less value in seconds, or a time span value such as "5min 20s"\&. Pass
"0"
to disable the timeout logic\&. Defaults to
\fITimeoutStartSec=\fR
from the manager configuration file\&.
.RE
.PP
\fITimeoutSec=\fR
.RS 4
A shorthand for configuring both
\fITimeoutStartSec=\fR
and
\fITimeoutStopSec=\fR
to the specified value\&.
.RE
.PP
\fIWatchdogSec=\fR
.RS 4
Configures the watchdog timeout for a service\&. The watchdog is activated when the start\-up is completed\&. The service must call
\fBsd_notify\fR(3)
regularly with
"WATCHDOG=1"
(i\&.e\&. the "keep\-alive ping")\&. If the time between two such calls is larger than the configured time, then the service is placed in a failed state\&. By setting
\fIRestart=\fR
to
\fBon\-failure\fR
or
\fBalways\fR, the service will be automatically restarted\&. The time configured here will be passed to the executed service process in the
\fIWATCHDOG_USEC=\fR
environment variable\&. This allows daemons to automatically enable the keep\-alive pinging logic if watchdog support is enabled for the service\&. If this option is used,
\fINotifyAccess=\fR
(see below) should be set to open access to the notification socket provided by systemd\&. If
\fINotifyAccess=\fR
is not set, it will be implicitly set to
\fBmain\fR\&. Defaults to 0, which disables this feature\&.
.RE
.PP
\fIRestart=\fR
.RS 4
Configures whether the service shall be restarted when the service process exits, is killed, or a timeout is reached\&. The service process may be the main service process, but it may also be one of the processes specified with
\fIExecStartPre=\fR,
\fIExecStartPost=\fR,
\fIExecStop=\fR,
\fIExecStopPost=\fR, or
\fIExecReload=\fR\&. When the death of the process is a result of systemd operation (e\&.g\&. service stop or restart), the service will not be restarted\&. Timeouts include missing the watchdog "keep\-alive ping" deadline and a service start, reload, and stop operation timeouts\&.
.sp
Takes one of
\fBno\fR,
\fBon\-success\fR,
\fBon\-failure\fR,
\fBon\-abnormal\fR,
\fBon\-watchdog\fR,
\fBon\-abort\fR, or
\fBalways\fR\&. If set to
\fBno\fR
(the default), the service will not be restarted\&. If set to
\fBon\-success\fR, it will be restarted only when the service process exits cleanly\&. In this context, a clean exit means an exit code of 0, or one of the signals
\fBSIGHUP\fR,
\fBSIGINT\fR,
\fBSIGTERM\fR
or
\fBSIGPIPE\fR, and additionally, exit statuses and signals specified in
\fISuccessExitStatus=\fR\&. If set to
\fBon\-failure\fR, the service will be restarted when the process exits with a non\-zero exit code, is terminated by a signal (including on core dump, but excluding the aforementiond four signals), when an operation (such as service reload) times out, and when the configured watchdog timeout is triggered\&. If set to
\fBon\-abnormal\fR, the service will be restarted when the process is terminated by a signal (including on core dump, excluding the aforementioned four signals), when an operation times out, or when the watchdog timeout is triggered\&. If set to
\fBon\-abort\fR, the service will be restarted only if the service process exits due to an uncaught signal not specified as a clean exit status\&. If set to
\fBon\-watchdog\fR, the service will be restarted only if the watchdog timeout for the service expires\&. If set to
\fBalways\fR, the service will be restarted regardless of whether it exited cleanly or not, got terminated abnormally by a signal, or hit a timeout\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \&Exit causes and the effect of the \fIRestart=\fR settings on them
.TS
allbox tab(:);
lB lB lB lB lB lB lB lB.
T{
Restart settings/Exit causes
T}:T{
\fBno\fR
T}:T{
\fBalways\fR
T}:T{
\fBon\-success\fR
T}:T{
\fBon\-failure\fR
T}:T{
\fBon\-abnormal\fR
T}:T{
\fBon\-abort\fR
T}:T{
\fBon\-watchdog\fR
T}
.T&
l l l l l l l l
l l l l l l l l
l l l l l l l l
l l l l l l l l
l l l l l l l l.
T{
Clean exit code or signal
T}:T{
\ \&
T}:T{
X
T}:T{
X
T}:T{
\ \&
T}:T{
\ \&
T}:T{
\ \&
T}:T{
\ \&
T}
T{
Unclean exit code
T}:T{
\ \&
T}:T{
X
T}:T{
\ \&
T}:T{
X
T}:T{
\ \&
T}:T{
\ \&
T}:T{
\ \&
T}
T{
Unclean signal
T}:T{
\ \&
T}:T{
X
T}:T{
\ \&
T}:T{
X
T}:T{
X
T}:T{
X
T}:T{
\ \&
T}
T{
Timeout
T}:T{
\ \&
T}:T{
X
T}:T{
\ \&
T}:T{
X
T}:T{
X
T}:T{
\ \&
T}:T{
\ \&
T}
T{
Watchdog
T}:T{
\ \&
T}:T{
X
T}:T{
\ \&
T}:T{
X
T}:T{
X
T}:T{
\ \&
T}:T{
X
T}
.TE
.sp 1
As exceptions to the setting above the service will not be restarted if the exit code or signal is specified in
\fIRestartPreventExitStatus=\fR
(see below)\&. Also, the services will always be restarted if the exit code or signal is specified in
\fIRestartForceExitStatus=\fR
(see below)\&.
.sp
Setting this to
\fBon\-failure\fR
is the recommended choice for long\-running services, in order to increase reliability by attempting automatic recovery from errors\&. For services that shall be able to terminate on their own choice (and avoid immediate restarting),
\fBon\-abnormal\fR
is an alternative choice\&.
.RE
.PP
\fISuccessExitStatus=\fR
.RS 4
Takes a list of exit status definitions that when returned by the main service process will be considered successful termination, in addition to the normal successful exit code 0 and the signals
\fBSIGHUP\fR,
\fBSIGINT\fR,
\fBSIGTERM\fR, and
\fBSIGPIPE\fR\&. Exit status definitions can either be numeric exit codes or termination signal names, separated by spaces\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
SuccessExitStatus=1 2 8 SIGKILL
.fi
.if n \{\
.RE
.\}
.sp
ensures that exit codes 1, 2, 8 and the termination signal
\fBSIGKILL\fR
are considered clean service terminations\&.
.sp
Note that if a process has a signal handler installed and exits by calling
\fB_exit\fR(2)
in response to a signal, the information about the signal is lost\&. Programs should instead perform cleanup and kill themselves with the same signal instead\&. See
\m[blue]\fBProper handling of SIGINT/SIGQUIT \(em How to be a proper program\fR\m[]\&\s-2\u[2]\d\s+2\&.
.sp
This option may appear more than once, in which case the list of successful exit statuses is merged\&. If the empty string is assigned to this option, the list is reset, all prior assignments of this option will have no effect\&.
.RE
.PP
\fIRestartPreventExitStatus=\fR
.RS 4
Takes a list of exit status definitions that when returned by the main service process will prevent automatic service restarts, regardless of the restart setting configured with
\fIRestart=\fR\&. Exit status definitions can either be numeric exit codes or termination signal names, and are separated by spaces\&. Defaults to the empty list, so that, by default, no exit status is excluded from the configured restart logic\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
RestartPreventExitStatus=1 6 SIGABRT
.fi
.if n \{\
.RE
.\}
.sp
ensures that exit codes 1 and 6 and the termination signal
\fBSIGABRT\fR
will not result in automatic service restarting\&. This option may appear more than once, in which case the list of restart\-preventing statuses is merged\&. If the empty string is assigned to this option, the list is reset and all prior assignments of this option will have no effect\&.
.RE
.PP
\fIRestartForceExitStatus=\fR
.RS 4
Takes a list of exit status definitions that when returned by the main service process will force automatic service restarts, regardless of the restart setting configured with
\fIRestart=\fR\&. The argument format is similar to
\fIRestartPreventExitStatus=\fR\&.
.RE
.PP
\fIPermissionsStartOnly=\fR
.RS 4
Takes a boolean argument\&. If true, the permission\-related execution options, as configured with
\fIUser=\fR
and similar options (see
\fBsystemd.exec\fR(5)
for more information), are only applied to the process started with
\fIExecStart=\fR, and not to the various other
\fIExecStartPre=\fR,
\fIExecStartPost=\fR,
\fIExecReload=\fR,
\fIExecStop=\fR, and
\fIExecStopPost=\fR
commands\&. If false, the setting is applied to all configured commands the same way\&. Defaults to false\&.
.RE
.PP
\fIRootDirectoryStartOnly=\fR
.RS 4
Takes a boolean argument\&. If true, the root directory, as configured with the
\fIRootDirectory=\fR
option (see
\fBsystemd.exec\fR(5)
for more information), is only applied to the process started with
\fIExecStart=\fR, and not to the various other
\fIExecStartPre=\fR,
\fIExecStartPost=\fR,
\fIExecReload=\fR,
\fIExecStop=\fR, and
\fIExecStopPost=\fR
commands\&. If false, the setting is applied to all configured commands the same way\&. Defaults to false\&.
.RE
.PP
\fINonBlocking=\fR
.RS 4
Set the
\fBO_NONBLOCK\fR
flag for all file descriptors passed via socket\-based activation\&. If true, all file descriptors >= 3 (i\&.e\&. all except stdin, stdout, and stderr) will have the
\fBO_NONBLOCK\fR
flag set and hence are in non\-blocking mode\&. This option is only useful in conjunction with a socket unit, as described in
\fBsystemd.socket\fR(5)\&. Defaults to false\&.
.RE
.PP
\fINotifyAccess=\fR
.RS 4
Controls access to the service status notification socket, as accessible via the
\fBsd_notify\fR(3)
call\&. Takes one of
\fBnone\fR
(the default),
\fBmain\fR
or
\fBall\fR\&. If
\fBnone\fR, no daemon status updates are accepted from the service processes, all status update messages are ignored\&. If
\fBmain\fR, only service updates sent from the main process of the service are accepted\&. If
\fBall\fR, all services updates from all members of the service\*(Aqs control group are accepted\&. This option should be set to open access to the notification socket when using
\fIType=notify\fR
or
\fIWatchdogSec=\fR
(see above)\&. If those options are used but
\fINotifyAccess=\fR
is not configured, it will be implicitly set to
\fBmain\fR\&.
.RE
.PP
\fISockets=\fR
.RS 4
Specifies the name of the socket units this service shall inherit the sockets from when the service is started\&. Normally it should not be necessary to use this setting as all sockets whose unit shares the same name as the service (ignoring the different suffix of course) are passed to the spawned process\&.
.sp
Note that the same socket may be passed to multiple processes at the same time\&. Also note that a different service may be activated on incoming traffic than that which inherits the sockets\&. Or in other words: the
\fIService=\fR
setting of
\&.socket
units does not have to match the inverse of the
\fISockets=\fR
setting of the
\&.service
it refers to\&.
.sp
This option may appear more than once, in which case the list of socket units is merged\&. If the empty string is assigned to this option, the list of sockets is reset, and all prior uses of this setting will have no effect\&.
.RE
.PP
\fIStartLimitInterval=\fR, \fIStartLimitBurst=\fR
.RS 4
Configure service start rate limiting\&. By default, services which are started more than 5 times within 10 seconds are not permitted to start any more times until the 10 second interval ends\&. With these two options, this rate limiting may be modified\&. Use
\fIStartLimitInterval=\fR
to configure the checking interval (defaults to
\fIDefaultStartLimitInterval=\fR
in manager configuration file, set to 0 to disable any kind of rate limiting)\&. Use
\fIStartLimitBurst=\fR
to configure how many starts per interval are allowed (defaults to
\fIDefaultStartLimitBurst=\fR
in manager configuration file)\&. These configuration options are particularly useful in conjunction with
\fIRestart=\fR; however, they apply to all kinds of starts (including manual), not just those triggered by the
\fIRestart=\fR
logic\&. Note that units which are configured for
\fIRestart=\fR
and which reach the start limit are not attempted to be restarted anymore; however, they may still be restarted manually at a later point, from which point on, the restart logic is again activated\&. Note that
\fBsystemctl reset\-failed\fR
will cause the restart rate counter for a service to be flushed, which is useful if the administrator wants to manually start a service and the start limit interferes with that\&.
.RE
.PP
\fIStartLimitAction=\fR
.RS 4
Configure the action to take if the rate limit configured with
\fIStartLimitInterval=\fR
and
\fIStartLimitBurst=\fR
is hit\&. Takes one of
\fBnone\fR,
\fBreboot\fR,
\fBreboot\-force\fR, or
\fBreboot\-immediate\fR\&. If
\fBnone\fR
is set, hitting the rate limit will trigger no action besides that the start will not be permitted\&.
\fBreboot\fR
causes a reboot following the normal shutdown procedure (i\&.e\&. equivalent to
\fBsystemctl reboot\fR)\&.
\fBreboot\-force\fR
causes a forced reboot which will terminate all processes forcibly but should cause no dirty file systems on reboot (i\&.e\&. equivalent to
\fBsystemctl reboot \-f\fR) and
\fBreboot\-immediate\fR
causes immediate execution of the
\fBreboot\fR(2)
system call, which might result in data loss\&. Defaults to
\fBnone\fR\&.
.RE
.PP
\fIRebootArgument=\fR
.RS 4
Configure the optional argument for the
\fBreboot\fR(2)
system call if
\fIStartLimitAction=\fR
is a reboot action\&. This works just like the optional argument to
\fBsystemctl reboot\fR
command\&.
.RE
.PP
\fIFailureAction=\fR
.RS 4
Configure the action to take when the service enters a failed state\&. Takes the same values as
\fIStartLimitAction=\fR
and executes the same actions\&. Defaults to
\fBnone\fR\&.
.RE
.PP
Check
\fBsystemd.exec\fR(5)
and
\fBsystemd.kill\fR(5)
for more settings\&.
.SH "COMPATIBILITY OPTIONS"
.PP
The following options are also available in the
"[Service]"
section, but exist purely for compatibility reasons and should not be used in newly written service files\&.
.PP
\fISysVStartPriority=\fR
.RS 4
Set the SysV start priority to use to order this service in relation to SysV services lacking LSB headers\&. This option is only necessary to fix ordering in relation to legacy SysV services that have no ordering information encoded in the script headers\&. As such, it should only be used as a temporary compatibility option and should not be used in new unit files\&. Almost always, it is a better choice to add explicit ordering directives via
\fIAfter=\fR
or
\fIBefore=\fR, instead\&. For more details, see
\fBsystemd.unit\fR(5)\&. If used, pass an integer value in the range 0\-99\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(8),
\fBsystemd.unit\fR(5),
\fBsystemd.exec\fR(5),
\fBsystemd.resource-control\fR(5),
\fBsystemd.kill\fR(5),
\fBsystemd.directives\fR(7)
.SH "NOTES"
.IP " 1." 4
Incompatibilities with SysV
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/Incompatibilities
.RE
.IP " 2." 4
Proper handling of SIGINT/SIGQUIT \(em How to be a proper program
.RS 4
\%http://www.cons.org/cracauer/sigint.html
.RE
