'\" t
.TH "SYSTEMD\&.SOCKET" "5" "" "systemd 220" "systemd.socket"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.socket \- Socket unit configuration
.SH "SYNOPSIS"
.PP
\fIsocket\fR\&.socket
.SH "DESCRIPTION"
.PP
A unit configuration file whose name ends in
"\&.socket"
encodes information about an IPC or network socket or a file system FIFO controlled and supervised by systemd, for socket\-based activation\&.
.PP
This man page lists the configuration options specific to this unit type\&. See
\fBsystemd.unit\fR(5)
for the common options of all unit configuration files\&. The common configuration items are configured in the generic [Unit] and [Install] sections\&. The socket specific configuration options are configured in the [Socket] section\&.
.PP
Additional options are listed in
\fBsystemd.exec\fR(5), which define the execution environment the
\fBExecStartPre=\fR,
\fBExecStartPost=\fR,
\fBExecStopPre=\fR
and
\fBExecStopPost=\fR
commands are executed in, and in
\fBsystemd.kill\fR(5), which define the way the processes are terminated, and in
\fBsystemd.resource-control\fR(5), which configure resource control settings for the processes of the socket\&.
.PP
For each socket file, a matching service file must exist, describing the service to start on incoming traffic on the socket (see
\fBsystemd.service\fR(5)
for more information about \&.service files)\&. The name of the \&.service unit is by default the same as the name of the \&.socket unit, but can be altered with the
\fBService=\fR
option described below\&. Depending on the setting of the
\fBAccept=\fR
option described below, this \&.service unit must either be named like the \&.socket unit, but with the suffix replaced, unless overridden with
\fBService=\fR; or it must be a template unit named the same way\&. Example: a socket file
foo\&.socket
needs a matching service
foo\&.service
if
\fBAccept=false\fR
is set\&. If
\fBAccept=true\fR
is set, a service template file
foo@\&.service
must exist from which services are instantiated for each incoming connection\&.
.PP
Unless
\fIDefaultDependencies=\fR
is set to
\fBfalse\fR, socket units will implicitly have dependencies of type
\fIRequires=\fR
and
\fIAfter=\fR
on
sysinit\&.target
as well as dependencies of type
\fIConflicts=\fR
and
\fIBefore=\fR
on
shutdown\&.target\&. These ensure that socket units pull in basic system initialization, and are terminated cleanly prior to system shutdown\&. Only sockets involved with early boot or late system shutdown should disable this option\&.
.PP
Socket units will have a
\fIBefore=\fR
dependency on the service which they trigger added implicitly\&. No implicit
\fIWantedBy=\fR
or
\fIRequiredBy=\fR
dependency from the socket to the service is added\&. This means that the service may be started without the socket, in which case it must be able to open sockets by itself\&. To prevent this, an explicit
\fIRequires=\fR
dependency may be added\&.
.PP
Socket units may be used to implement on\-demand starting of services, as well as parallelized starting of services\&. See the blog stories linked at the end for an introduction\&.
.PP
Note that the daemon software configured for socket activation with socket units needs to be able to accept sockets from systemd, either via systemd\*(Aqs native socket passing interface (see
\fBsd_listen_fds\fR(3)
for details) or via the traditional
\fBinetd\fR(8)\-style socket passing (i\&.e\&. sockets passed in via standard input and output, using
\fIStandardInput=socket\fR
in the service file)\&.
.SH "OPTIONS"
.PP
Socket files must include a [Socket] section, which carries information about the socket or FIFO it supervises\&. A number of options that may be used in this section are shared with other unit types\&. These options are documented in
\fBsystemd.exec\fR(5)
and
\fBsystemd.kill\fR(5)\&. The options specific to the [Socket] section of socket units are the following:
.PP
\fIListenStream=\fR, \fIListenDatagram=\fR, \fIListenSequentialPacket=\fR
.RS 4
Specifies an address to listen on for a stream (\fBSOCK_STREAM\fR), datagram (\fBSOCK_DGRAM\fR), or sequential packet (\fBSOCK_SEQPACKET\fR) socket, respectively\&. The address can be written in various formats:
.sp
If the address starts with a slash ("/"), it is read as file system socket in the
\fBAF_UNIX\fR
socket family\&.
.sp
If the address starts with an at symbol ("@"), it is read as abstract namespace socket in the
\fBAF_UNIX\fR
family\&. The
"@"
is replaced with a
\fBNUL\fR
character before binding\&. For details, see
\fBunix\fR(7)\&.
.sp
If the address string is a single number, it is read as port number to listen on via IPv6\&. Depending on the value of
\fIBindIPv6Only=\fR
(see below) this might result in the service being available via both IPv6 and IPv4 (default) or just via IPv6\&.
.sp
If the address string is a string in the format v\&.w\&.x\&.y:z, it is read as IPv4 specifier for listening on an address v\&.w\&.x\&.y on a port z\&.
.sp
If the address string is a string in the format [x]:y, it is read as IPv6 address x on a port y\&. Note that this might make the service available via IPv4, too, depending on the
\fIBindIPv6Only=\fR
setting (see below)\&.
.sp
Note that
\fBSOCK_SEQPACKET\fR
(i\&.e\&.
\fIListenSequentialPacket=\fR) is only available for
\fBAF_UNIX\fR
sockets\&.
\fBSOCK_STREAM\fR
(i\&.e\&.
\fIListenStream=\fR) when used for IP sockets refers to TCP sockets,
\fBSOCK_DGRAM\fR
(i\&.e\&.
\fIListenDatagram=\fR) to UDP\&.
.sp
These options may be specified more than once in which case incoming traffic on any of the sockets will trigger service activation, and all listed sockets will be passed to the service, regardless of whether there is incoming traffic on them or not\&. If the empty string is assigned to any of these options, the list of addresses to listen on is reset, all prior uses of any of these options will have no effect\&.
.sp
It is also possible to have more than one socket unit for the same service when using
\fIService=\fR, and the service will receive all the sockets configured in all the socket units\&. Sockets configured in one unit are passed in the order of configuration, but no ordering between socket units is specified\&.
.sp
If an IP address is used here, it is often desirable to listen on it before the interface it is configured on is up and running, and even regardless of whether it will be up and running at any point\&. To deal with this, it is recommended to set the
\fIFreeBind=\fR
option described below\&.
.RE
.PP
\fIListenFIFO=\fR
.RS 4
Specifies a file system FIFO to listen on\&. This expects an absolute file system path as argument\&. Behavior otherwise is very similar to the
\fIListenDatagram=\fR
directive above\&.
.RE
.PP
\fIListenSpecial=\fR
.RS 4
Specifies a special file in the file system to listen on\&. This expects an absolute file system path as argument\&. Behavior otherwise is very similar to the
\fIListenFIFO=\fR
directive above\&. Use this to open character device nodes as well as special files in
/proc
and
/sys\&.
.RE
.PP
\fIListenNetlink=\fR
.RS 4
Specifies a Netlink family to create a socket for to listen on\&. This expects a short string referring to the
\fBAF_NETLINK\fR
family name (such as
\fIaudit\fR
or
\fIkobject\-uevent\fR) as argument, optionally suffixed by a whitespace followed by a multicast group integer\&. Behavior otherwise is very similar to the
\fIListenDatagram=\fR
directive above\&.
.RE
.PP
\fIListenMessageQueue=\fR
.RS 4
Specifies a POSIX message queue name to listen on\&. This expects a valid message queue name (i\&.e\&. beginning with /)\&. Behavior otherwise is very similar to the
\fIListenFIFO=\fR
directive above\&. On Linux message queue descriptors are actually file descriptors and can be inherited between processes\&.
.RE
.PP
\fIBindIPv6Only=\fR
.RS 4
Takes a one of
\fBdefault\fR,
\fBboth\fR
or
\fBipv6\-only\fR\&. Controls the IPV6_V6ONLY socket option (see
\fBipv6\fR(7)
for details)\&. If
\fBboth\fR, IPv6 sockets bound will be accessible via both IPv4 and IPv6\&. If
\fBipv6\-only\fR, they will be accessible via IPv6 only\&. If
\fBdefault\fR
(which is the default, surprise!), the system wide default setting is used, as controlled by
/proc/sys/net/ipv6/bindv6only, which in turn defaults to the equivalent of
\fBboth\fR\&.
.RE
.PP
\fIBacklog=\fR
.RS 4
Takes an unsigned integer argument\&. Specifies the number of connections to queue that have not been accepted yet\&. This setting matters only for stream and sequential packet sockets\&. See
\fBlisten\fR(2)
for details\&. Defaults to SOMAXCONN (128)\&.
.RE
.PP
\fIBindToDevice=\fR
.RS 4
Specifies a network interface name to bind this socket to\&. If set, traffic will only be accepted from the specified network interfaces\&. This controls the SO_BINDTODEVICE socket option (see
\fBsocket\fR(7)
for details)\&. If this option is used, an automatic dependency from this socket unit on the network interface device unit (\fBsystemd.device\fR(5)
is created\&.
.RE
.PP
\fISocketUser=\fR, \fISocketGroup=\fR
.RS 4
Takes a UNIX user/group name\&. When specified, all AF_UNIX sockets and FIFO nodes in the file system are owned by the specified user and group\&. If unset (the default), the nodes are owned by the root user/group (if run in system context) or the invoking user/group (if run in user context)\&. If only a user is specified but no group, then the group is derived from the user\*(Aqs default group\&.
.RE
.PP
\fISocketMode=\fR
.RS 4
If listening on a file system socket or FIFO, this option specifies the file system access mode used when creating the file node\&. Takes an access mode in octal notation\&. Defaults to 0666\&.
.RE
.PP
\fIDirectoryMode=\fR
.RS 4
If listening on a file system socket or FIFO, the parent directories are automatically created if needed\&. This option specifies the file system access mode used when creating these directories\&. Takes an access mode in octal notation\&. Defaults to 0755\&.
.RE
.PP
\fIAccept=\fR
.RS 4
Takes a boolean argument\&. If true, a service instance is spawned for each incoming connection and only the connection socket is passed to it\&. If false, all listening sockets themselves are passed to the started service unit, and only one service unit is spawned for all connections (also see above)\&. This value is ignored for datagram sockets and FIFOs where a single service unit unconditionally handles all incoming traffic\&. Defaults to
\fBfalse\fR\&. For performance reasons, it is recommended to write new daemons only in a way that is suitable for
\fBAccept=false\fR\&. A daemon listening on an
\fBAF_UNIX\fR
socket may, but does not need to, call
\fBclose\fR(2)
on the received socket before exiting\&. However, it must not unlink the socket from a file system\&. It should not invoke
\fBshutdown\fR(2)
on sockets it got with
\fIAccept=false\fR, but it may do so for sockets it got with
\fIAccept=true\fR
set\&. Setting
\fIAccept=true\fR
is mostly useful to allow daemons designed for usage with
\fBinetd\fR(8)
to work unmodified with systemd socket activation\&.
.sp
For IPv4 and IPv6 connections the
\fIREMOTE_ADDR\fR
environment variable will contain the remote IP, and
\fIREMOTE_PORT\fR
will contain the remote port\&. This is the same as the format used by CGI\&. For SOCK_RAW the port is the IP protocol\&.
.RE
.PP
\fIMaxConnections=\fR
.RS 4
The maximum number of connections to simultaneously run services instances for, when
\fBAccept=true\fR
is set\&. If more concurrent connections are coming in, they will be refused until at least one existing connection is terminated\&. This setting has no effect on sockets configured with
\fBAccept=false\fR
or datagram sockets\&. Defaults to 64\&.
.RE
.PP
\fIKeepAlive=\fR
.RS 4
Takes a boolean argument\&. If true, the TCP/IP stack will send a keep alive message after 2h (depending on the configuration of
/proc/sys/net/ipv4/tcp_keepalive_time) for all TCP streams accepted on this socket\&. This controls the SO_KEEPALIVE socket option (see
\fBsocket\fR(7)
and the
\m[blue]\fBTCP Keepalive HOWTO\fR\m[]\&\s-2\u[1]\d\s+2
for details\&.) Defaults to
\fBfalse\fR\&.
.RE
.PP
\fIKeepAliveTimeSec=\fR
.RS 4
Takes time (in seconds) as argument \&. The connection needs to remain idle before TCP starts sending keepalive probes\&. This controls the TCP_KEEPIDLE socket option (see
\fBsocket\fR(7)
and the
\m[blue]\fBTCP Keepalive HOWTO\fR\m[]\&\s-2\u[1]\d\s+2
for details\&.) Defaults value is 7200 seconds (2 hours)\&.
.RE
.PP
\fIKeepAliveIntervalSec=\fR
.RS 4
Takes time (in seconds) as argument between individual keepalive probes, if the socket option SO_KEEPALIVE has been set on this socket seconds as argument\&. This controls the TCP_KEEPINTVL socket option (see
\fBsocket\fR(7)
and the
\m[blue]\fBTCP Keepalive HOWTO\fR\m[]\&\s-2\u[1]\d\s+2
for details\&.) Defaults value is 75 seconds\&.
.RE
.PP
\fIKeepAliveProbes=\fR
.RS 4
Takes integer as argument\&. It\*(Aqs the number of unacknowledged probes to send before considering the connection dead and notifying the application layer\&. This controls the TCP_KEEPCNT socket option (see
\fBsocket\fR(7)
and the
\m[blue]\fBTCP Keepalive HOWTO\fR\m[]\&\s-2\u[1]\d\s+2
for details\&.) Defaults value is 9\&.
.RE
.PP
\fINoDelay=\fR
.RS 4
Takes a boolean argument\&. TCP Nagle\*(Aqs algorithm works by combining a number of small outgoing messages, and sending them all at once\&. This controls the TCP_NODELAY socket option (see
\fBtcp\fR(7)
Defaults to
\fBfalse\fR\&.
.RE
.PP
\fIPriority=\fR
.RS 4
Takes an integer argument controlling the priority for all traffic sent from this socket\&. This controls the SO_PRIORITY socket option (see
\fBsocket\fR(7)
for details\&.)\&.
.RE
.PP
\fIDeferAcceptSec=\fR
.RS 4
Takes time (in seconds) as argument\&. If set, the listening process will be awakened only when data arrives on the socket, and not immediately when connection is established\&. When this option is set, the
\fBTCP_DEFER_ACCEPT\fR
socket option will be used (see
\fBtcp\fR(7)), and the kernel will ignore initial ACK packets without any data\&. The argument specifies the approximate amount of time the kernel should wait for incoming data before falling back to the normal behaviour of honouring empty ACK packets\&. This option is beneficial for protocols where the client sends the data first (e\&.g\&. HTTP, in contrast to SMTP), because the server process will not be woken up unnecessarily before it can take any action\&.
.sp
If the client also uses the
\fBTCP_DEFER_ACCEPT\fR
option, the latency of the initial connection may be reduced, because the kernel will send data in the final packet establishing the connection (the third packet in the "three\-way handshake")\&.
.sp
Disabled by default\&.
.RE
.PP
\fIReceiveBuffer=\fR, \fISendBuffer=\fR
.RS 4
Takes an integer argument controlling the receive or send buffer sizes of this socket, respectively\&. This controls the SO_RCVBUF and SO_SNDBUF socket options (see
\fBsocket\fR(7)
for details\&.)\&. The usual suffixes K, M, G are supported and are understood to the base of 1024\&.
.RE
.PP
\fIIPTOS=\fR
.RS 4
Takes an integer argument controlling the IP Type\-Of\-Service field for packets generated from this socket\&. This controls the IP_TOS socket option (see
\fBip\fR(7)
for details\&.)\&. Either a numeric string or one of
\fBlow\-delay\fR,
\fBthroughput\fR,
\fBreliability\fR
or
\fBlow\-cost\fR
may be specified\&.
.RE
.PP
\fIIPTTL=\fR
.RS 4
Takes an integer argument controlling the IPv4 Time\-To\-Live/IPv6 Hop\-Count field for packets generated from this socket\&. This sets the IP_TTL/IPV6_UNICAST_HOPS socket options (see
\fBip\fR(7)
and
\fBipv6\fR(7)
for details\&.)
.RE
.PP
\fIMark=\fR
.RS 4
Takes an integer value\&. Controls the firewall mark of packets generated by this socket\&. This can be used in the firewall logic to filter packets from this socket\&. This sets the SO_MARK socket option\&. See
\fBiptables\fR(8)
for details\&.
.RE
.PP
\fIReusePort=\fR
.RS 4
Takes a boolean value\&. If true, allows multiple
\fBbind\fR(2)s to this TCP or UDP port\&. This controls the SO_REUSEPORT socket option\&. See
\fBsocket\fR(7)
for details\&.
.RE
.PP
\fISmackLabel=\fR, \fISmackLabelIPIn=\fR, \fISmackLabelIPOut=\fR
.RS 4
Takes a string value\&. Controls the extended attributes
"security\&.SMACK64",
"security\&.SMACK64IPIN"
and
"security\&.SMACK64IPOUT", respectively, i\&.e\&. the security label of the FIFO, or the security label for the incoming or outgoing connections of the socket, respectively\&. See
\m[blue]\fBSmack\&.txt\fR\m[]\&\s-2\u[2]\d\s+2
for details\&.
.RE
.PP
\fISELinuxContextFromNet=\fR
.RS 4
Takes a boolean argument\&. When true, systemd will attempt to figure out the SELinux label used for the instantiated service from the information handed by the peer over the network\&. Note that only the security level is used from the information provided by the peer\&. Other parts of the resulting SELinux context originate from either the target binary that is effectively triggered by socket unit or from the value of the
\fISELinuxContext=\fR
option\&. This configuration option only affects sockets with
\fIAccept=\fR
mode set to
"true"\&. Also note that this option is useful only when MLS/MCS SELinux policy is deployed\&. Defaults to
"false"\&.
.RE
.PP
\fIPipeSize=\fR
.RS 4
Takes a size in bytes\&. Controls the pipe buffer size of FIFOs configured in this socket unit\&. See
\fBfcntl\fR(2)
for details\&. The usual suffixes K, M, G are supported and are understood to the base of 1024\&.
.RE
.PP
\fIMessageQueueMaxMessages=\fR, \fIMessageQueueMessageSize=\fR
.RS 4
These two settings take integer values and control the mq_maxmsg field or the mq_msgsize field, respectively, when creating the message queue\&. Note that either none or both of these variables need to be set\&. See
\fBmq_setattr\fR(3)
for details\&.
.RE
.PP
\fIFreeBind=\fR
.RS 4
Takes a boolean value\&. Controls whether the socket can be bound to non\-local IP addresses\&. This is useful to configure sockets listening on specific IP addresses before those IP addresses are successfully configured on a network interface\&. This sets the IP_FREEBIND socket option\&. For robustness reasons it is recommended to use this option whenever you bind a socket to a specific IP address\&. Defaults to
\fBfalse\fR\&.
.RE
.PP
\fITransparent=\fR
.RS 4
Takes a boolean value\&. Controls the IP_TRANSPARENT socket option\&. Defaults to
\fBfalse\fR\&.
.RE
.PP
\fIBroadcast=\fR
.RS 4
Takes a boolean value\&. This controls the SO_BROADCAST socket option, which allows broadcast datagrams to be sent from this socket\&. Defaults to
\fBfalse\fR\&.
.RE
.PP
\fIPassCredentials=\fR
.RS 4
Takes a boolean value\&. This controls the SO_PASSCRED socket option, which allows
\fBAF_UNIX\fR
sockets to receive the credentials of the sending process in an ancillary message\&. Defaults to
\fBfalse\fR\&.
.RE
.PP
\fIPassSecurity=\fR
.RS 4
Takes a boolean value\&. This controls the SO_PASSSEC socket option, which allows
\fBAF_UNIX\fR
sockets to receive the security context of the sending process in an ancillary message\&. Defaults to
\fBfalse\fR\&.
.RE
.PP
\fITCPCongestion=\fR
.RS 4
Takes a string value\&. Controls the TCP congestion algorithm used by this socket\&. Should be one of "westwood", "veno", "cubic", "lp" or any other available algorithm supported by the IP stack\&. This setting applies only to stream sockets\&.
.RE
.PP
\fIExecStartPre=\fR, \fIExecStartPost=\fR
.RS 4
Takes one or more command lines, which are executed before or after the listening sockets/FIFOs are created and bound, respectively\&. The first token of the command line must be an absolute filename, then followed by arguments for the process\&. Multiple command lines may be specified following the same scheme as used for
\fIExecStartPre=\fR
of service unit files\&.
.RE
.PP
\fIExecStopPre=\fR, \fIExecStopPost=\fR
.RS 4
Additional commands that are executed before or after the listening sockets/FIFOs are closed and removed, respectively\&. Multiple command lines may be specified following the same scheme as used for
\fIExecStartPre=\fR
of service unit files\&.
.RE
.PP
\fITimeoutSec=\fR
.RS 4
Configures the time to wait for the commands specified in
\fIExecStartPre=\fR,
\fIExecStartPost=\fR,
\fIExecStopPre=\fR
and
\fIExecStopPost=\fR
to finish\&. If a command does not exit within the configured time, the socket will be considered failed and be shut down again\&. All commands still running will be terminated forcibly via
\fBSIGTERM\fR, and after another delay of this time with
\fBSIGKILL\fR\&. (See
\fBKillMode=\fR
in
\fBsystemd.kill\fR(5)\&.) Takes a unit\-less value in seconds, or a time span value such as "5min 20s"\&. Pass
"0"
to disable the timeout logic\&. Defaults to
\fIDefaultTimeoutStartSec=\fR
from the manager configuration file (see
\fBsystemd-system.conf\fR(5))\&.
.RE
.PP
\fIService=\fR
.RS 4
Specifies the service unit name to activate on incoming traffic\&. This setting is only allowed for sockets with
\fIAccept=no\fR\&. It defaults to the service that bears the same name as the socket (with the suffix replaced)\&. In most cases, it should not be necessary to use this option\&.
.RE
.PP
\fIRemoveOnStop=\fR
.RS 4
Takes a boolean argument\&. If enabled, any file nodes created by this socket unit are removed when it is stopped\&. This applies to AF_UNIX sockets in the file system, POSIX message queues, FIFOs, as well as any symlinks to them configured with
\fISymlinks=\fR\&. Normally, it should not be necessary to use this option, and is not recommended as services might continue to run after the socket unit has been terminated and it should still be possible to communicate with them via their file system node\&. Defaults to off\&.
.RE
.PP
\fISymlinks=\fR
.RS 4
Takes a list of file system paths\&. The specified paths will be created as symlinks to the AF_UNIX socket path or FIFO path of this socket unit\&. If this setting is used, only one AF_UNIX socket in the file system or one FIFO may be configured for the socket unit\&. Use this option to manage one or more symlinked alias names for a socket, binding their lifecycle together\&. Defaults to the empty list\&.
.RE
.PP
Check
\fBsystemd.exec\fR(5)
and
\fBsystemd.kill\fR(5)
for more settings\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBsystemd.unit\fR(5),
\fBsystemd.exec\fR(5),
\fBsystemd.kill\fR(5),
\fBsystemd.resource-control\fR(5),
\fBsystemd.service\fR(5),
\fBsystemd.directives\fR(7)
.PP
For more extensive descriptions see the "systemd for Developers" series:
\m[blue]\fBSocket Activation\fR\m[]\&\s-2\u[3]\d\s+2,
\m[blue]\fBSocket Activation, part II\fR\m[]\&\s-2\u[4]\d\s+2,
\m[blue]\fBConverting inetd Services\fR\m[]\&\s-2\u[5]\d\s+2,
\m[blue]\fBSocket Activated Internet Services and OS Containers\fR\m[]\&\s-2\u[6]\d\s+2\&.
.SH "NOTES"
.IP " 1." 4
TCP Keepalive HOWTO
.RS 4
\%http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/
.RE
.IP " 2." 4
Smack.txt
.RS 4
\%https://www.kernel.org/doc/Documentation/security/Smack.txt
.RE
.IP " 3." 4
Socket Activation
.RS 4
\%http://0pointer.de/blog/projects/socket-activation.html
.RE
.IP " 4." 4
Socket Activation, part II
.RS 4
\%http://0pointer.de/blog/projects/socket-activation2.html
.RE
.IP " 5." 4
Converting inetd Services
.RS 4
\%http://0pointer.de/blog/projects/inetd.html
.RE
.IP " 6." 4
Socket Activated Internet Services and OS Containers
.RS 4
\%http://0pointer.de/blog/projects/socket-activated-containers.html
.RE
