'\" t
.TH "SYSTEMD\-MODULES\-LOAD\&.SERVICE" "8" "" "systemd 220" "systemd-modules-load.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-modules-load.service, systemd-modules-load \- Load kernel modules at boot
.SH "SYNOPSIS"
.PP
systemd\-modules\-load\&.service
.PP
/usr/lib/systemd/systemd\-modules\-load
.SH "DESCRIPTION"
.PP
systemd\-modules\-load\&.service
is an early\-boot service that loads kernel modules based on static configuration\&.
.PP
See
\fBmodules-load.d\fR(5)
for information about the configuration of this service\&.
.SH "KERNEL COMMAND LINE"
.PP
systemd\-modules\-load\&.service
understands the following kernel command line parameters:
.PP
\fImodules\-load=\fR, \fIrd\&.modules\-load=\fR
.RS 4
Takes a comma\-separated list of kernel modules to statically load during early boot\&. The option prefixed with
"rd\&."
is read by the initial RAM disk only\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBmodules-load.d\fR(5),
