'\" t
.TH "SYSTEMD\-NETWORKD\-WAIT\-ONLINE\&.SERVICE" "8" "" "systemd 221" "systemd-networkd.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-networkd-wait-online.service, systemd-networkd-wait-online \- Wait for network to come online
.SH "SYNOPSIS"
.PP
systemd\-networkd\-wait\-online\&.service
.PP
/usr/lib/systemd/systemd\-networkd\-wait\-online
.SH "DESCRIPTION"
.PP
\fBsystemd\-networkd\-wait\-online\fR
is a one\-shot system service that waits for the network to be configured\&. By default, it will wait for all links it is aware of and which are managed by
\fBsystemd-networkd.service\fR(8)
to be fully configured or failed, and for at least one link to gain a carrier\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-i\fR, \fB\-\-interface=\fR
.RS 4
Network interface to wait for before deciding if the system is online\&. This is useful when a system has several interfaces which will be configured, but a particular one is necessary to access some network resources\&. This option may be used more than once to wait for multiple network interfaces\&.
.RE
.PP
\fB\-\-ignore=\fR
.RS 4
Network interfaces to be ignored when deciding if the system is online\&. By default only the loopback interface is ignored\&. This option may be used more than once to ignore multiple network interfaces\&.
.RE
.PP
\fB\-\-timeout=\fR
.RS 4
Fail the service if the network is not online by the time the timeout elapses\&. A timeout of 0 disables the timeout\&. Defaults to 120 seconds\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-networkd.service\fR(8)
