'\" t
.TH "SYSTEMD\&.SCOPE" "5" "" "systemd 220" "systemd.scope"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.scope \- Scope unit configuration
.SH "SYNOPSIS"
.PP
\fIscope\fR\&.scope
.SH "DESCRIPTION"
.PP
Scope units are not configured via unit configuration files, but are only created programmatically using the bus interfaces of systemd\&. They are named similar to filenames\&. A unit whose name ends in
"\&.scope"
refers to a scope unit\&. Scopes units manage a set of system processes\&. Unlike service units, scope units manage externally created processes, and do not fork off processes on its own\&.
.PP
The main purpose of scope units is grouping worker processes of a system service for organization and for managing resources\&.
.PP
\fBsystemd\-run \fR\fB\fB\-\-scope\fR\fR
may be used to easily launch a command in a new scope unit from the command line\&.
.PP
See the
\m[blue]\fBNew Control Group Interfaces\fR\m[]\&\s-2\u[1]\d\s+2
for an introduction on how to make use of scope units from programs\&.
.PP
Unless
\fIDefaultDependencies=false\fR
is used, scope units will implicitly have dependencies of type
\fIConflicts=\fR
and
\fIBefore=\fR
on
shutdown\&.target\&. These ensure that scope units are removed prior to system shutdown\&. Only scope units involved with early boot or late system shutdown should disable this option\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-run\fR(1),
\fBsystemd.unit\fR(5),
\fBsystemd.resource-control\fR(5),
\fBsystemd.service\fR(5),
\fBsystemd.directives\fR(7)\&.
.SH "NOTES"
.IP " 1." 4
New Control Group Interfaces
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/
.RE
