'\" t
.TH "SYSTEMD\-MACHINE\-ID\-COMMIT\&.SERVICE" "8" "" "systemd 221" "systemd-machine-id-commit.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-machine-id-commit.service \- Commit transient machine\-id to disk
.SH "SYNOPSIS"
.PP
systemd\-machine\-id\-commit\&.service
.PP
/usr/lib/systemd/systemd\-machine\-id\-commit
.SH "DESCRIPTION"
.PP
systemd\-machine\-id\-commit\&.service
is a service responsible for committing any transient
/etc/machine\-id
file to a writable file system\&. See
\fBmachine-id\fR(5)
for more information about this file\&.
.PP
This service is started shortly after
local\-fs\&.target
if
/etc/machine\-id
is an independent mount point (probably a tmpfs one) and /etc is writable\&.
\fBsystemd\-machine\-id\-commit\fR
will then write current machine ID to disk and unmount the transient
/etc/machine\-id
file in a race\-free manner to ensure that file is always valid for other processes\&.
.PP
Note that the traditional way to initialize the machine ID in
/etc/machine\-id
is to use
\fBsystemd\-machine\-id\-setup\fR
by system installer tools\&. You can also use
\fBsystemd-firstboot\fR(1)
to initialize the machine ID on mounted (but not booted) system images\&. The main use case for that service is
/etc/machine\-id
being an empty file at boot and initrd chaining to systemd giving it a read only file system that will be turned read\-write later during the boot process\&.
.PP
There is no consequence if that service fails other than a newer machine\-id will be generated during next system boot\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-machine-id-commit\fR(1),
\fBsystemd-machine-id-setup\fR(1),
\fBmachine-id\fR(5),
\fBsystemd-firstboot\fR(1)
