'\" t
.TH "SYSTEMD\-READAHEAD\-REPLAY\&.SERVICE" "8" "" "systemd 215" "systemd-readahead-replay.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-readahead-replay.service, systemd-readahead-collect.service, systemd-readahead-done.service, systemd-readahead-done.timer, systemd-readahead \- Disk read ahead logic
.SH "SYNOPSIS"
.PP
systemd\-readahead\-replay\&.service
.PP
systemd\-readahead\-collect\&.service
.PP
systemd\-readahead\-done\&.service
.PP
systemd\-readahead\-done\&.timer
.HP \w'\fB/usr/lib/systemd/systemd\-readahead/systemd\-readahead\fR\ 'u
\fB/usr/lib/systemd/systemd\-readahead/systemd\-readahead\fR [OPTIONS...] COMMAND [DIRECTORY\ |\ FILE]
.SH "DESCRIPTION"
.PP
systemd\-readahead\-collect\&.service
is a service that collects disk usage patterns at boot time\&.
systemd\-readahead\-replay\&.service
is a service that replays this access data collected at the subsequent boot\&. Since disks tend to be magnitudes slower than RAM, this is intended to improve boot speeds by pre\-loading early at boot all data on disk that is known to be read for the complete boot process\&.
.PP
systemd\-readahead\-done\&.service
is executed a short while after boot completed and signals
systemd\-readahead\-collect\&.service
to end data collection\&. On this signal, this service will then sort the collected disk accesses and store information about them in
/\&.readahead\&.
.PP
Normally, both
systemd\-readahead\-collect\&.service
and
systemd\-readahead\-replay\&.service
are activated at boot so that access patterns from the preceding boot are replayed and new data collected for the subsequent boot\&. However, on read\-only media where the collected data cannot be stored, it might be a good idea to disable
systemd\-readahead\-collect\&.service\&.
.PP
On rotating media, when replaying disk accesses at early boot,
systemd\-readahead\-replay\&.service
will order read requests by their location on disk\&. On non\-rotating media, they will be ordered by their original access timestamp\&. If the file system supports it,
systemd\-readahead\-collect\&.service
will also defragment and rearrange files on disk to optimize subsequent boot times\&.
.SH "OPTIONS"
.PP
systemd\-readahead
understands the following options:
.PP
\fB\-\-files\-max=\fR
.RS 4
Maximum number of files to read ahead\&. Only valid for thes
\fBcollect\fR
command\&.
.RE
.PP
\fB\-\-file\-size\-max=\fR
.RS 4
Maximum size of files in bytes to read ahead\&. Only valid for the
\fBcollect\fR
and
\fBreplay\fR
commands\&.
.RE
.PP
\fB\-\-timeout=\fR
.RS 4
Maximum time in microseconds to spend collecting data\&. Only valid for the
\fBcollect\fR
command\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "COMMANDS"
.PP
The following commands are understood by
systemd\-readahead:
.PP
\fBcollect [\fR\fB\fIDIRECTORY\fR\fR\fB]\fR
.RS 4
Collect read\-ahead data on early boot\&. When terminating, it will write out a pack file to the indicated directory containing the read\-ahead data\&.
.RE
.PP
\fBreplay [\fR\fB\fIDIRECTORY\fR\fR\fB]\fR
.RS 4
Perform read\-ahead on the specified directory tree\&.
.RE
.PP
\fBanalyze [\fR\fB\fIFILE\fR\fR\fB]\fR
.RS 4
Dumps the content of the read\-ahead pack file to the terminal\&. For each file, the output lists approximately how much will be read ahead by the
\fBreplay\fR
command\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1)
