'\" t
.TH "SYSTEMD\&.INDEX" "7" "" "systemd 215" "systemd.index"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.index \- List all manpages from the systemd project
.SH "B"
.PP
\fBbinfmt.d\fR(5)
\-\- Configure additional binary formats for executables at boot
.br
\fBbootchart.conf\fR(5)
\-\- Boot performance analysis graphing tool configuration file
.br
\fBbootctl\fR(1)
\-\- Control the firmware and boot manager settings
.br
\fBbootup\fR(7)
\-\- System bootup process
.br
\fBbusctl\fR(1)
\-\- Introspect the bus
.br

.SH "C"
.PP
\fBcoredump.conf\fR(5)
\-\- Coredump storage configuration file
.br
\fBcoredumpctl\fR(1)
\-\- Retrieve coredumps from the journal
.br
\fBcrypttab\fR(5)
\-\- Configuration for encrypted block devices
.br

.SH "D"
.PP
\fBdaemon\fR(7)
\-\- Writing and packaging system daemons
.br

.SH "F"
.PP
\fBfile-hierarchy\fR(7)
\-\- File system hierarchy overview
.br

.SH "H"
.PP
\fBhalt\fR(8)
\-\- Halt, power\-off or reboot the machine
.br
\fBhostname\fR(5)
\-\- Local hostname configuration file
.br
\fBhostnamectl\fR(1)
\-\- Control the system hostname
.br

.SH "I"
.PP
\fBinit\fR(1)
\-\- systemd system and service manager
.br

.SH "J"
.PP
\fBjournalctl\fR(1)
\-\- Query the systemd journal
.br
\fBjournald.conf\fR(5)
\-\- Journal service configuration file
.br

.SH "K"
.PP
\fBkernel-command-line\fR(7)
\-\- Kernel command line parameters
.br
\fBkernel-install\fR(8)
\-\- Add and remove kernel and initramfs images to and from /boot
.br

.SH "L"
.PP
\fBlocale.conf\fR(5)
\-\- Configuration file for locale settings
.br
\fBlocalectl\fR(1)
\-\- Control the system locale and keyboard layout settings
.br
\fBlocaltime\fR(5)
\-\- Local timezone configuration file
.br
\fBloginctl\fR(1)
\-\- Control the systemd login manager
.br
\fBlogind.conf\fR(5)
\-\- Login manager configuration file
.br

.SH "M"
.PP
\fBmachine-id\fR(5)
\-\- Local machine ID configuration file
.br
\fBmachine-info\fR(5)
\-\- Local machine information file
.br
\fBmachinectl\fR(1)
\-\- Control the systemd machine manager
.br
\fBmodules-load.d\fR(5)
\-\- Configure kernel modules to load at boot
.br

.SH "N"
.PP
\fBnss-myhostname\fR(8)
\-\- Provide hostname resolution for the locally configured system hostname\&.
.br

.SH "O"
.PP
\fBos-release\fR(5)
\-\- Operating system identification
.br

.SH "P"
.PP
\fBpam_systemd\fR(8)
\-\- Register user sessions in the systemd login manager
.br
\fBpoweroff\fR(8)
\-\- Halt, power\-off or reboot the machine
.br

.SH "R"
.PP
\fBreboot\fR(8)
\-\- Halt, power\-off or reboot the machine
.br
\fBresolved.conf\fR(5)
\-\- Network Name Resolution configuration file
.br
\fBrunlevel\fR(8)
\-\- Print previous and current SysV runlevel
.br

.SH "S"
.PP
\fBsd-daemon\fR(3)
\-\- APIs for new\-style daemons
.br
\fBsd-id128\fR(3)
\-\- APIs for processing 128\-bit IDs
.br
\fBsd-journal\fR(3)
\-\- APIs for submitting and querying log entries to and from the journal
.br
\fBsd-login\fR(3)
\-\- APIs for tracking logins
.br
\fBsd-readahead\fR(3)
\-\- Reference implementation of APIs for controlling boot\-time read\-ahead
.br
\fBSD_ALERT\fR(3)
\-\- APIs for new\-style daemons
.br
\fBsd_booted\fR(3)
\-\- Test whether the system is running the systemd init system
.br
\fBsd_bus_creds_get_audit_login_uid\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_audit_session_id\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_cgroup\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_cmdline\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_comm\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_exe\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_gid\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_mask\fR(3)
\-\- Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_get_owner_uid\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_pid\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_pid_starttime\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_selinux_context\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_session\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_slice\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_tid\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_tid_comm\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_uid\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_unique_name\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_unit\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_user_unit\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_get_well_known_names\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_bounding_cap\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_effective_cap\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_inheritable_cap\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_has_permitted_cap\fR(3)
\-\- Retrieve fields from a credentials object
.br
\fBsd_bus_creds_new_from_pid\fR(3)
\-\- Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_ref\fR(3)
\-\- Retrieve credentials object for the specified PID
.br
\fBsd_bus_creds_unref\fR(3)
\-\- Retrieve credentials object for the specified PID
.br
\fBsd_bus_default_system\fR(3)
\-\- Open a connection to the system or user bus
.br
\fBsd_bus_default_user\fR(3)
\-\- Open a connection to the system or user bus
.br
\fBsd_bus_error\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_copy\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_free\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_get_errno\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_has_name\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_is_set\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_set\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_set_const\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_set_errno\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_error_set_errnof\fR(3)
\-\- sd\-bus error handling
.br
\fBsd_bus_message_append\fR(3)
\-\- Attach parts of message based on a format string
.br
\fBsd_bus_message_append_array\fR(3)
\-\- Attach an array of items to a message
.br
\fBsd_bus_message_append_array_iovec\fR(3)
\-\- Attach an array of items to a message
.br
\fBsd_bus_message_append_array_memfd\fR(3)
\-\- Attach an array of items to a message
.br
\fBsd_bus_message_append_array_space\fR(3)
\-\- Attach an array of items to a message
.br
\fBsd_bus_message_append_basic\fR(3)
\-\- Attach a single part to a message
.br
\fBsd_bus_message_append_string_iovec\fR(3)
\-\- Attach a string to a message
.br
\fBsd_bus_message_append_string_memfd\fR(3)
\-\- Attach a string to a message
.br
\fBsd_bus_message_append_string_space\fR(3)
\-\- Attach a string to a message
.br
\fBsd_bus_message_append_strv\fR(3)
\-\- Attach an array of strings to a message
.br
\fBsd_bus_message_get_cookie\fR(3)
\-\- Returns the transaction cookie of a message
.br
\fBsd_bus_message_get_monotonic_usec\fR(3)
\-\- Retrieve the sender timestamps and sequence number of a message
.br
\fBsd_bus_message_get_realtime_usec\fR(3)
\-\- Retrieve the sender timestamps and sequence number of a message
.br
\fBsd_bus_message_get_reply_cookie\fR(3)
\-\- Returns the transaction cookie of a message
.br
\fBsd_bus_message_get_seqnum\fR(3)
\-\- Retrieve the sender timestamps and sequence number of a message
.br
\fBsd_bus_negotiate_creds\fR(3)
\-\- Control feature negotiation on bus connections
.br
\fBsd_bus_negotiate_fds\fR(3)
\-\- Control feature negotiation on bus connections
.br
\fBsd_bus_negotiate_timestamps\fR(3)
\-\- Control feature negotiation on bus connections
.br
\fBsd_bus_new\fR(3)
\-\- Create a new bus object and create or destroy references to it
.br
\fBsd_bus_open_system\fR(3)
\-\- Open a connection to the system or user bus
.br
\fBsd_bus_open_system_container\fR(3)
\-\- Open a connection to the system or user bus
.br
\fBsd_bus_open_system_remote\fR(3)
\-\- Open a connection to the system or user bus
.br
\fBsd_bus_open_user\fR(3)
\-\- Open a connection to the system or user bus
.br
\fBsd_bus_path_decode\fR(3)
\-\- Convert an external identifier into an object path and back
.br
\fBsd_bus_path_encode\fR(3)
\-\- Convert an external identifier into an object path and back
.br
\fBsd_bus_ref\fR(3)
\-\- Create a new bus object and create or destroy references to it
.br
\fBsd_bus_release_name\fR(3)
\-\- Request or release a well\-known name on a bus
.br
\fBsd_bus_request_name\fR(3)
\-\- Request or release a well\-known name on a bus
.br
\fBsd_bus_unref\fR(3)
\-\- Create a new bus object and create or destroy references to it
.br
\fBSD_CRIT\fR(3)
\-\- APIs for new\-style daemons
.br
\fBSD_DEBUG\fR(3)
\-\- APIs for new\-style daemons
.br
\fBSD_EMERG\fR(3)
\-\- APIs for new\-style daemons
.br
\fBSD_ERR\fR(3)
\-\- APIs for new\-style daemons
.br
\fBsd_event_add_time\fR(3)
\-\- Add a timer event source to an event loop
.br
\fBsd_event_default\fR(3)
\-\- Acquire and release an event loop object
.br
\fBsd_event_new\fR(3)
\-\- Acquire and release an event loop object
.br
\fBsd_event_ref\fR(3)
\-\- Acquire and release an event loop object
.br
\fBsd_event_source_get_time\fR(3)
\-\- Add a timer event source to an event loop
.br
\fBsd_event_source_get_time_accuracy\fR(3)
\-\- Add a timer event source to an event loop
.br
\fBsd_event_source_get_time_clock\fR(3)
\-\- Add a timer event source to an event loop
.br
\fBsd_event_source_set_time\fR(3)
\-\- Add a timer event source to an event loop
.br
\fBsd_event_source_set_time_accuracy\fR(3)
\-\- Add a timer event source to an event loop
.br
\fBsd_event_unref\fR(3)
\-\- Acquire and release an event loop object
.br
\fBsd_get_machine_names\fR(3)
\-\- Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBsd_get_seats\fR(3)
\-\- Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBsd_get_sessions\fR(3)
\-\- Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBsd_get_uids\fR(3)
\-\- Determine available seats, sessions, logged in users and virtual machines/containers
.br
\fBSD_ID128_CONST_STR\fR(3)
\-\- APIs for processing 128\-bit IDs
.br
\fBsd_id128_equal\fR(3)
\-\- APIs for processing 128\-bit IDs
.br
\fBSD_ID128_FORMAT_STR\fR(3)
\-\- APIs for processing 128\-bit IDs
.br
\fBSD_ID128_FORMAT_VAL\fR(3)
\-\- APIs for processing 128\-bit IDs
.br
\fBsd_id128_from_string\fR(3)
\-\- Format or parse 128\-bit IDs as strings
.br
\fBsd_id128_get_boot\fR(3)
\-\- Retrieve 128\-bit IDs
.br
\fBsd_id128_get_machine\fR(3)
\-\- Retrieve 128\-bit IDs
.br
\fBSD_ID128_MAKE\fR(3)
\-\- APIs for processing 128\-bit IDs
.br
\fBsd_id128_randomize\fR(3)
\-\- Generate 128\-bit IDs
.br
\fBsd_id128_t\fR(3)
\-\- APIs for processing 128\-bit IDs
.br
\fBsd_id128_to_string\fR(3)
\-\- Format or parse 128\-bit IDs as strings
.br
\fBSD_INFO\fR(3)
\-\- APIs for new\-style daemons
.br
\fBsd_is_fifo\fR(3)
\-\- Check the type of a file descriptor
.br
\fBsd_is_mq\fR(3)
\-\- Check the type of a file descriptor
.br
\fBsd_is_socket\fR(3)
\-\- Check the type of a file descriptor
.br
\fBsd_is_socket_inet\fR(3)
\-\- Check the type of a file descriptor
.br
\fBsd_is_socket_unix\fR(3)
\-\- Check the type of a file descriptor
.br
\fBsd_is_special\fR(3)
\-\- Check the type of a file descriptor
.br
\fBsd_journal\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_add_conjunction\fR(3)
\-\- Add or remove entry matches
.br
\fBsd_journal_add_disjunction\fR(3)
\-\- Add or remove entry matches
.br
\fBsd_journal_add_match\fR(3)
\-\- Add or remove entry matches
.br
\fBSD_JOURNAL_APPEND\fR(3)
\-\- Journal change notification interface
.br
\fBsd_journal_close\fR(3)
\-\- Open the system journal for reading
.br
\fBSD_JOURNAL_CURRENT_USER\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_enumerate_data\fR(3)
\-\- Read data fields from the current journal entry
.br
\fBsd_journal_enumerate_unique\fR(3)
\-\- Read unique data fields from the journal
.br
\fBsd_journal_flush_matches\fR(3)
\-\- Add or remove entry matches
.br
\fBSD_JOURNAL_FOREACH\fR(3)
\-\- Advance or set back the read pointer in the journal
.br
\fBSD_JOURNAL_FOREACH_BACKWARDS\fR(3)
\-\- Advance or set back the read pointer in the journal
.br
\fBSD_JOURNAL_FOREACH_DATA\fR(3)
\-\- Read data fields from the current journal entry
.br
\fBSD_JOURNAL_FOREACH_UNIQUE\fR(3)
\-\- Read unique data fields from the journal
.br
\fBsd_journal_get_catalog\fR(3)
\-\- Retrieve message catalog entry
.br
\fBsd_journal_get_catalog_for_message_id\fR(3)
\-\- Retrieve message catalog entry
.br
\fBsd_journal_get_cursor\fR(3)
\-\- Get cursor string for or test cursor string against the current journal entry
.br
\fBsd_journal_get_cutoff_monotonic_usec\fR(3)
\-\- Read cut\-off timestamps from the current journal entry
.br
\fBsd_journal_get_cutoff_realtime_usec\fR(3)
\-\- Read cut\-off timestamps from the current journal entry
.br
\fBsd_journal_get_data\fR(3)
\-\- Read data fields from the current journal entry
.br
\fBsd_journal_get_data_threshold\fR(3)
\-\- Read data fields from the current journal entry
.br
\fBsd_journal_get_events\fR(3)
\-\- Journal change notification interface
.br
\fBsd_journal_get_fd\fR(3)
\-\- Journal change notification interface
.br
\fBsd_journal_get_monotonic_usec\fR(3)
\-\- Read timestamps from the current journal entry
.br
\fBsd_journal_get_realtime_usec\fR(3)
\-\- Read timestamps from the current journal entry
.br
\fBsd_journal_get_timeout\fR(3)
\-\- Journal change notification interface
.br
\fBsd_journal_get_usage\fR(3)
\-\- Journal disk usage
.br
\fBSD_JOURNAL_INVALIDATE\fR(3)
\-\- Journal change notification interface
.br
\fBSD_JOURNAL_LOCAL_ONLY\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_next\fR(3)
\-\- Advance or set back the read pointer in the journal
.br
\fBsd_journal_next_skip\fR(3)
\-\- Advance or set back the read pointer in the journal
.br
\fBSD_JOURNAL_NOP\fR(3)
\-\- Journal change notification interface
.br
\fBsd_journal_open\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_open_container\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_open_directory\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_open_files\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_perror\fR(3)
\-\- Submit log entries to the journal
.br
\fBsd_journal_previous\fR(3)
\-\- Advance or set back the read pointer in the journal
.br
\fBsd_journal_previous_skip\fR(3)
\-\- Advance or set back the read pointer in the journal
.br
\fBsd_journal_print\fR(3)
\-\- Submit log entries to the journal
.br
\fBsd_journal_printv\fR(3)
\-\- Submit log entries to the journal
.br
\fBsd_journal_process\fR(3)
\-\- Journal change notification interface
.br
\fBsd_journal_query_unique\fR(3)
\-\- Read unique data fields from the journal
.br
\fBsd_journal_reliable_fd\fR(3)
\-\- Journal change notification interface
.br
\fBsd_journal_restart_data\fR(3)
\-\- Read data fields from the current journal entry
.br
\fBsd_journal_restart_unique\fR(3)
\-\- Read unique data fields from the journal
.br
\fBSD_JOURNAL_RUNTIME_ONLY\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_seek_cursor\fR(3)
\-\- Seek to a position in the journal
.br
\fBsd_journal_seek_head\fR(3)
\-\- Seek to a position in the journal
.br
\fBsd_journal_seek_monotonic_usec\fR(3)
\-\- Seek to a position in the journal
.br
\fBsd_journal_seek_realtime_usec\fR(3)
\-\- Seek to a position in the journal
.br
\fBsd_journal_seek_tail\fR(3)
\-\- Seek to a position in the journal
.br
\fBsd_journal_send\fR(3)
\-\- Submit log entries to the journal
.br
\fBsd_journal_sendv\fR(3)
\-\- Submit log entries to the journal
.br
\fBsd_journal_set_data_threshold\fR(3)
\-\- Read data fields from the current journal entry
.br
\fBsd_journal_stream_fd\fR(3)
\-\- Create log stream file descriptor to the journal
.br
\fBSD_JOURNAL_SUPPRESS_LOCATION\fR(3)
\-\- Submit log entries to the journal
.br
\fBSD_JOURNAL_SYSTEM\fR(3)
\-\- Open the system journal for reading
.br
\fBsd_journal_test_cursor\fR(3)
\-\- Get cursor string for or test cursor string against the current journal entry
.br
\fBsd_journal_wait\fR(3)
\-\- Journal change notification interface
.br
\fBsd_listen_fds\fR(3)
\-\- Check for file descriptors passed by the system manager
.br
\fBSD_LISTEN_FDS_START\fR(3)
\-\- Check for file descriptors passed by the system manager
.br
\fBsd_login_monitor\fR(3)
\-\- Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_flush\fR(3)
\-\- Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_get_events\fR(3)
\-\- Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_get_fd\fR(3)
\-\- Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_get_timeout\fR(3)
\-\- Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_new\fR(3)
\-\- Monitor login sessions, seats, users and virtual machines/containers
.br
\fBsd_login_monitor_unref\fR(3)
\-\- Monitor login sessions, seats, users and virtual machines/containers
.br
\fBSD_NOTICE\fR(3)
\-\- APIs for new\-style daemons
.br
\fBsd_notify\fR(3)
\-\- Notify service manager about start\-up completion and other daemon status changes
.br
\fBsd_notifyf\fR(3)
\-\- Notify service manager about start\-up completion and other daemon status changes
.br
\fBsd_peer_get_machine_name\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_peer_get_owner_uid\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_peer_get_session\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_peer_get_slice\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_peer_get_unit\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_peer_get_user_unit\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_pid_get_machine_name\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_pid_get_owner_uid\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_pid_get_session\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_pid_get_slice\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_pid_get_unit\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_pid_get_user_unit\fR(3)
\-\- Determine session, service, owner of a session, container/VM or slice of a specific PID or socket peer
.br
\fBsd_readahead\fR(3)
\-\- Control ongoing disk boot\-time read\-ahead operations
.br
\fBsd_seat_can_graphical\fR(3)
\-\- Determine state of a specific seat
.br
\fBsd_seat_can_multi_session\fR(3)
\-\- Determine state of a specific seat
.br
\fBsd_seat_can_tty\fR(3)
\-\- Determine state of a specific seat
.br
\fBsd_seat_get_active\fR(3)
\-\- Determine state of a specific seat
.br
\fBsd_seat_get_sessions\fR(3)
\-\- Determine state of a specific seat
.br
\fBsd_session_get_class\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_display\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_remote_host\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_remote_user\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_seat\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_service\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_state\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_tty\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_type\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_uid\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_get_vt\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_is_active\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_session_is_remote\fR(3)
\-\- Determine state of a specific session
.br
\fBsd_uid_get_display\fR(3)
\-\- Determine login state of a specific Unix user ID
.br
\fBsd_uid_get_seats\fR(3)
\-\- Determine login state of a specific Unix user ID
.br
\fBsd_uid_get_sessions\fR(3)
\-\- Determine login state of a specific Unix user ID
.br
\fBsd_uid_get_state\fR(3)
\-\- Determine login state of a specific Unix user ID
.br
\fBsd_uid_is_on_seat\fR(3)
\-\- Determine login state of a specific Unix user ID
.br
\fBSD_WARNING\fR(3)
\-\- APIs for new\-style daemons
.br
\fBsd_watchdog_enabled\fR(3)
\-\- Check whether the service manager expects watchdog keep\-alive notifications from a service
.br
\fBshutdown\fR(8)
\-\- Halt, power\-off or reboot the machine
.br
\fBsysctl.d\fR(5)
\-\- Configure kernel parameters at boot
.br
\fBsystemctl\fR(1)
\-\- Control the systemd system and service manager
.br
\fBsystemd\fR(1)
\-\- systemd system and service manager
.br
\fBsystemd-activate\fR(8)
\-\- Test socket activation of daemons
.br
\fBsystemd-analyze\fR(1)
\-\- Analyze system boot\-up performance
.br
\fBsystemd-ask-password\fR(1)
\-\- Query the user for a system password
.br
\fBsystemd-ask-password-console.path\fR(8)
\-\- Query the user for system passwords on the console and via wall
.br
\fBsystemd-ask-password-console.service\fR(8)
\-\- Query the user for system passwords on the console and via wall
.br
\fBsystemd-ask-password-wall.path\fR(8)
\-\- Query the user for system passwords on the console and via wall
.br
\fBsystemd-ask-password-wall.service\fR(8)
\-\- Query the user for system passwords on the console and via wall
.br
\fBsystemd-backlight\fR(8)
\-\- Load and save the display backlight brightness at boot and shutdown
.br
\fBsystemd-backlight@.service\fR(8)
\-\- Load and save the display backlight brightness at boot and shutdown
.br
\fBsystemd-binfmt\fR(8)
\-\- Configure additional binary formats for executables at boot
.br
\fBsystemd-binfmt.service\fR(8)
\-\- Configure additional binary formats for executables at boot
.br
\fBsystemd-bootchart\fR(1)
\-\- Boot performance graphing tool
.br
\fBsystemd-bus-proxyd\fR(8)
\-\- Connect STDIO or a socket to a given bus address
.br
\fBsystemd-bus-proxyd.socket\fR(8)
\-\- Proxy classic D\-Bus clients to kdbus
.br
\fBsystemd-bus-proxyd@.service\fR(8)
\-\- Proxy classic D\-Bus clients to kdbus
.br
\fBsystemd-cat\fR(1)
\-\- Connect a pipeline or program\*(Aqs output with the journal
.br
\fBsystemd-cgls\fR(1)
\-\- Recursively show control group contents
.br
\fBsystemd-cgtop\fR(1)
\-\- Show top control groups by their resource usage
.br
\fBsystemd-cryptsetup\fR(8)
\-\- Full disk decryption logic
.br
\fBsystemd-cryptsetup-generator\fR(8)
\-\- Unit generator for
.br
\fBsystemd-cryptsetup@.service\fR(8)
\-\- Full disk decryption logic
.br
\fBsystemd-debug-generator\fR(8)
\-\- Generator for enabling a runtime debug shell and masking specific units at boot
.br
\fBsystemd-delta\fR(1)
\-\- Find overridden configuration files
.br
\fBsystemd-detect-virt\fR(1)
\-\- Detect execution in a virtualized environment
.br
\fBsystemd-efi-boot-generator\fR(8)
\-\- Generator for automatically mounting the EFI System Partition used by the current boot to
.br
\fBsystemd-fsck\fR(8)
\-\- File system checker logic
.br
\fBsystemd-fsck-root.service\fR(8)
\-\- File system checker logic
.br
\fBsystemd-fsck@.service\fR(8)
\-\- File system checker logic
.br
\fBsystemd-fstab-generator\fR(8)
\-\- Unit generator for /etc/fstab
.br
\fBsystemd-getty-generator\fR(8)
\-\- Generator for enabling getty instances on the console
.br
\fBsystemd-gpt-auto-generator\fR(8)
\-\- Generator for automatically discovering and mounting root,
.br
\fBsystemd-halt.service\fR(8)
\-\- System shutdown logic
.br
\fBsystemd-hibernate.service\fR(8)
\-\- System sleep state logic
.br
\fBsystemd-hostnamed\fR(8)
\-\- Host name bus mechanism
.br
\fBsystemd-hostnamed.service\fR(8)
\-\- Host name bus mechanism
.br
\fBsystemd-hybrid-sleep.service\fR(8)
\-\- System sleep state logic
.br
\fBsystemd-inhibit\fR(1)
\-\- Execute a program with an inhibition lock taken
.br
\fBsystemd-initctl\fR(8)
\-\- /dev/initctl compatibility
.br
\fBsystemd-initctl.service\fR(8)
\-\- /dev/initctl compatibility
.br
\fBsystemd-initctl.socket\fR(8)
\-\- /dev/initctl compatibility
.br
\fBsystemd-journal-gatewayd\fR(8)
\-\- HTTP server for journal events
.br
\fBsystemd-journal-gatewayd.service\fR(8)
\-\- HTTP server for journal events
.br
\fBsystemd-journal-gatewayd.socket\fR(8)
\-\- HTTP server for journal events
.br
\fBsystemd-journal-remote\fR(8)
\-\- Stream journal messages over the network
.br
\fBsystemd-journald\fR(8)
\-\- Journal service
.br
\fBsystemd-journald-dev-log.socket\fR(8)
\-\- Journal service
.br
\fBsystemd-journald.service\fR(8)
\-\- Journal service
.br
\fBsystemd-journald.socket\fR(8)
\-\- Journal service
.br
\fBsystemd-kexec.service\fR(8)
\-\- System shutdown logic
.br
\fBsystemd-localed\fR(8)
\-\- Locale bus mechanism
.br
\fBsystemd-localed.service\fR(8)
\-\- Locale bus mechanism
.br
\fBsystemd-logind\fR(8)
\-\- Login manager
.br
\fBsystemd-logind.service\fR(8)
\-\- Login manager
.br
\fBsystemd-machine-id-setup\fR(1)
\-\- Initialize the machine ID in /etc/machine\-id
.br
\fBsystemd-machined\fR(8)
\-\- Virtual machine and container registration manager
.br
\fBsystemd-machined.service\fR(8)
\-\- Virtual machine and container registration manager
.br
\fBsystemd-modules-load\fR(8)
\-\- Configure kernel modules to load at boot
.br
\fBsystemd-modules-load.service\fR(8)
\-\- Configure kernel modules to load at boot
.br
\fBsystemd-networkd\fR(8)
\-\- Network manager
.br
\fBsystemd-networkd-wait-online\fR(8)
\-\- Wait for network to come online
.br
\fBsystemd-networkd-wait-online.service\fR(8)
\-\- Wait for network to come online
.br
\fBsystemd-networkd.service\fR(8)
\-\- Network manager
.br
\fBsystemd-notify\fR(1)
\-\- Notify service manager about start\-up completion and other daemon status changes
.br
\fBsystemd-nspawn\fR(1)
\-\- Spawn a namespace container for debugging, testing and building
.br
\fBsystemd-path\fR(1)
\-\- List and query system and user paths
.br
\fBsystemd-poweroff.service\fR(8)
\-\- System shutdown logic
.br
\fBsystemd-quotacheck\fR(8)
\-\- File system quota checker logic
.br
\fBsystemd-quotacheck.service\fR(8)
\-\- File system quota checker logic
.br
\fBsystemd-random-seed\fR(8)
\-\- Load and save the system random seed at boot and shutdown
.br
\fBsystemd-random-seed.service\fR(8)
\-\- Load and save the system random seed at boot and shutdown
.br
\fBsystemd-readahead\fR(8)
\-\- Disk read ahead logic
.br
\fBsystemd-readahead-collect.service\fR(8)
\-\- Disk read ahead logic
.br
\fBsystemd-readahead-done.service\fR(8)
\-\- Disk read ahead logic
.br
\fBsystemd-readahead-done.timer\fR(8)
\-\- Disk read ahead logic
.br
\fBsystemd-readahead-replay.service\fR(8)
\-\- Disk read ahead logic
.br
\fBsystemd-reboot.service\fR(8)
\-\- System shutdown logic
.br
\fBsystemd-remount-fs\fR(8)
\-\- Remount root and kernel file systems
.br
\fBsystemd-remount-fs.service\fR(8)
\-\- Remount root and kernel file systems
.br
\fBsystemd-resolved\fR(8)
\-\- Network Name Resolution manager
.br
\fBsystemd-resolved.service\fR(8)
\-\- Network Name Resolution manager
.br
\fBsystemd-rfkill\fR(8)
\-\- Load and save the RF kill switch state at boot and shutdown
.br
\fBsystemd-rfkill@.service\fR(8)
\-\- Load and save the RF kill switch state at boot and shutdown
.br
\fBsystemd-run\fR(1)
\-\- Run programs in transient scope or service units
.br
\fBsystemd-shutdown\fR(8)
\-\- System shutdown logic
.br
\fBsystemd-shutdownd\fR(8)
\-\- Scheduled shutdown service
.br
\fBsystemd-shutdownd.service\fR(8)
\-\- Scheduled shutdown service
.br
\fBsystemd-shutdownd.socket\fR(8)
\-\- Scheduled shutdown service
.br
\fBsystemd-sleep\fR(8)
\-\- System sleep state logic
.br
\fBsystemd-sleep.conf\fR(5)
\-\- Suspend and hibernation configuration file
.br
\fBsystemd-socket-proxyd\fR(8)
\-\- Bidirectionally proxy local sockets to another (possibly remote) socket\&.
.br
\fBsystemd-suspend.service\fR(8)
\-\- System sleep state logic
.br
\fBsystemd-sysctl\fR(8)
\-\- Configure kernel parameters at boot
.br
\fBsystemd-sysctl.service\fR(8)
\-\- Configure kernel parameters at boot
.br
\fBsystemd-system-update-generator\fR(8)
\-\- Generator for redirecting boot to offline update mode
.br
\fBsystemd-system.conf\fR(5)
\-\- System and session service manager configuration file
.br
\fBsystemd-sysusers\fR(8)
\-\- Allocate system users and groups
.br
\fBsystemd-sysusers.service\fR(8)
\-\- Allocate system users and groups
.br
\fBsystemd-timedated\fR(8)
\-\- Time and date bus mechanism
.br
\fBsystemd-timedated.service\fR(8)
\-\- Time and date bus mechanism
.br
\fBsystemd-timesyncd\fR(8)
\-\- Network Time Synchronization
.br
\fBsystemd-timesyncd.service\fR(8)
\-\- Network Time Synchronization
.br
\fBsystemd-tmpfiles\fR(8)
\-\- Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-clean.service\fR(8)
\-\- Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-clean.timer\fR(8)
\-\- Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-setup-dev.service\fR(8)
\-\- Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tmpfiles-setup.service\fR(8)
\-\- Creates, deletes and cleans up volatile and temporary files and directories
.br
\fBsystemd-tty-ask-password-agent\fR(1)
\-\- List or process pending systemd password requests
.br
\fBsystemd-udevd\fR(8)
\-\- Device event managing daemon
.br
\fBsystemd-udevd-control.socket\fR(8)
\-\- Device event managing daemon
.br
\fBsystemd-udevd-kernel.socket\fR(8)
\-\- Device event managing daemon
.br
\fBsystemd-udevd.service\fR(8)
\-\- Device event managing daemon
.br
\fBsystemd-update-done\fR(8)
\-\- Mark
.br
\fBsystemd-update-done.service\fR(8)
\-\- Mark
.br
\fBsystemd-update-utmp\fR(8)
\-\- Write audit and utmp updates at bootup, runlevel changes and shutdown
.br
\fBsystemd-update-utmp-runlevel.service\fR(8)
\-\- Write audit and utmp updates at bootup, runlevel changes and shutdown
.br
\fBsystemd-update-utmp.service\fR(8)
\-\- Write audit and utmp updates at bootup, runlevel changes and shutdown
.br
\fBsystemd-user-sessions\fR(8)
\-\- Permit user logins after boot, prohibit user logins at shutdown
.br
\fBsystemd-user-sessions.service\fR(8)
\-\- Permit user logins after boot, prohibit user logins at shutdown
.br
\fBsystemd-user.conf\fR(5)
\-\- System and session service manager configuration file
.br
\fBsystemd-vconsole-setup\fR(8)
\-\- Configure the virtual console at boot
.br
\fBsystemd-vconsole-setup.service\fR(8)
\-\- Configure the virtual console at boot
.br
\fBsystemd.automount\fR(5)
\-\- Automount unit configuration
.br
\fBsystemd.device\fR(5)
\-\- Device unit configuration
.br
\fBsystemd.directives\fR(7)
\-\- Index of configuration directives
.br
\fBsystemd.exec\fR(5)
\-\- Execution environment configuration
.br
\fBsystemd.journal-fields\fR(7)
\-\- Special journal fields
.br
\fBsystemd.kill\fR(5)
\-\- Process killing procedure configuration
.br
\fBsystemd.link\fR(5)
\-\- Network device configuration
.br
\fBsystemd.mount\fR(5)
\-\- Mount unit configuration
.br
\fBsystemd.netdev\fR(5)
\-\- Virtual Network Device configuration
.br
\fBsystemd.network\fR(5)
\-\- Network configuration
.br
\fBsystemd.path\fR(5)
\-\- Path unit configuration
.br
\fBsystemd.preset\fR(5)
\-\- Service enablement presets
.br
\fBsystemd.resource-control\fR(5)
\-\- Resource control unit settings
.br
\fBsystemd.scope\fR(5)
\-\- Scope unit configuration
.br
\fBsystemd.service\fR(5)
\-\- Service unit configuration
.br
\fBsystemd.slice\fR(5)
\-\- Slice unit configuration
.br
\fBsystemd.snapshot\fR(5)
\-\- Snapshot unit configuration
.br
\fBsystemd.socket\fR(5)
\-\- Socket unit configuration
.br
\fBsystemd.special\fR(7)
\-\- Special systemd units
.br
\fBsystemd.swap\fR(5)
\-\- Swap unit configuration
.br
\fBsystemd.target\fR(5)
\-\- Target unit configuration
.br
\fBsystemd.time\fR(7)
\-\- Time and date specifications
.br
\fBsystemd.timer\fR(5)
\-\- Timer unit configuration
.br
\fBsystemd.unit\fR(5)
\-\- Unit configuration
.br
\fBsysusers.d\fR(5)
\-\- Declarative allocation of system users and groups
.br

.SH "T"
.PP
\fBtelinit\fR(8)
\-\- Change SysV runlevel
.br
\fBtimedatectl\fR(1)
\-\- Control the system time and date
.br
\fBtmpfiles.d\fR(5)
\-\- Configuration for creation, deletion and cleaning of volatile and temporary files
.br

.SH "U"
.PP
\fBudev\fR(7)
\-\- Dynamic device management
.br
\fBudevadm\fR(8)
\-\- udev management tool
.br

.SH "V"
.PP
\fBvconsole.conf\fR(5)
\-\- Configuration file for the virtual console
.br

.SH "SEE ALSO"
.PP
\fBsystemd.directives\fR(7)
.PP
This index contains 412 entries, referring to 180 individual manual pages\&.
