'\" t
.TH "SYSTEMD\-GETTY\-GENERATOR" "8" "" "systemd 221" "systemd-getty-generator"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-getty-generator \- Generator for enabling getty instances on the console
.SH "SYNOPSIS"
.PP
/usr/lib/systemd/system\-generators/systemd\-getty\-generator
.SH "DESCRIPTION"
.PP
systemd\-getty\-generator
is a generator that automatically instantiates
serial\-getty@\&.service
on the kernel console
/dev/console
if that is not directed to the virtual console subsystem\&. It will also instantiate
serial\-getty@\&.service
instances for virtualizer consoles, if execution in a virtualized environment is detected\&. Finally, it will instantiate
container\-getty@\&.service
instances for additional container pseudo TTYs as requested by the container manager (see
\m[blue]\fBContainer Interface\fR\m[]\&\s-2\u[1]\d\s+2)\&. This should ensure that the user is shown a login prompt at the right place, regardless of which environment the system is started in\&. For example, it is sufficient to redirect the kernel console with a kernel command line argument such as
\fIconsole=\fR
to get both kernel messages and a getty prompt on a serial TTY\&. See
\m[blue]\fBkernel\-parameters\&.txt\fR\m[]\&\s-2\u[2]\d\s+2
for more information on the
\fIconsole=\fR
kernel parameter\&.
.PP
systemd\-getty\-generator
implements
\fBsystemd.generator\fR(7)\&.
.PP
Further information about configuration of gettys you may find in
\m[blue]\fBsystemd for Administrators, Part XVI: Gettys on Serial Consoles (and Elsewhere)\fR\m[]\&\s-2\u[3]\d\s+2\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBagetty\fR(8)
.SH "NOTES"
.IP " 1." 4
Container
    Interface
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/
.RE
.IP " 2." 4
kernel-parameters.txt
.RS 4
\%https://www.kernel.org/doc/Documentation/kernel-parameters.txt
.RE
.IP " 3." 4
systemd for Administrators, Part XVI: Gettys on Serial Consoles (and Elsewhere)
.RS 4
\%http://0pointer.de/blog/projects/serial-console.html
.RE
