'\" t
.TH "SYSTEMD\&.JOURNAL\-FIELDS" "7" "" "systemd 220" "systemd.journal-fields"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd.journal-fields \- Special journal fields
.SH "DESCRIPTION"
.PP
Entries in the journal resemble an environment block in their syntax but with fields that can include binary data\&. Primarily, fields are formatted UTF\-8 text strings, and binary formatting is used only where formatting as UTF\-8 text strings makes little sense\&. New fields may freely be defined by applications, but a few fields have special meaning\&. All fields with special meanings are optional\&. In some cases, fields may appear more than once per entry\&.
.SH "USER JOURNAL FIELDS"
.PP
User fields are fields that are directly passed from clients and stored in the journal\&.
.PP
\fIMESSAGE=\fR
.RS 4
The human\-readable message string for this entry\&. This is supposed to be the primary text shown to the user\&. It is usually not translated (but might be in some cases), and is not supposed to be parsed for meta data\&.
.RE
.PP
\fIMESSAGE_ID=\fR
.RS 4
A 128\-bit message identifier ID for recognizing certain message types, if this is desirable\&. This should contain a 128\-bit ID formatted as a lower\-case hexadecimal string, without any separating dashes or suchlike\&. This is recommended to be a UUID\-compatible ID, but this is not enforced, and formatted differently\&. Developers can generate a new ID for this purpose with
\fBjournalctl \fR\fB\fB\-\-new\-id\fR\fR\&.
.RE
.PP
\fIPRIORITY=\fR
.RS 4
A priority value between 0 ("emerg") and 7 ("debug") formatted as a decimal string\&. This field is compatible with syslog\*(Aqs priority concept\&.
.RE
.PP
\fICODE_FILE=\fR, \fICODE_LINE=\fR, \fICODE_FUNC=\fR
.RS 4
The code location generating this message, if known\&. Contains the source filename, the line number and the function name\&.
.RE
.PP
\fIERRNO=\fR
.RS 4
The low\-level Unix error number causing this entry, if any\&. Contains the numeric value of
\fBerrno\fR(3)
formatted as a decimal string\&.
.RE
.PP
\fISYSLOG_FACILITY=\fR, \fISYSLOG_IDENTIFIER=\fR, \fISYSLOG_PID=\fR
.RS 4
Syslog compatibility fields containing the facility (formatted as decimal string), the identifier string (i\&.e\&. "tag"), and the client PID\&. (Note that the tag is usually derived from glibc\*(Aqs
\fIprogram_invocation_short_name\fR
variable, see
\fBprogram_invocation_short_name\fR(3)\&.)
.RE
.SH "TRUSTED JOURNAL FIELDS"
.PP
Fields prefixed with an underscore are trusted fields, i\&.e\&. fields that are implicitly added by the journal and cannot be altered by client code\&.
.PP
\fI_PID=\fR, \fI_UID=\fR, \fI_GID=\fR
.RS 4
The process, user, and group ID of the process the journal entry originates from formatted as a decimal string\&.
.RE
.PP
\fI_COMM=\fR, \fI_EXE=\fR, \fI_CMDLINE=\fR
.RS 4
The name, the executable path, and the command line of the process the journal entry originates from\&.
.RE
.PP
\fI_CAP_EFFECTIVE=\fR
.RS 4
The effective
\fBcapabilities\fR(7)
of the process the journal entry originates from\&.
.RE
.PP
\fI_AUDIT_SESSION=\fR, \fI_AUDIT_LOGINUID=\fR
.RS 4
The session and login UID of the process the journal entry originates from, as maintained by the kernel audit subsystem\&.
.RE
.PP
\fI_SYSTEMD_CGROUP=\fR, \fI_SYSTEMD_SESSION=\fR, \fI_SYSTEMD_UNIT=\fR, \fI_SYSTEMD_USER_UNIT=\fR, \fI_SYSTEMD_OWNER_UID=\fR, \fI_SYSTEMD_SLICE=\fR
.RS 4
The control group path in the systemd hierarchy, the systemd session ID (if any), the systemd unit name (if any), the systemd user session unit name (if any), the owner UID of the systemd session (if any) and the systemd slice unit of the process the journal entry originates from\&.
.RE
.PP
\fI_SELINUX_CONTEXT=\fR
.RS 4
The SELinux security context (label) of the process the journal entry originates from\&.
.RE
.PP
\fI_SOURCE_REALTIME_TIMESTAMP=\fR
.RS 4
The earliest trusted timestamp of the message, if any is known that is different from the reception time of the journal\&. This is the time in microseconds since the epoch UTC, formatted as a decimal string\&.
.RE
.PP
\fI_BOOT_ID=\fR
.RS 4
The kernel boot ID for the boot the message was generated in, formatted as a 128\-bit hexadecimal string\&.
.RE
.PP
\fI_MACHINE_ID=\fR
.RS 4
The machine ID of the originating host, as available in
\fBmachine-id\fR(5)\&.
.RE
.PP
\fI_HOSTNAME=\fR
.RS 4
The name of the originating host\&.
.RE
.PP
\fI_TRANSPORT=\fR
.RS 4
How the entry was received by the journal service\&. Valid transports are:
.PP
\fBdriver\fR
.RS 4
for internally generated messages
.RE
.PP
\fBsyslog\fR
.RS 4
for those received via the local syslog socket with the syslog protocol
.RE
.PP
\fBjournal\fR
.RS 4
for those received via the native journal protocol
.RE
.PP
\fBstdout\fR
.RS 4
for those read from a service\*(Aqs standard output or error output
.RE
.PP
\fBkernel\fR
.RS 4
for those read from the kernel
.RE
.RE
.SH "KERNEL JOURNAL FIELDS"
.PP
Kernel fields are fields that are used by messages originating in the kernel and stored in the journal\&.
.PP
\fI_KERNEL_DEVICE=\fR
.RS 4
The kernel device name\&. If the entry is associated to a block device, the major and minor of the device node, separated by
":"
and prefixed by
"b"\&. Similar for character devices but prefixed by
"c"\&. For network devices, this is the interface index prefixed by
"n"\&. For all other devices, this is the subsystem name prefixed by
"+", followed by
":", followed by the kernel device name\&.
.RE
.PP
\fI_KERNEL_SUBSYSTEM=\fR
.RS 4
The kernel subsystem name\&.
.RE
.PP
\fI_UDEV_SYSNAME=\fR
.RS 4
The kernel device name as it shows up in the device tree below
/sys\&.
.RE
.PP
\fI_UDEV_DEVNODE=\fR
.RS 4
The device node path of this device in
/dev\&.
.RE
.PP
\fI_UDEV_DEVLINK=\fR
.RS 4
Additional symlink names pointing to the device node in
/dev\&. This field is frequently set more than once per entry\&.
.RE
.SH "FIELDS TO LOG ON BEHALF OF A DIFFERENT PROGRAM"
.PP
Fields in this section are used by programs to specify that they are logging on behalf of another program or unit\&.
.PP
Fields used by the
\fBsystemd\-coredump\fR
coredump kernel helper:
.PP
\fICOREDUMP_UNIT=\fR, \fICOREDUMP_USER_UNIT=\fR
.RS 4
Used to annotate messages containing coredumps from system and session units\&. See
\fBcoredumpctl\fR(1)\&.
.RE
.PP
Privileged programs (currently UID 0) may attach
\fIOBJECT_PID=\fR
to a message\&. This will instruct
\fBsystemd\-journald\fR
to attach additional fields on behalf of the caller:
.PP
\fIOBJECT_PID=\fR\fI\fIPID\fR\fR
.RS 4
PID of the program that this message pertains to\&.
.RE
.PP
\fIOBJECT_UID=\fR, \fIOBJECT_GID=\fR, \fIOBJECT_COMM=\fR, \fIOBJECT_EXE=\fR, \fIOBJECT_CMDLINE=\fR, \fIOBJECT_AUDIT_SESSION=\fR, \fIOBJECT_AUDIT_LOGINUID=\fR, \fIOBJECT_SYSTEMD_CGROUP=\fR, \fIOBJECT_SYSTEMD_SESSION=\fR, \fIOBJECT_SYSTEMD_OWNER_UID=\fR, \fIOBJECT_SYSTEMD_UNIT=\fR, \fIOBJECT_SYSTEMD_USER_UNIT=\fR
.RS 4
These are additional fields added automatically by
\fBsystemd\-journald\fR\&. Their meaning is the same as
\fI_UID=\fR,
\fI_GID=\fR,
\fI_COMM=\fR,
\fI_EXE=\fR,
\fI_CMDLINE=\fR,
\fI_AUDIT_SESSION=\fR,
\fI_AUDIT_LOGINUID=\fR,
\fI_SYSTEMD_CGROUP=\fR,
\fI_SYSTEMD_SESSION=\fR,
\fI_SYSTEMD_UNIT=\fR,
\fI_SYSTEMD_USER_UNIT=\fR, and
\fI_SYSTEMD_OWNER_UID=\fR
as described above, except that the process identified by
\fIPID\fR
is described, instead of the process which logged the message\&.
.RE
.SH "ADDRESS FIELDS"
.PP
During serialization into external formats, such as the
\m[blue]\fBJournal Export Format\fR\m[]\&\s-2\u[1]\d\s+2
or the
\m[blue]\fBJournal JSON Format\fR\m[]\&\s-2\u[2]\d\s+2, the addresses of journal entries are serialized into fields prefixed with double underscores\&. Note that these are not proper fields when stored in the journal but for addressing metadata of entries\&. They cannot be written as part of structured log entries via calls such as
\fBsd_journal_send\fR(3)\&. They may also not be used as matches for
\fBsd_journal_add_match\fR(3)
.PP
\fI__CURSOR=\fR
.RS 4
The cursor for the entry\&. A cursor is an opaque text string that uniquely describes the position of an entry in the journal and is portable across machines, platforms and journal files\&.
.RE
.PP
\fI__REALTIME_TIMESTAMP=\fR
.RS 4
The wallclock time (\fBCLOCK_REALTIME\fR) at the point in time the entry was received by the journal, in microseconds since the epoch UTC, formatted as a decimal string\&. This has different properties from
"_SOURCE_REALTIME_TIMESTAMP=", as it is usually a bit later but more likely to be monotonic\&.
.RE
.PP
\fI__MONOTONIC_TIMESTAMP=\fR
.RS 4
The monotonic time (\fBCLOCK_MONOTONIC\fR) at the point in time the entry was received by the journal in microseconds, formatted as a decimal string\&. To be useful as an address for the entry, this should be combined with the boot ID in
"_BOOT_ID="\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBjournalctl\fR(1),
\fBjournald.conf\fR(5),
\fBsd-journal\fR(3),
\fBcoredumpctl\fR(1),
\fBsystemd.directives\fR(7)
.SH "NOTES"
.IP " 1." 4
Journal Export Format
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/export
.RE
.IP " 2." 4
Journal JSON Format
.RS 4
\%http://www.freedesktop.org/wiki/Software/systemd/json
.RE
