'\" t
.TH "SYSTEMD\-DELTA" "1" "" "systemd 221" "systemd-delta"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-delta \- Find overridden configuration files
.SH "SYNOPSIS"
.HP \w'\fBsystemd\-delta\fR\ 'u
\fBsystemd\-delta\fR [OPTIONS...] [\fIPREFIX\fR[/\fISUFFIX\fR]|\fISUFFIX\fR...]
.SH "DESCRIPTION"
.PP
\fBsystemd\-delta\fR
may be used to identify and compare configuration files that override other configuration files\&. Files in
/etc
have highest priority, files in
/run
have the second highest priority, \&.\&.\&., files in
/lib
have lowest priority\&. Files in a directory with higher priority override files with the same name in directories of lower priority\&. In addition, certain configuration files can have
"\&.d"
directories which contain "drop\-in" files with configuration snippets which augment the main configuration file\&. "Drop\-in" files can be overridden in the same way by placing files with the same name in a directory of higher priority (except that in case of "drop\-in" files, both the "drop\-in" file name and the name of the containing directory, which corresponds to the name of the main configuration file, must match)\&. For a fuller explanation, see
\fBsystemd.unit\fR(5)\&.
.PP
The command line argument will be split into a prefix and a suffix\&. Either is optional\&. The prefix must be one of the directories containing configuration files (/etc,
/run,
/usr/lib, \&.\&.\&.)\&. If it is given, only overriding files contained in this directory will be shown\&. Otherwise, all overriding files will be shown\&. The suffix must be a name of a subdirectory containing configuration files like
tmpfiles\&.d,
sysctl\&.d
or
systemd/system\&. If it is given, only configuration files in this subdirectory (across all configuration paths) will be analyzed\&. Otherwise, all configuration files will be analyzed\&. If the command line argument is not given at all, all configuration files will be analyzed\&. See below for some examples\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-t\fR, \fB\-\-type=\fR
.RS 4
When listing the differences, only list those that are asked for\&. The list itself is a comma\-separated list of desired difference types\&.
.sp
Recognized types are:
.PP
\fImasked\fR
.RS 4
Show masked files
.RE
.PP
\fIequivalent\fR
.RS 4
Show overridden files that while overridden, do not differ in content\&.
.RE
.PP
\fIredirected\fR
.RS 4
Show files that are redirected to another\&.
.RE
.PP
\fIoverridden\fR
.RS 4
Show overridden, and changed files\&.
.RE
.PP
\fIextended\fR
.RS 4
Show
*\&.conf
files in drop\-in directories for units\&.
.RE
.PP
\fIunchanged\fR
.RS 4
Show unmodified files too\&.
.RE
.sp
.RE
.PP
\fB\-\-diff=\fR
.RS 4
When showing modified files, when a file is overridden show a diff as well\&. This option takes a boolean argument\&. If omitted, it defaults to
\fBtrue\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.PP
\fB\-\-no\-pager\fR
.RS 4
Do not pipe output into a pager\&.
.RE
.SH "EXAMPLES"
.PP
To see all local configuration:
.sp
.if n \{\
.RS 4
.\}
.nf
systemd\-delta
.fi
.if n \{\
.RE
.\}
.PP
To see all runtime configuration:
.sp
.if n \{\
.RS 4
.\}
.nf
systemd\-delta /run
.fi
.if n \{\
.RE
.\}
.PP
To see all system unit configuration changes:
.sp
.if n \{\
.RS 4
.\}
.nf
systemd\-delta systemd/system
.fi
.if n \{\
.RE
.\}
.PP
To see all runtime "drop\-in" changes for system units:
.sp
.if n \{\
.RS 4
.\}
.nf
systemd\-delta \-\-type=extended /run/systemd/system
.fi
.if n \{\
.RE
.\}
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd.unit\fR(5)
