'\" t
.TH "SYSTEMD\-TIMESYNCD\&.SERVICE" "8" "" "systemd 221" "systemd-timesyncd.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-timesyncd.service, systemd-timesyncd \- Network Time Synchronization
.SH "SYNOPSIS"
.PP
systemd\-timesyncd\&.service
.PP
/usr/lib/systemd/systemd\-timesyncd
.SH "DESCRIPTION"
.PP
systemd\-timesyncd
is a system service that may be used to synchronize the local system clock with a remote Network Time Protocol server\&. It also saves the local time to disk every time the clock has been synchronized and uses this to possibly advance the system realtime clock on subsequent reboots to ensure it monotonically advances even if the system lacks a battery\-buffered RTC chip\&.
.PP
The NTP servers contacted are determined from the global settings in
\fBtimesyncd.conf\fR(5), the per\-link static settings in
\&.network
files, and the per\-link dynamic settings received over DHCP\&. See
\fBsystemd.network\fR(5)
for more details\&.
.SH "FILES"
.PP
/var/lib/systemd/clock
.RS 4
This file contains the timestamp of last successful synchronization\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBtimesyncd.conf\fR(5),
\fBsystemd.network\fR(5),
\fBsystemd-networkd.service\fR(8),
\fBtimedatectl\fR(1),
\fBlocaltime\fR(5),
\fBhwclock\fR(8)
