'\" t
.TH "SYSTEMD\-NETWORKD\&.SERVICE" "8" "" "systemd 220" "systemd-networkd.service"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-networkd.service, systemd-networkd \- Network manager
.SH "SYNOPSIS"
.PP
systemd\-networkd\&.service
.PP
/usr/lib/systemd/systemd\-networkd
.SH "DESCRIPTION"
.PP
\fBsystemd\-networkd\fR
is a system service that manages networks\&. It detects and configures network devices as they appear, as well as creating virtual network devices\&.
.PP
To configure low\-level link settings independently of networks, see
\fBsystemd.link\fR(5)\&.
.PP
Network configurations applied before networkd is started are not removed, and static configuration applied by networkd is not removed when networkd exits\&. Dynamic configuration applied by networkd may also optionally be left in place on shutdown\&. This ensures restarting networkd does not cut the network connection, and, in particular, that it is safe to transition between the initrd and the real root, and back\&.
.SH "CONFIGURATION FILES"
.PP
The configuration files are read from the files located in the system network directory
/usr/lib/systemd/network, the volatile runtime network directory
/run/systemd/network
and the local administration network directory
/etc/systemd/network\&.
.PP
Networks are configured in
\&.network
files, see
\fBsystemd.network\fR(5), and virtual network devices are configured in
\&.netdev
files, see
\fBsystemd.netdev\fR(5)\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd.link\fR(5),
\fBsystemd.network\fR(5),
\fBsystemd.netdev\fR(5),
\fBsystemd-networkd-wait-online.service\fR(8)
