'\" t
.TH "SYSTEMCTL" "1" "" "systemd 220" "systemctl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemctl \- Control the systemd system and service manager
.SH "SYNOPSIS"
.HP \w'\fBsystemctl\fR\ 'u
\fBsystemctl\fR [OPTIONS...] COMMAND [NAME...]
.SH "DESCRIPTION"
.PP
\fBsystemctl\fR
may be used to introspect and control the state of the
"systemd"
system and service manager\&. Please refer to
\fBsystemd\fR(1)
for an introduction into the basic concepts and functionality this tool manages\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-t\fR, \fB\-\-type=\fR
.RS 4
The argument should be a comma\-separated list of unit types such as
\fBservice\fR
and
\fBsocket\fR\&.
.sp
If one of the arguments is a unit type, when listing units, limit display to certain unit types\&. Otherwise, units of all types will be shown\&.
.sp
As a special case, if one of the arguments is
\fBhelp\fR, a list of allowed values will be printed and the program will exit\&.
.RE
.PP
\fB\-\-state=\fR
.RS 4
The argument should be a comma\-separated list of unit LOAD, SUB, or ACTIVE states\&. When listing units, show only those in specified states\&. Use
\fB\-\-state=failed\fR
to show only failed units\&.
.RE
.PP
\fB\-p\fR, \fB\-\-property=\fR
.RS 4
When showing unit/job/manager properties with the
\fBshow\fR
command, limit display to certain properties as specified as argument\&. If not specified, all set properties are shown\&. The argument should be a comma\-separated list of property names, such as
"MainPID"\&. If specified more than once, all properties with the specified names are shown\&.
.RE
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
When listing units, show all loaded units, regardless of their state, including inactive units\&. When showing unit/job/manager properties, show all properties regardless whether they are set or not\&.
.sp
To list all units installed on the system, use the
\fBlist\-unit\-files\fR
command instead\&.
.RE
.PP
\fB\-r\fR, \fB\-\-recursive\fR
.RS 4
When listing units, also show units of local containers\&. Units of local containers will be prefixed with the container name, separated by a single colon character (":")\&.
.RE
.PP
\fB\-\-reverse\fR
.RS 4
Show reverse dependencies between units with
\fBlist\-dependencies\fR, i\&.e\&. follow dependencies of type
\fIWantedBy=\fR,
\fIRequiredBy=\fR,
\fIRequiredByOverridable=\fR,
\fIPartOf=\fR,
\fIBoundBy=\fR, instead of
\fIWants=\fR
and similar\&.
.RE
.PP
\fB\-\-after\fR
.RS 4
With
\fBlist\-dependencies\fR, show the units that are ordered before the specified unit\&. In other words, recursively list units following the
\fIAfter=\fR
dependency\&.
.sp
Note that any
\fIAfter=\fR
dependency is automatically mirrored to create a
\fIBefore=\fR
dependency\&. Temporal dependencies may be specified explicitly, but are also created implicitly for units which are
\fIWantedBy=\fR
targets (see
\fBsystemd.target\fR(5)), and as a result of other directives (for example
\fIRequiresMountsFor=\fR)\&. Both explicitly and implicitly introduced dependencies are shown with
\fBlist\-dependencies\fR\&.
.RE
.PP
\fB\-\-before\fR
.RS 4
With
\fBlist\-dependencies\fR, show the units that are ordered after the specified unit\&. In other words, recursively list units following the
\fIBefore=\fR
dependency\&.
.RE
.PP
\fB\-l\fR, \fB\-\-full\fR
.RS 4
Do not ellipsize unit names, process tree entries, journal output, or truncate unit descriptions in the output of
\fBstatus\fR,
\fBlist\-units\fR,
\fBlist\-jobs\fR, and
\fBlist\-timers\fR\&.
.RE
.PP
\fB\-\-show\-types\fR
.RS 4
When showing sockets, show the type of the socket\&.
.RE
.PP
\fB\-\-job\-mode=\fR
.RS 4
When queuing a new job, this option controls how to deal with already queued jobs\&. It takes one of
"fail",
"replace",
"replace\-irreversibly",
"isolate",
"ignore\-dependencies",
"ignore\-requirements"
or
"flush"\&. Defaults to
"replace", except when the
\fBisolate\fR
command is used which implies the
"isolate"
job mode\&.
.sp
If
"fail"
is specified and a requested operation conflicts with a pending job (more specifically: causes an already pending start job to be reversed into a stop job or vice versa), cause the operation to fail\&.
.sp
If
"replace"
(the default) is specified, any conflicting pending job will be replaced, as necessary\&.
.sp
If
"replace\-irreversibly"
is specified, operate like
"replace", but also mark the new jobs as irreversible\&. This prevents future conflicting transactions from replacing these jobs (or even being enqueued while the irreversible jobs are still pending)\&. Irreversible jobs can still be cancelled using the
\fBcancel\fR
command\&.
.sp
"isolate"
is only valid for start operations and causes all other units to be stopped when the specified unit is started\&. This mode is always used when the
\fBisolate\fR
command is used\&.
.sp
"flush"
will cause all queued jobs to be canceled when the new job is enqueued\&.
.sp
If
"ignore\-dependencies"
is specified, then all unit dependencies are ignored for this new job and the operation is executed immediately\&. If passed, no required units of the unit passed will be pulled in, and no ordering dependencies will be honored\&. This is mostly a debugging and rescue tool for the administrator and should not be used by applications\&.
.sp
"ignore\-requirements"
is similar to
"ignore\-dependencies", but only causes the requirement dependencies to be ignored, the ordering dependencies will still be honoured\&.
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-inhibitors\fR
.RS 4
When system shutdown or a sleep state is requested, ignore inhibitor locks\&. Applications can establish inhibitor locks to avoid that certain important operations (such as CD burning or suchlike) are interrupted by system shutdown or a sleep state\&. Any user may take these locks and privileged users may override these locks\&. If any locks are taken, shutdown and sleep state requests will normally fail (regardless of whether privileged or not) and a list of active locks is printed\&. However, if
\fB\-\-ignore\-inhibitors\fR
is specified, the locks are ignored and not printed, and the operation attempted anyway, possibly requiring additional privileges\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Suppress output to standard output in
\fBsnapshot\fR,
\fBis\-active\fR,
\fBis\-failed\fR,
\fBis\-enabled\fR,
\fBis\-system\-running\fR,
\fBenable\fR
and
\fBdisable\fR\&.
.RE
.PP
\fB\-\-no\-block\fR
.RS 4
Do not synchronously wait for the requested operation to finish\&. If this is not specified, the job will be verified, enqueued and
\fBsystemctl\fR
will wait until the unit\*(Aqs start\-up is completed\&. By passing this argument, it is only verified and enqueued\&.
.RE
.PP
\fB\-\-user\fR
.RS 4
Talk to the service manager of the calling user, rather than the service manager of the system\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
Talk to the service manager of the system\&. This is the implied default\&.
.RE
.PP
\fB\-\-no\-wall\fR
.RS 4
Do not send wall message before halt, power\-off, reboot\&.
.RE
.PP
\fB\-\-global\fR
.RS 4
When used with
\fBenable\fR
and
\fBdisable\fR, operate on the global user configuration directory, thus enabling or disabling a unit file globally for all future logins of all users\&.
.RE
.PP
\fB\-\-no\-reload\fR
.RS 4
When used with
\fBenable\fR
and
\fBdisable\fR, do not implicitly reload daemon configuration after executing the changes\&.
.RE
.PP
\fB\-\-no\-ask\-password\fR
.RS 4
When used with
\fBstart\fR
and related commands, disables asking for passwords\&. Background services may require input of a password or passphrase string, for example to unlock system hard disks or cryptographic certificates\&. Unless this option is specified and the command is invoked from a terminal,
\fBsystemctl\fR
will query the user on the terminal for the necessary secrets\&. Use this option to switch this behavior off\&. In this case, the password must be supplied by some other means (for example graphical password agents) or the service might fail\&. This also disables querying the user for authentication for privileged operations\&.
.RE
.PP
\fB\-\-kill\-who=\fR
.RS 4
When used with
\fBkill\fR, choose which processes to send a signal to\&. Must be one of
\fBmain\fR,
\fBcontrol\fR
or
\fBall\fR
to select whether to kill only the main process, the control process or all processes of the unit\&. The main process of the unit is the one that defines the life\-time of it\&. A control process of a unit is one that is invoked by the manager to induce state changes of it\&. For example, all processes started due to the
\fIExecStartPre=\fR,
\fIExecStop=\fR
or
\fIExecReload=\fR
settings of service units are control processes\&. Note that there is only one control process per unit at a time, as only one state change is executed at a time\&. For services of type
\fIType=forking\fR, the initial process started by the manager for
\fIExecStart=\fR
is a control process, while the process ultimately forked off by that one is then considered the main process of the unit (if it can be determined)\&. This is different for service units of other types, where the process forked off by the manager for
\fIExecStart=\fR
is always the main process itself\&. A service unit consists of zero or one main process, zero or one control process plus any number of additional processes\&. Not all unit types manage processes of these types however\&. For example, for mount units, control processes are defined (which are the invocations of
/usr/bin/mount
and
/usr/bin/umount), but no main process is defined\&. If omitted, defaults to
\fBall\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-signal=\fR
.RS 4
When used with
\fBkill\fR, choose which signal to send to selected processes\&. Must be one of the well known signal specifiers such as
\fBSIGTERM\fR,
\fBSIGINT\fR
or
\fBSIGSTOP\fR\&. If omitted, defaults to
\fBSIGTERM\fR\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
When used with
\fBenable\fR, overwrite any existing conflicting symlinks\&.
.sp
When used with
\fBhalt\fR,
\fBpoweroff\fR,
\fBreboot\fR
or
\fBkexec\fR, execute the selected operation without shutting down all units\&. However, all processes will be killed forcibly and all file systems are unmounted or remounted read\-only\&. This is hence a drastic but relatively safe option to request an immediate reboot\&. If
\fB\-\-force\fR
is specified twice for these operations, they will be executed immediately without terminating any processes or unmounting any file systems\&. Warning: specifying
\fB\-\-force\fR
twice with any of these operations might result in data loss\&.
.RE
.PP
\fB\-\-now\fR
.RS 4
When used with
\fBenable\fR, the units will also be started\&. When used with
\fBdisable\fR
or
\fBmask\fR, the units will also be stopped\&. The start or stop operation is only carried out when the respective enable or disable operation has been successful\&.
.RE
.PP
\fB\-\-root=\fR
.RS 4
When used with
\fBenable\fR/\fBdisable\fR/\fBis\-enabled\fR
(and related commands), use alternative root path when looking for unit files\&.
.RE
.PP
\fB\-\-runtime\fR
.RS 4
When used with
\fBenable\fR,
\fBdisable\fR,
\fBedit\fR, (and related commands), make changes only temporarily, so that they are lost on the next reboot\&. This will have the effect that changes are not made in subdirectories of
/etc
but in
/run, with identical immediate effects, however, since the latter is lost on reboot, the changes are lost too\&.
.sp
Similarly, when used with
\fBset\-property\fR, make changes only temporarily, so that they are lost on the next reboot\&.
.RE
.PP
\fB\-\-preset\-mode=\fR
.RS 4
Takes one of
"full"
(the default),
"enable\-only",
"disable\-only"\&. When used with the
\fBpreset\fR
or
\fBpreset\-all\fR
commands, controls whether units shall be disabled and enabled according to the preset rules, or only enabled, or only disabled\&.
.RE
.PP
\fB\-n\fR, \fB\-\-lines=\fR
.RS 4
When used with
\fBstatus\fR, controls the number of journal lines to show, counting from the most recent ones\&. Takes a positive integer argument\&. Defaults to 10\&.
.RE
.PP
\fB\-o\fR, \fB\-\-output=\fR
.RS 4
When used with
\fBstatus\fR, controls the formatting of the journal entries that are shown\&. For the available choices, see
\fBjournalctl\fR(1)\&. Defaults to
"short"\&.
.RE
.PP
\fB\-\-firmware\-setup\fR
.RS 4
When used with the
\fBreboot\fR
command, indicate to the system\*(Aqs firmware to boot into setup mode\&. Note that this is currently only supported on some EFI systems and only if the system was booted in EFI mode\&.
.RE
.PP
\fB\-\-plain\fR
.RS 4
When used with
\fBlist\-dependencies\fR, the output is printed as a list instead of a tree\&.
.RE
.PP
\fB\-H\fR, \fB\-\-host=\fR
.RS 4
Execute the operation remotely\&. Specify a hostname, or a username and hostname separated by
"@", to connect to\&. The hostname may optionally be suffixed by a container name, separated by
":", which connects directly to a specific container on the specified host\&. This will use SSH to talk to the remote machine manager instance\&. Container names may be enumerated with
\fBmachinectl \-H \fR\fB\fIHOST\fR\fR\&.
.RE
.PP
\fB\-M\fR, \fB\-\-machine=\fR
.RS 4
Execute operation on a local container\&. Specify a container name to connect to\&.
.RE
.PP
\fB\-\-no\-pager\fR
.RS 4
Do not pipe output into a pager\&.
.RE
.PP
\fB\-\-no\-legend\fR
.RS 4
Do not print the legend, i\&.e\&. column headers and the footer with hints\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.SH "COMMANDS"
.PP
The following commands are understood:
.SS "Unit Commands"
.PP
\fBlist\-units \fR\fB[\fIPATTERN\fR\&.\&.\&.]\fR
.RS 4
List known units (subject to limitations specified with
\fB\-t\fR)\&. If one or more
\fIPATTERN\fRs are specified, only units matching one of them are shown\&.
.sp
This is the default command\&.
.RE
.PP
\fBlist\-sockets \fR\fB[\fIPATTERN\fR\&.\&.\&.]\fR
.RS 4
List socket units ordered by listening address\&. If one or more
\fIPATTERN\fRs are specified, only socket units matching one of them are shown\&. Produces output similar to
.sp
.if n \{\
.RS 4
.\}
.nf
LISTEN           UNIT                        ACTIVATES
/dev/initctl     systemd\-initctl\&.socket      systemd\-initctl\&.service
\&.\&.\&.
[::]:22          sshd\&.socket                 sshd\&.service
kobject\-uevent 1 systemd\-udevd\-kernel\&.socket systemd\-udevd\&.service

5 sockets listed\&.
.fi
.if n \{\
.RE
.\}
.sp
Note: because the addresses might contains spaces, this output is not suitable for programmatic consumption\&.
.sp
See also the options
\fB\-\-show\-types\fR,
\fB\-\-all\fR, and
\fB\-\-state=\fR\&.
.RE
.PP
\fBlist\-timers \fR\fB[\fIPATTERN\fR\&.\&.\&.]\fR
.RS 4
List timer units ordered by the time they elapse next\&. If one or more
\fIPATTERN\fRs are specified, only units matching one of them are shown\&.
.sp
See also the options
\fB\-\-all\fR
and
\fB\-\-state=\fR\&.
.RE
.PP
\fBstart \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Start (activate) one or more units specified on the command line\&.
.sp
Note that glob patterns operate on a list of currently loaded units\&. Units which are not active and are not in a failed state usually are not loaded, and would not be matched by any pattern\&. In addition, in case of instantiated units, systemd is often unaware of the instance name until the instance has been started\&. Therefore, using glob patterns with
\fBstart\fR
has limited usefulness\&.
.RE
.PP
\fBstop \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Stop (deactivate) one or more units specified on the command line\&.
.RE
.PP
\fBreload \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Asks all units listed on the command line to reload their configuration\&. Note that this will reload the service\-specific configuration, not the unit configuration file of systemd\&. If you want systemd to reload the configuration file of a unit, use the
\fBdaemon\-reload\fR
command\&. In other words: for the example case of Apache, this will reload Apache\*(Aqs
httpd\&.conf
in the web server, not the
apache\&.service
systemd unit file\&.
.sp
This command should not be confused with the
\fBdaemon\-reload\fR
command\&.
.RE
.PP
\fBrestart \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Restart one or more units specified on the command line\&. If the units are not running yet, they will be started\&.
.RE
.PP
\fBtry\-restart \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Restart one or more units specified on the command line if the units are running\&. This does nothing if units are not running\&. Note that, for compatibility with Red Hat init scripts,
\fBcondrestart\fR
is equivalent to this command\&.
.RE
.PP
\fBreload\-or\-restart \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Reload one or more units if they support it\&. If not, restart them instead\&. If the units are not running yet, they will be started\&.
.RE
.PP
\fBreload\-or\-try\-restart \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Reload one or more units if they support it\&. If not, restart them instead\&. This does nothing if the units are not running\&. Note that, for compatibility with SysV init scripts,
\fBforce\-reload\fR
is equivalent to this command\&.
.RE
.PP
\fBisolate \fR\fB\fINAME\fR\fR
.RS 4
Start the unit specified on the command line and its dependencies and stop all others\&. If a unit name with no extension is given, an extension of
"\&.target"
will be assumed\&.
.sp
This is similar to changing the runlevel in a traditional init system\&. The
\fBisolate\fR
command will immediately stop processes that are not enabled in the new unit, possibly including the graphical environment or terminal you are currently using\&.
.sp
Note that this is allowed only on units where
\fBAllowIsolate=\fR
is enabled\&. See
\fBsystemd.unit\fR(5)
for details\&.
.RE
.PP
\fBkill \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Send a signal to one or more processes of the unit\&. Use
\fB\-\-kill\-who=\fR
to select which process to kill\&. Use
\fB\-\-signal=\fR
to select the signal to send\&.
.RE
.PP
\fBis\-active \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Check whether any of the specified units are active (i\&.e\&. running)\&. Returns an exit code
\fB0\fR
if at least one is active, or non\-zero otherwise\&. Unless
\fB\-\-quiet\fR
is specified, this will also print the current unit state to standard output\&.
.RE
.PP
\fBis\-failed \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Check whether any of the specified units are in a "failed" state\&. Returns an exit code
\fB0\fR
if at least one has failed, non\-zero otherwise\&. Unless
\fB\-\-quiet\fR
is specified, this will also print the current unit state to standard output\&.
.RE
.PP
\fBstatus\fR [\fIPATTERN\fR\&.\&.\&.|\fIPID\fR\&.\&.\&.]]
.RS 4
Show terse runtime status information about one or more units, followed by most recent log data from the journal\&. If no units are specified, show system status\&. If combined with
\fB\-\-all\fR, also show the status of all units (subject to limitations specified with
\fB\-t\fR)\&. If a PID is passed, show information about the unit the process belongs to\&.
.sp
This function is intended to generate human\-readable output\&. If you are looking for computer\-parsable output, use
\fBshow\fR
instead\&. By default this function only shows 10 lines of output and ellipsizes lines to fit in the terminal window\&. This can be changes with
\fB\-\-lines\fR
and
\fB\-\-full\fR, see above\&. In addition,
\fBjournalctl \-\-unit=\fR\fB\fINAME\fR\fR
or
\fBjournalctl \-\-user\-unit=\fR\fB\fINAME\fR\fR
use a similar filter for messages and might be more convenient\&.
.RE
.PP
\fBshow\fR [\fIPATTERN\fR\&.\&.\&.|\fIJOB\fR\&.\&.\&.]
.RS 4
Show properties of one or more units, jobs, or the manager itself\&. If no argument is specified, properties of the manager will be shown\&. If a unit name is specified, properties of the unit is shown, and if a job id is specified, properties of the job is shown\&. By default, empty properties are suppressed\&. Use
\fB\-\-all\fR
to show those too\&. To select specific properties to show, use
\fB\-\-property=\fR\&. This command is intended to be used whenever computer\-parsable output is required\&. Use
\fBstatus\fR
if you are looking for formatted human\-readable output\&.
.RE
.PP
\fBcat \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Show backing files of one or more units\&. Prints the "fragment" and "drop\-ins" (source files) of units\&. Each file is preceded by a comment which includes the file name\&.
.RE
.PP
\fBset\-property \fR\fB\fINAME\fR\fR\fB \fR\fB\fIASSIGNMENT\fR\fR\fB\&.\&.\&.\fR
.RS 4
Set the specified unit properties at runtime where this is supported\&. This allows changing configuration parameter properties such as resource control settings at runtime\&. Not all properties may be changed at runtime, but many resource control settings (primarily those in
\fBsystemd.resource-control\fR(5)) may\&. The changes are applied instantly, and stored on disk for future boots, unless
\fB\-\-runtime\fR
is passed, in which case the settings only apply until the next reboot\&. The syntax of the property assignment follows closely the syntax of assignments in unit files\&.
.sp
Example:
\fBsystemctl set\-property foobar\&.service CPUShares=777\fR
.sp
Note that this command allows changing multiple properties at the same time, which is preferable over setting them individually\&. Like unit file configuration settings, assigning the empty list to list parameters will reset the list\&.
.RE
.PP
\fBhelp \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.|\fR\fB\fIPID\fR\fR\fB\&.\&.\&.\fR
.RS 4
Show manual pages for one or more units, if available\&. If a PID is given, the manual pages for the unit the process belongs to are shown\&.
.RE
.PP
\fBreset\-failed [\fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.]\fR
.RS 4
Reset the
"failed"
state of the specified units, or if no unit name is passed, reset the state of all units\&. When a unit fails in some way (i\&.e\&. process exiting with non\-zero error code, terminating abnormally or timing out), it will automatically enter the
"failed"
state and its exit code and status is recorded for introspection by the administrator until the service is restarted or reset with this command\&.
.RE
.PP
\fBlist\-dependencies\fR [\fINAME\fR]
.RS 4
Shows units required and wanted by the specified unit\&. This recursively lists units following the
\fIRequires=\fR,
\fIRequiresOverridable=\fR,
\fIRequisite=\fR,
\fIRequisiteOverridable=\fR,
\fIWants=\fR,
\fIBindsTo=\fR
dependencies\&. If no unit is specified,
default\&.target
is implied\&.
.sp
By default, only target units are recursively expanded\&. When
\fB\-\-all\fR
is passed, all other units are recursively expanded as well\&.
.sp
Options
\fB\-\-reverse\fR,
\fB\-\-after\fR,
\fB\-\-before\fR
may be used to change what types of dependencies are shown\&.
.RE
.SS "Unit File Commands"
.PP
\fBlist\-unit\-files \fR\fB[\fIPATTERN\&.\&.\&.\fR]\fR
.RS 4
List installed unit files\&. If one or more
\fIPATTERN\fRs are specified, only units whose filename (just the last component of the path) matches one of them are shown\&.
.RE
.PP
\fBenable \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Enable one or more unit files or unit file instances, as specified on the command line\&. This will create a number of symlinks as encoded in the
"[Install]"
sections of the unit files\&. After the symlinks have been created, the systemd configuration is reloaded (in a way that is equivalent to
\fBdaemon\-reload\fR) to ensure the changes are taken into account immediately\&. Note that this does
\fInot\fR
have the effect of also starting any of the units being enabled\&. If this is desired, either
\fB\-\-now\fR
should be used together with this command, or an additional
\fBstart\fR
command must be invoked for the unit\&. Also note that in case of instance enablement, symlinks named the same as instances are created in the install location, however they all point to the same template unit file\&.
.sp
This command will print the actions executed\&. This output may be suppressed by passing
\fB\-\-quiet\fR\&.
.sp
Note that this operation creates only the suggested symlinks for the units\&. While this command is the recommended way to manipulate the unit configuration directory, the administrator is free to make additional changes manually by placing or removing symlinks in the directory\&. This is particularly useful to create configurations that deviate from the suggested default installation\&. In this case, the administrator must make sure to invoke
\fBdaemon\-reload\fR
manually as necessary to ensure the changes are taken into account\&.
.sp
Enabling units should not be confused with starting (activating) units, as done by the
\fBstart\fR
command\&. Enabling and starting units is orthogonal: units may be enabled without being started and started without being enabled\&. Enabling simply hooks the unit into various suggested places (for example, so that the unit is automatically started on boot or when a particular kind of hardware is plugged in)\&. Starting actually spawns the daemon process (in case of service units), or binds the socket (in case of socket units), and so on\&.
.sp
Depending on whether
\fB\-\-system\fR,
\fB\-\-user\fR,
\fB\-\-runtime\fR, or
\fB\-\-global\fR
is specified, this enables the unit for the system, for the calling user only, for only this boot of the system, or for all future logins of all users, or only this boot\&. Note that in the last case, no systemd daemon configuration is reloaded\&.
.sp
Using
\fBenable\fR
on masked units results in an error\&.
.RE
.PP
\fBdisable \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Disables one or more units\&. This removes all symlinks to the specified unit files from the unit configuration directory, and hence undoes the changes made by
\fBenable\fR\&. Note however that this removes all symlinks to the unit files (i\&.e\&. including manual additions), not just those actually created by
\fBenable\fR\&. This call implicitly reloads the systemd daemon configuration after completing the disabling of the units\&. Note that this command does not implicitly stop the units that are being disabled\&. If this is desired, either
\fB\-\-now\fR
should be used together with this command, or an additional
\fBstop\fR
command should be executed afterwards\&.
.sp
This command will print the actions executed\&. This output may be suppressed by passing
\fB\-\-quiet\fR\&.
.sp
This command honors
\fB\-\-system\fR,
\fB\-\-user\fR,
\fB\-\-runtime\fR
and
\fB\-\-global\fR
in a similar way as
\fBenable\fR\&.
.RE
.PP
\fBreenable \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Reenable one or more unit files, as specified on the command line\&. This is a combination of
\fBdisable\fR
and
\fBenable\fR
and is useful to reset the symlinks a unit is enabled with to the defaults configured in the
"[Install]"
section of the unit file\&.
.RE
.PP
\fBpreset \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Reset one or more unit files, as specified on the command line, to the defaults configured in the preset policy files\&. This has the same effect as
\fBdisable\fR
or
\fBenable\fR, depending how the unit is listed in the preset files\&.
.sp
Use
\fB\-\-preset\-mode=\fR
to control whether units shall be enabled and disabled, or only enabled, or only disabled\&.
.sp
For more information on the preset policy format, see
\fBsystemd.preset\fR(5)\&. For more information on the concept of presets, please consult the
\m[blue]\fBPreset\fR\m[]\&\s-2\u[1]\d\s+2
document\&.
.RE
.PP
\fBpreset\-all\fR
.RS 4
Resets all installed unit files to the defaults configured in the preset policy file (see above)\&.
.sp
Use
\fB\-\-preset\-mode=\fR
to control whether units shall be enabled and disabled, or only enabled, or only disabled\&.
.RE
.PP
\fBis\-enabled \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Checks whether any of the specified unit files are enabled (as with
\fBenable\fR)\&. Returns an exit code of 0 if at least one is enabled, non\-zero otherwise\&. Prints the current enable status (see table)\&. To suppress this output, use
\fB\-\-quiet\fR\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \& is\-enabled output
.TS
allbox tab(:);
lB lB lB.
T{
Printed string
T}:T{
Meaning
T}:T{
Return value
T}
.T&
l l l
l ^ ^
l l l
l ^ ^
l l l
l ^ ^
l l l
l l l
l l l.
T{
"enabled"
T}:T{
Enabled through a symlink in \&.wants directory (permanently or just in /run)\&.
T}:T{
0
T}
T{
"enabled\-runtime"
T}::
T{
"linked"
T}:T{
Made available through a symlink to the unit file (permanently or just in /run)\&.
T}:T{
1
T}
T{
"linked\-runtime"
T}::
T{
"masked"
T}:T{
Disabled entirely (permanently or just in /run)\&.
T}:T{
1
T}
T{
"masked\-runtime"
T}::
T{
"static"
T}:T{
Unit file is not enabled, and has no provisions for enabling in the "[Install]" section\&.
T}:T{
0
T}
T{
"indirect"
T}:T{
Unit file itself is not enabled, but it has a non\-empty \fIAlso=\fR setting in the "[Install]" section, listing other unit files that might be enabled\&.
T}:T{
0
T}
T{
"disabled"
T}:T{
Unit file is not enabled\&.
T}:T{
1
T}
.TE
.sp 1
.RE
.PP
\fBmask \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Mask one or more unit files, as specified on the command line\&. This will link these units to
/dev/null, making it impossible to start them\&. This is a stronger version of
\fBdisable\fR, since it prohibits all kinds of activation of the unit, including enablement and manual activation\&. Use this option with care\&. This honors the
\fB\-\-runtime\fR
option to only mask temporarily until the next reboot of the system\&. The
\fB\-\-now\fR
option can be used to ensure that the units are also stopped\&.
.RE
.PP
\fBunmask \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Unmask one or more unit files, as specified on the command line\&. This will undo the effect of
\fBmask\fR\&.
.RE
.PP
\fBlink \fR\fB\fIFILENAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Link a unit file that is not in the unit file search paths into the unit file search path\&. This requires an absolute path to a unit file\&. The effect of this can be undone with
\fBdisable\fR\&. The effect of this command is that a unit file is available for
\fBstart\fR
and other commands although it is not installed directly in the unit search path\&.
.RE
.PP
\fBadd\-wants \fR\fB\fITARGET\fR\fR\fB \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR, \fBadd\-requires \fR\fB\fITARGET\fR\fR\fB \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Adds
"Wants="
resp\&.
"Requires="
dependency to the specified
\fITARGET\fR
for one or more units\&.
.sp
This command honors
\fB\-\-system\fR,
\fB\-\-user\fR,
\fB\-\-runtime\fR
and
\fB\-\-global\fR
in a similar way as
\fBenable\fR\&.
.RE
.PP
\fBedit \fR\fB\fINAME\fR\fR\fB\&.\&.\&.\fR
.RS 4
Edit a drop\-in snippet or a whole replacement file if
\fB\-\-full\fR
is specified, to extend or override the specified unit\&.
.sp
Depending on whether
\fB\-\-system\fR
(the default),
\fB\-\-user\fR, or
\fB\-\-global\fR
is specified, this creates a drop\-in file for each unit either for the system, for the calling user or for all futures logins of all users\&. Then, the editor (see the "Environment" section below) is invoked on temporary files which will be written to the real location if the editor exits successfully\&.
.sp
If
\fB\-\-full\fR
is specified, this will copy the original units instead of creating drop\-in files\&.
.sp
If
\fB\-\-runtime\fR
is specified, the changes will be made temporarily in
/run
and they will be lost on the next reboot\&.
.sp
If the temporary file is empty upon exit the modification of the related unit is canceled
.sp
After the units have been edited, systemd configuration is reloaded (in a way that is equivalent to
\fBdaemon\-reload\fR)\&.
.sp
Note that this command cannot be used to remotely edit units and that you cannot temporarily edit units which are in
/etc
since they take precedence over
/run\&.
.RE
.PP
\fBget\-default\fR
.RS 4
Return the default target to boot into\&. This returns the target unit name
default\&.target
is aliased (symlinked) to\&.
.RE
.PP
\fBset\-default \fR\fB\fINAME\fR\fR
.RS 4
Set the default target to boot into\&. This sets (symlinks) the
default\&.target
alias to the given target unit\&.
.RE
.SS "Machine Commands"
.PP
\fBlist\-machines \fR\fB[\fIPATTERN\fR\&.\&.\&.]\fR
.RS 4
List the host and all running local containers with their state\&. If one or more
\fIPATTERN\fRs are specified, only containers matching one of them are shown\&.
.RE
.SS "Job Commands"
.PP
\fBlist\-jobs \fR\fB[\fIPATTERN\&.\&.\&.\fR]\fR
.RS 4
List jobs that are in progress\&. If one or more
\fIPATTERN\fRs are specified, only jobs for units matching one of them are shown\&.
.RE
.PP
\fBcancel \fR\fB\fIJOB\fR\fR\fB\&.\&.\&.\fR
.RS 4
Cancel one or more jobs specified on the command line by their numeric job IDs\&. If no job ID is specified, cancel all pending jobs\&.
.RE
.SS "Snapshot Commands"
.PP
\fBsnapshot \fR\fB[\fINAME\fR]\fR
.RS 4
Create a snapshot\&. If a snapshot name is specified, the new snapshot will be named after it\&. If none is specified, an automatic snapshot name is generated\&. In either case, the snapshot name used is printed to standard output, unless
\fB\-\-quiet\fR
is specified\&.
.sp
A snapshot refers to a saved state of the systemd manager\&. It is implemented itself as a unit that is generated dynamically with this command and has dependencies on all units active at the time\&. At a later time, the user may return to this state by using the
\fBisolate\fR
command on the snapshot unit\&.
.sp
Snapshots are only useful for saving and restoring which units are running or are stopped, they do not save/restore any other state\&. Snapshots are dynamic and lost on reboot\&.
.RE
.PP
\fBdelete \fR\fB\fIPATTERN\fR\fR\fB\&.\&.\&.\fR
.RS 4
Remove a snapshot previously created with
\fBsnapshot\fR\&.
.RE
.SS "Environment Commands"
.PP
\fBshow\-environment\fR
.RS 4
Dump the systemd manager environment block\&. The environment block will be dumped in straight\-forward form suitable for sourcing into a shell script\&. This environment block will be passed to all processes the manager spawns\&.
.RE
.PP
\fBset\-environment \fR\fB\fIVARIABLE=VALUE\fR\fR\fB\&.\&.\&.\fR
.RS 4
Set one or more systemd manager environment variables, as specified on the command line\&.
.RE
.PP
\fBunset\-environment \fR\fB\fIVARIABLE\fR\fR\fB\&.\&.\&.\fR
.RS 4
Unset one or more systemd manager environment variables\&. If only a variable name is specified, it will be removed regardless of its value\&. If a variable and a value are specified, the variable is only removed if it has the specified value\&.
.RE
.PP
\fBimport\-environment\fR [\fIVARIABLE\&.\&.\&.\fR]
.RS 4
Import all, one or more environment variables set on the client into the systemd manager environment block\&. If no arguments are passed, the entire environment block is imported\&. Otherwise, a list of one or more environment variable names should be passed, whose client\-side values are then imported into the manager\*(Aqs environment block\&.
.RE
.SS "Manager Lifecycle Commands"
.PP
\fBdaemon\-reload\fR
.RS 4
Reload systemd manager configuration\&. This will rerun all generators (see
\fBsystemd.generator\fR(7)), reload all unit files, and recreate the entire dependency tree\&. While the daemon is being reloaded, all sockets systemd listens on behalf of user configuration will stay accessible\&.
.sp
This command should not be confused with the
\fBreload\fR
command\&.
.RE
.PP
\fBdaemon\-reexec\fR
.RS 4
Reexecute the systemd manager\&. This will serialize the manager state, reexecute the process and deserialize the state again\&. This command is of little use except for debugging and package upgrades\&. Sometimes, it might be helpful as a heavy\-weight
\fBdaemon\-reload\fR\&. While the daemon is being reexecuted, all sockets systemd listening on behalf of user configuration will stay accessible\&.
.RE
.SS "System Commands"
.PP
\fBis\-system\-running\fR
.RS 4
Checks whether the system is operational\&. This returns success when the system is fully up and running, meaning not in startup, shutdown or maintenance mode\&. Failure is returned otherwise\&. In addition, the current state is printed in a short string to standard output, see table below\&. Use
\fB\-\-quiet\fR
to suppress this output\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&2.\ \&Manager Operational States
.TS
allbox tab(:);
lB lB.
T{
Name
T}:T{
Description
T}
.T&
l l
l l
l l
l l
l l
l l.
T{
\fIinitializing\fR
T}:T{
Early bootup, before
basic\&.target
is reached or the
\fImaintenance\fR
state entered\&.
T}
T{
\fIstarting\fR
T}:T{
Late bootup, before the job queue becomes idle for the first time, or one of the rescue targets are reached\&.
T}
T{
\fIrunning\fR
T}:T{
The system is fully operational\&.
T}
T{
\fIdegraded\fR
T}:T{
The system is operational but one or more units failed\&.
T}
T{
\fImaintenance\fR
T}:T{
The rescue or emergency target is active\&.
T}
T{
\fIstopping\fR
T}:T{
The manager is shutting down\&.
T}
.TE
.sp 1
.RE
.PP
\fBdefault\fR
.RS 4
Enter default mode\&. This is mostly equivalent to
\fBisolate default\&.target\fR\&.
.RE
.PP
\fBrescue\fR
.RS 4
Enter rescue mode\&. This is mostly equivalent to
\fBisolate rescue\&.target\fR, but also prints a wall message to all users\&.
.RE
.PP
\fBemergency\fR
.RS 4
Enter emergency mode\&. This is mostly equivalent to
\fBisolate emergency\&.target\fR, but also prints a wall message to all users\&.
.RE
.PP
\fBhalt\fR
.RS 4
Shut down and halt the system\&. This is mostly equivalent to
\fBstart halt\&.target \-\-job\-mode=replace\-irreversibly\fR, but also prints a wall message to all users\&. If combined with
\fB\-\-force\fR, shutdown of all running services is skipped, however all processes are killed and all file systems are unmounted or mounted read\-only, immediately followed by the system halt\&. If
\fB\-\-force\fR
is specified twice, the operation is immediately executed without terminating any processes or unmounting any file systems\&. This may result in data loss\&.
.RE
.PP
\fBpoweroff\fR
.RS 4
Shut down and power\-off the system\&. This is mostly equivalent to
\fBstart poweroff\&.target \-\-job\-mode=replace\-irreversibly\fR, but also prints a wall message to all users\&. If combined with
\fB\-\-force\fR, shutdown of all running services is skipped, however all processes are killed and all file systems are unmounted or mounted read\-only, immediately followed by the powering off\&. If
\fB\-\-force\fR
is specified twice, the operation is immediately executed without terminating any processes or unmounting any file systems\&. This may result in data loss\&.
.RE
.PP
\fBreboot \fR\fB[\fIarg\fR]\fR
.RS 4
Shut down and reboot the system\&. This is mostly equivalent to
\fBstart reboot\&.target \-\-job\-mode=replace\-irreversibly\fR, but also prints a wall message to all users\&. If combined with
\fB\-\-force\fR, shutdown of all running services is skipped, however all processes are killed and all file systems are unmounted or mounted read\-only, immediately followed by the reboot\&. If
\fB\-\-force\fR
is specified twice, the operation is immediately executed without terminating any processes or unmounting any file systems\&. This may result in data loss\&.
.sp
If the optional argument
\fIarg\fR
is given, it will be passed as the optional argument to the
\fBreboot\fR(2)
system call\&. The value is architecture and firmware specific\&. As an example,
"recovery"
might be used to trigger system recovery, and
"fota"
might be used to trigger a
\(lqfirmware over the air\(rq
update\&.
.RE
.PP
\fBkexec\fR
.RS 4
Shut down and reboot the system via kexec\&. This is mostly equivalent to
\fBstart kexec\&.target \-\-job\-mode=replace\-irreversibly\fR, but also prints a wall message to all users\&. If combined with
\fB\-\-force\fR, shutdown of all running services is skipped, however all processes are killed and all file systems are unmounted or mounted read\-only, immediately followed by the reboot\&.
.RE
.PP
\fBexit\fR
.RS 4
Ask the systemd manager to quit\&. This is only supported for user service managers (i\&.e\&. in conjunction with the
\fB\-\-user\fR
option) and will fail otherwise\&.
.RE
.PP
\fBswitch\-root \fR\fB\fIROOT\fR\fR\fB \fR\fB[\fIINIT\fR]\fR
.RS 4
Switches to a different root directory and executes a new system manager process below it\&. This is intended for usage in initial RAM disks ("initrd"), and will transition from the initrd\*(Aqs system manager process (a\&.k\&.a "init" process) to the main system manager process\&. This call takes two arguments: the directory that is to become the new root directory, and the path to the new system manager binary below it to execute as PID 1\&. If the latter is omitted or the empty string, a systemd binary will automatically be searched for and used as init\&. If the system manager path is omitted or equal to the empty string, the state of the initrd\*(Aqs system manager process is passed to the main system manager, which allows later introspection of the state of the services involved in the initrd boot\&.
.RE
.PP
\fBsuspend\fR
.RS 4
Suspend the system\&. This will trigger activation of the special
suspend\&.target
target\&.
.RE
.PP
\fBhibernate\fR
.RS 4
Hibernate the system\&. This will trigger activation of the special
hibernate\&.target
target\&.
.RE
.PP
\fBhybrid\-sleep\fR
.RS 4
Hibernate and suspend the system\&. This will trigger activation of the special
hybrid\-sleep\&.target
target\&.
.RE
.SS "Parameter Syntax"
.PP
Unit commands listed above take either a single unit name (designated as
\fINAME\fR), or multiple unit specifications (designated as
\fIPATTERN\fR\&.\&.\&.)\&. In the first case, the unit name with or without a suffix must be given\&. If the suffix is not specified, systemctl will append a suitable suffix,
"\&.service"
by default, and a type\-specific suffix in case of commands which operate only on specific unit types\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl start sshd
.fi
.if n \{\
.RE
.\}
.sp
and
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl start sshd\&.service
.fi
.if n \{\
.RE
.\}
.sp
are equivalent, as are
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl isolate default
.fi
.if n \{\
.RE
.\}
.sp
and
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl isolate default\&.target
.fi
.if n \{\
.RE
.\}
.sp
Note that (absolute) paths to device nodes are automatically converted to device unit names, and other (absolute) paths to mount unit names\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl status /dev/sda
# systemctl status /home
.fi
.if n \{\
.RE
.\}
.sp
are equivalent to:
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl status dev\-sda\&.device
# systemctl status home\&.mount
.fi
.if n \{\
.RE
.\}
.sp
In the second case, shell\-style globs will be matched against currently loaded units; literal unit names, with or without a suffix, will be treated as in the first case\&. This means that literal unit names always refer to exactly one unit, but globs may match zero units and this is not considered an error\&.
.PP
Glob patterns use
\fBfnmatch\fR(3), so normal shell\-style globbing rules are used, and
"*",
"?",
"[]"
may be used\&. See
\fBglob\fR(7)
for more details\&. The patterns are matched against the names of currently loaded units, and patterns which do not match anything are silently skipped\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl stop sshd@*\&.service
.fi
.if n \{\
.RE
.\}
.sp
will stop all
sshd@\&.service
instances\&.
.PP
For unit file commands, the specified
\fINAME\fR
should be the full name of the unit file, or the absolute path to the unit file:
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl enable foo\&.service
.fi
.if n \{\
.RE
.\}
.sp
or
.sp
.if n \{\
.RS 4
.\}
.nf
# systemctl link /path/to/foo\&.service
.fi
.if n \{\
.RE
.\}
.sp
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "ENVIRONMENT"
.PP
\fI$SYSTEMD_EDITOR\fR
.RS 4
Editor to use when editing units; overrides
\fI$EDITOR\fR
and
\fI$VISUAL\fR\&. If neither
\fI$SYSTEMD_EDITOR\fR
nor
\fI$EDITOR\fR
nor
\fI$VISUAL\fR
are present or if it is set to an empty string or if their execution failed, systemctl will try to execute well known editors in this order:
\fBnano\fR(1),
\fBvim\fR(1),
\fBvi\fR(1)\&.
.RE
.PP
\fI$SYSTEMD_PAGER\fR
.RS 4
Pager to use when
\fB\-\-no\-pager\fR
is not given; overrides
\fI$PAGER\fR\&. Setting this to an empty string or the value
"cat"
is equivalent to passing
\fB\-\-no\-pager\fR\&.
.RE
.PP
\fI$SYSTEMD_LESS\fR
.RS 4
Override the default options passed to
\fBless\fR
("FRSXMK")\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBjournalctl\fR(1),
\fBloginctl\fR(1),
\fBmachinectl\fR(1),
\fBsystemd.unit\fR(5),
\fBsystemd.resource-control\fR(5),
\fBsystemd.special\fR(7),
\fBwall\fR(1),
\fBsystemd.preset\fR(5),
\fBsystemd.generator\fR(7),
\fBglob\fR(7)
.SH "NOTES"
.IP " 1." 4
Preset
.RS 4
\%http://freedesktop.org/wiki/Software/systemd/Preset
.RE
