'\" t
.TH "SYSTEMD\-SLEEP\&.CONF" "5" "" "systemd 215" "systemd-sleep.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
systemd-sleep.conf \- Suspend and hibernation configuration file
.SH "SYNOPSIS"
.PP
/etc/systemd/sleep\&.conf
.SH "DESCRIPTION"
.PP
\fBsystemd\fR
supports three general power\-saving modes:
.PP
suspend
.RS 4
a low\-power state where execution of the OS is paused, and complete power loss might result in lost data, and which is fast to enter and exit\&. This corresponds to suspend, standby, or freeze states as understood by the kernel\&.
.RE
.PP
hibernate
.RS 4
a low\-power state where execution of the OS is paused, and complete power loss does not result in lost data, and which might be slow to enter and exit\&. This corresponds to the hibernation as understood by the kernel\&.
.RE
.PP
hybrid\-sleep
.RS 4
a low\-power state where execution of the OS is paused, which might be slow to enter, and on complete power loss does not result in lost data but might be slower to exit in that case\&. This mode is called suspend\-to\-both by the kernel\&.
.RE
.PP
Settings in this file determine what strings will be written to
/sys/power/disk
and
/sys/power/state
by
\fBsystemd-sleep\fR(8)
when
\fBsystemd\fR(1)
attempts to suspend or hibernate the machine\&.
.SH "OPTIONS"
.PP
The following options can be configured in the
"[Sleep]"
section of
/etc/systemd/sleep\&.conf:
.PP
\fISuspendMode=\fR, \fIHibernateMode=\fR, \fIHybridSleepMode=\fR
.RS 4
The string to be written to
/sys/power/disk
by, respectively,
\fBsystemd-suspend.service\fR(8),
\fBsystemd-hibernate.service\fR(8), or
\fBsystemd-hybrid-sleep.service\fR(8)\&. More than one value can be specified by separating multiple values with whitespace\&. They will be tried in turn, until one is written without error\&. If neither succeeds, the operation will be aborted\&.
.RE
.PP
\fISuspendState=\fR, \fIHibernateState=\fR, \fIHybridSleepState=\fR
.RS 4
The string to be written to
/sys/power/state
by, respectively,
\fBsystemd-suspend.service\fR(8),
\fBsystemd-hibernate.service\fR(8), or
\fBsystemd-hybrid-sleep.service\fR(8)\&. More than one value can be specified by separating multiple values with whitespace\&. They will be tried in turn, until one is written without error\&. If neither succeeds, the operation will be aborted\&.
.RE
.SH "EXAMPLE: FREEZE"
.PP
Example: to exploit the
\(lqfreeze\(rq
mode added in Linux 3\&.9, one can use
\fBsystemctl suspend\fR
with
.sp
.if n \{\
.RS 4
.\}
.nf
[Sleep]
SuspendState=freeze
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd-sleep\fR(8),
\fBsystemd-suspend.service\fR(8),
\fBsystemd-hibernate.service\fR(8),
\fBsystemd-hybrid-sleep.service\fR(8),
\fBsystemd\fR(1),
\fBsystemd.directives\fR(7)
