'\" t
.TH "TELINIT" "8" "" "systemd 220" "telinit"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
telinit \- Change SysV runlevel
.SH "SYNOPSIS"
.HP \w'\fBtelinit\ \fR\fB[OPTIONS...]\fR\fB\ \fR\fB{COMMAND}\fR\ 'u
\fBtelinit \fR\fB[OPTIONS...]\fR\fB \fR\fB{COMMAND}\fR
.SH "DESCRIPTION"
.PP
\fBtelinit\fR
may be used to change the SysV system runlevel\&. Since the concept of SysV runlevels is obsolete the runlevel requests will be transparently translated into systemd unit activation requests\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-no\-wall\fR
.RS 4
Do not send wall message before reboot/halt/power\-off\&.
.RE
.PP
The following commands are understood:
.PP
\fB0\fR
.RS 4
Power\-off the machine\&. This is translated into an activation request for
poweroff\&.target
and is equivalent to
\fBsystemctl poweroff\fR\&.
.RE
.PP
\fB6\fR
.RS 4
Reboot the machine\&. This is translated into an activation request for
reboot\&.target
and is equivalent to
\fBsystemctl reboot\fR\&.
.RE
.PP
\fB2\fR, \fB3\fR, \fB4\fR, \fB5\fR
.RS 4
Change the SysV runlevel\&. This is translated into an activation request for
runlevel2\&.target,
runlevel3\&.target, \&.\&.\&. and is equivalent to
\fBsystemctl isolate runlevel2\&.target\fR,
\fBsystemctl isolate runlevel3\&.target\fR, \&.\&.\&.
.RE
.PP
\fB1\fR, \fBs\fR, \fBS\fR
.RS 4
Change into system rescue mode\&. This is translated into an activation request for
rescue\&.target
and is equivalent to
\fBsystemctl rescue\fR\&.
.RE
.PP
\fBq\fR, \fBQ\fR
.RS 4
Reload daemon configuration\&. This is equivalent to
\fBsystemctl daemon\-reload\fR\&.
.RE
.PP
\fBu\fR, \fBU\fR
.RS 4
Serialize state, reexecute daemon and deserialize state again\&. This is equivalent to
\fBsystemctl daemon\-reexec\fR\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "NOTES"
.PP
This is a legacy command available for compatibility only\&. It should not be used anymore, as the concept of runlevels is obsolete\&.
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemctl\fR(1),
\fBwall\fR(1)
