'\" t
.TH "TIMEDATECTL" "1" "" "systemd 220" "timedatectl"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
timedatectl \- Control the system time and date
.SH "SYNOPSIS"
.HP \w'\fBtimedatectl\ \fR\fB[OPTIONS...]\fR\fB\ \fR\fB{COMMAND}\fR\ 'u
\fBtimedatectl \fR\fB[OPTIONS...]\fR\fB \fR\fB{COMMAND}\fR
.SH "DESCRIPTION"
.PP
\fBtimedatectl\fR
may be used to query and change the system clock and its settings\&.
.PP
Use
\fBsystemd-firstboot\fR(1)
to initialize the system time zone for mounted (but not booted) system images\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fB\-\-no\-ask\-password\fR
.RS 4
Do not query the user for authentication for privileged operations\&.
.RE
.PP
\fB\-\-adjust\-system\-clock\fR
.RS 4
If
\fBset\-local\-rtc\fR
is invoked and this option is passed, the system clock is synchronized from the RTC again, taking the new setting into account\&. Otherwise, the RTC is synchronized from the system clock\&.
.RE
.PP
\fB\-H\fR, \fB\-\-host=\fR
.RS 4
Execute the operation remotely\&. Specify a hostname, or a username and hostname separated by
"@", to connect to\&. The hostname may optionally be suffixed by a container name, separated by
":", which connects directly to a specific container on the specified host\&. This will use SSH to talk to the remote machine manager instance\&. Container names may be enumerated with
\fBmachinectl \-H \fR\fB\fIHOST\fR\fR\&.
.RE
.PP
\fB\-M\fR, \fB\-\-machine=\fR
.RS 4
Execute operation on a local container\&. Specify a container name to connect to\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print a short version string and exit\&.
.RE
.PP
\fB\-\-no\-pager\fR
.RS 4
Do not pipe output into a pager\&.
.RE
.PP
The following commands are understood:
.PP
\fBstatus\fR
.RS 4
Show current settings of the system clock and RTC, including whether network time synchronization is on\&. Note that whether network time synchronization is on simply reflects whether the
systemd\-timesyncd\&.service
unit is enabled\&. Even if this command shows the status as off a different service might still synchronize the clock with the network\&.
.RE
.PP
\fBset\-time [TIME]\fR
.RS 4
Set the system clock to the specified time\&. This will also update the RTC time accordingly\&. The time may be specified in the format "2012\-10\-30 18:17:16"\&.
.RE
.PP
\fBset\-timezone [TIMEZONE]\fR
.RS 4
Set the system time zone to the specified value\&. Available timezones can be listed with
\fBlist\-timezones\fR\&. If the RTC is configured to be in the local time, this will also update the RTC time\&. This call will alter the
/etc/localtime
symlink\&. See
\fBlocaltime\fR(5)
for more information\&.
.RE
.PP
\fBlist\-timezones\fR
.RS 4
List available time zones, one per line\&. Entries from the list can be set as the system timezone with
\fBset\-timezone\fR\&.
.RE
.PP
\fBset\-local\-rtc [BOOL]\fR
.RS 4
Takes a boolean argument\&. If
"0", the system is configured to maintain the RTC in universal time\&. If
"1", it will maintain the RTC in local time instead\&. Note that maintaining the RTC in the local timezone is not fully supported and will create various problems with time zone changes and daylight saving adjustments\&. If at all possible, keep the RTC in UTC mode\&. Note that invoking this will also synchronize the RTC from the system clock, unless
\fB\-\-adjust\-system\-clock\fR
is passed (see above)\&. This command will change the 3rd line of
/etc/adjtime, as documented in
\fBhwclock\fR(8)\&.
.RE
.PP
\fBset\-ntp [BOOL]\fR
.RS 4
Takes a boolean argument\&. Controls whether network time synchronization is enabled (if available)\&. This enables or disables the
systemd\-timesyncd\&.service
unit\&. Note that even if this command turns time synchronization off a different system service might still synchronize the clock with the network\&.
.RE
.SH "EXIT STATUS"
.PP
On success, 0 is returned, a non\-zero failure code otherwise\&.
.SH "ENVIRONMENT"
.PP
\fI$SYSTEMD_PAGER\fR
.RS 4
Pager to use when
\fB\-\-no\-pager\fR
is not given; overrides
\fI$PAGER\fR\&. Setting this to an empty string or the value
"cat"
is equivalent to passing
\fB\-\-no\-pager\fR\&.
.RE
.PP
\fI$SYSTEMD_LESS\fR
.RS 4
Override the default options passed to
\fBless\fR
("FRSXMK")\&.
.RE
.SH "EXAMPLES"
.PP
Show current settings:
.sp
.if n \{\
.RS 4
.\}
.nf
$ timedatectl
      Local time: Di 2015\-04\-07 16:26:56 CEST
  Universal time: Di 2015\-04\-07 14:26:56 UTC
        RTC time: Di 2015\-04\-07 14:26:56
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
.fi
.if n \{\
.RE
.\}
.PP
Enable network time synchronization:
.sp
.if n \{\
.RS 4
.\}
.nf
$ timedatectl set\-ntp true
==== AUTHENTICATING FOR org\&.freedesktop\&.timedate1\&.set\-ntp ===
Authentication is required to control whether network time synchronization shall be enabled\&.
Authenticating as: user
Password: ********
==== AUTHENTICATION COMPLETE ===
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ systemctl status systemd\-timesyncd\&.service
● systemd\-timesyncd\&.service \- Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd\-timesyncd\&.service; enabled)
   Active: active (running) since Mo 2015\-03\-30 14:20:38 CEST; 5s ago
     Docs: man:systemd\-timesyncd\&.service(8)
 Main PID: 595 (systemd\-timesyn)
   Status: "Using Time Server 216\&.239\&.38\&.15:123 (time4\&.google\&.com)\&."
   CGroup: /system\&.slice/systemd\-timesyncd\&.service
           └─595 /usr/lib/systemd/systemd\-timesyncd
\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBhwclock\fR(8),
\fBdate\fR(1),
\fBlocaltime\fR(5),
\fBsystemctl\fR(1),
\fBsystemd-timedated.service\fR(8),
\fBsystemd-timesyncd.service\fR(8),
\fBsystemd-firstboot\fR(1)
