'\" t
.TH "UDEV_ENUMERATE_NEW" "3" "" "systemd 221" "udev_enumerate_new"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
udev_enumerate_new, udev_enumerate_ref, udev_enumerate_unref \- Create, acquire and release a udev enumerate object
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <libudev\&.h>
.fi
.ft
.HP \w'struct\ udev_enumerate\ *udev_enumerate_new('u
.BI "struct udev_enumerate *udev_enumerate_new(struct\ udev\ *" "udev" ");"
.HP \w'struct\ udev_enumerate\ *udev_enumerate_ref('u
.BI "struct udev_enumerate *udev_enumerate_ref(struct\ udev_enumerate\ *" "udev_enumerate" ");"
.HP \w'struct\ udev_enumerate\ *udev_enumerate_unref('u
.BI "struct udev_enumerate *udev_enumerate_unref(struct\ udev_enumerate\ *" "udev_enumerate" ");"
.SH "RETURN VALUE"
.PP
On success,
\fBudev_enumerate_new()\fR
returns a pointer to the allocated udev monitor\&. On failure,
\fBNULL\fR
is returned\&.
\fBudev_enumerate_ref()\fR
returns the argument that it was passed, unmodified\&.
\fBudev_enumerate_unref()\fR
always returns
\fBNULL\fR\&.
.SH "SEE ALSO"
.PP
\fBudev_new\fR(3),
\fBudev_device_new_from_syspath\fR(3),
\fBudev_enumerate_add_match_subsystem\fR(3),
\fBudev_enumerate_scan_devices\fR(3),
\fBudev_monitor_new_from_netlink\fR(3),
\fBudev_list_entry\fR(3),
\fBsystemd\fR(1),
