'\" t
.TH "UDEV_LIST_ENTRY" "3" "" "systemd 221" "udev_list_entry"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
udev_list_entry, udev_list_entry_get_next, udev_list_entry_get_by_name, udev_list_entry_get_name, udev_list_entry_get_value \- Iterate and access udev lists
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <libudev\&.h>
.fi
.ft
.HP \w'struct\ udev_list_entry\ *udev_list_entry_get_next('u
.BI "struct udev_list_entry *udev_list_entry_get_next(struct\ udev_list_entry\ *" "list_entry" ");"
.HP \w'struct\ udev_list_entry\ *udev_list_entry_get_by_name('u
.BI "struct udev_list_entry *udev_list_entry_get_by_name(struct\ udev_list_entry\ *" "list_entry" ", const\ char\ *" "name" ");"
.HP \w'const\ char\ *udev_list_entry_get_name('u
.BI "const char *udev_list_entry_get_name(struct\ udev_list_entry\ *" "list_entry" ");"
.HP \w'const\ char\ *udev_list_entry_get_value('u
.BI "const char *udev_list_entry_get_value(struct\ udev_list_entry\ *" "list_entry" ");"
.SH "RETURN VALUE"
.PP
On success,
\fBudev_list_entry_get_next()\fR
and
\fBudev_list_entry_get_by_name()\fR
return a pointer to the requested list entry\&. If no such entry can be found, or on failure,
\fBNULL\fR
is returned\&.
.PP
On success,
\fBudev_list_entry_get_name()\fR
and
\fBudev_list_entry_get_value()\fR
return a pointer to a constant string representing the requested value\&. The string is bound to the lifetime of the list\-entry itself\&. On failure,
\fBNULL\fR
is returned\&.
.SH "SEE ALSO"
.PP
\fBudev_new\fR(3),
\fBudev_device_new_from_syspath\fR(3),
\fBudev_enumerate_new\fR(3),
\fBudev_monitor_new_from_netlink\fR(3),
\fBsystemd\fR(1),
