'\" t
.TH "VCONSOLE\&.CONF" "5" "" "systemd 221" "vconsole.conf"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vconsole.conf \- Configuration file for the virtual console
.SH "SYNOPSIS"
.PP
/etc/vconsole\&.conf
.SH "DESCRIPTION"
.PP
The
/etc/vconsole\&.conf
file configures the virtual console, i\&.e\&. keyboard mapping and console font\&. It is applied at boot by
\fBsystemd-vconsole-setup.service\fR(8)\&.
.PP
The basic file format of the
vconsole\&.conf
is a newline\-separated list of environment\-like shell\-compatible variable assignments\&. It is possible to source the configuration from shell scripts, however, beyond mere variable assignments no shell features are supported, allowing applications to read the file without implementing a shell compatible execution engine\&.
.PP
Note that the kernel command line options
\fIvconsole\&.keymap=\fR,
\fIvconsole\&.keymap\&.toggle=\fR,
\fIvconsole\&.font=\fR,
\fIvconsole\&.font\&.map=\fR,
\fIvconsole\&.font\&.unimap=\fR
may be used to override the console settings at boot\&.
.PP
Depending on the operating system other configuration files might be checked for configuration of the virtual console as well, however only as fallback\&.
.SH "OPTIONS"
.PP
The following options are understood:
.PP
\fIKEYMAP=\fR, \fIKEYMAP_TOGGLE=\fR
.RS 4
Configures the key mapping table for the keyboard\&.
\fIKEYMAP=\fR
defaults to
"us"
if not set\&. The
\fIKEYMAP_TOGGLE=\fR
can be used to configure a second toggle keymap and is by default unset\&.
.RE
.PP
\fIFONT=\fR, \fIFONT_MAP=\fR, \fIFONT_UNIMAP=\fR
.RS 4
Configures the console font, the console map and the unicode font map\&.
.RE
.SH "EXAMPLE"
.PP
\fBExample\ \&1.\ \&German keyboard and console\fR
.PP
/etc/vconsole\&.conf:
.sp
.if n \{\
.RS 4
.\}
.nf
KEYMAP=de\-latin1
FONT=eurlatgr
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBsystemd\fR(1),
\fBsystemd-vconsole-setup.service\fR(8),
\fBloadkeys\fR(1),
\fBsetfont\fR(8),
\fBlocale.conf\fR(5),
\fBsystemd-localed.service\fR(8)
