#!/bin/sh
set -e

if ! ORIG_LOC=`grep -v '^#' /etc/default/locale`; then
    # set up for a minimal unconfigured system
    if [ -e /etc/locale.gen ]; then
        echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    fi
    locale-gen en_US.UTF-8
    ORIG_LOC='LANG="en_US.UTF-8"'
    echo "$ORIG_LOC" > /etc/default/locale
fi

if ! [ -e /etc/default/keyboard ]; then
    /bin/echo -e 'XKBMODEL=us\nXKBLAYOUT=pc105' > /etc/default/keyboard
fi

# should activate daemon and work
STATUS=`localectl`
echo "$STATUS" | grep -q "System Locale:"

# change locale
OUT=`localectl set-locale LANG=C LC_CTYPE=en_US.UTF-8 2>&1`
[ -z "$OUT" ]
sync
[ "`cat /etc/default/locale`" = "LANG=C
LC_CTYPE=en_US.UTF-8" ]

! [ -f /etc/locale.conf ]

STATUS=`localectl`
echo "$STATUS" | grep -q "System Locale: LANG=C"
echo "$STATUS" | grep -q "LC_CTYPE=en_US.UTF-8"

# reset locale to original
echo "$ORIG_LOC" > /etc/default/locale
