#!/bin/sh
# autopkgtest check: Run upstream udev test script
# (C) 2016 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
set -euC

TEST_DIR=${ADTTMP:=$(mktemp -d)}
mkdir -p $TEST_DIR/test
tar -C $TEST_DIR/test -xf test/sys.tar.xz
cp test/udev-test.pl $TEST_DIR
cp /usr/lib/*/test-udev $TEST_DIR
cd $TEST_DIR
./udev-test.pl
