#!/bin/sh
# build source package for current upstream master
# Author: Martin Pitt <martin.pitt@ubuntu.com>
set -e

UPSTREAM_GIT=${UPSTREAM_GIT:-https://github.com/systemd/systemd.git}
PATCH="patch --force -p1 --no-backup-if-mismatch"

###############################################################
# create upstream checkout in debian/tmp/upstream-master/

DEBIAN_DIR=$(dirname $(dirname $(readlink -f $0)))
ROOT_DIR=$(dirname "$DEBIAN_DIR")
[ -e "$DEBIAN_DIR/control" ] || { echo "ERROR: $DEBIAN_DIR/control does not exist" >&2; exit 1; }
rm -rf "$ROOT_DIR/pkg-upstream-master"
mkdir "$ROOT_DIR/pkg-upstream-master"
SRCDIR="$ROOT_DIR/pkg-upstream-master/systemd"
git clone "$UPSTREAM_GIT" "$SRCDIR"

# copy packaging
cp -r "$DEBIAN_DIR" "$SRCDIR"
cd "$SRCDIR"

# add changelog
cat << EOF > debian/changelog.new
systemd (220+upstream$(date +'%Y%m%d')-0) UNRELEASED; urgency=low

  * Automatic build from upstream trunk.

 -- Upstream master build <pkg-systemd-maintainers@lists.alioth.debian.org>  $(date -R)
EOF
cat debian/changelog >> debian/changelog.new
mv debian/changelog.new debian/changelog

###############################################################
# apply Debian patches, filter out unwanted ones, skip backported upstream ones

rm -r debian/patches
BLACKLIST="Disable-tests-which-fail-on-buildds.patch
util-Add-hidden-suffixes-for-ucf.patch
"
for p in $(grep -A10000 '^## Debian' $DEBIAN_DIR/patches/series |grep -v ^#); do
    if echo "$BLACKLIST" | grep -qF "$p"; then
        echo "-- Ignoring patch $p"
    elif [ -e "$DEBIAN_DIR/patches/upstream-master/$p" ]; then
        echo "-- Applying overridden patch $p..."
        $PATCH < "$DEBIAN_DIR/patches/upstream-master/$p"
    else
        echo "-- Applying original patch $p..."
        $PATCH < "$DEBIAN_DIR/patches/$p"
    fi
done

###############################################################
# permanent packaging adjustments

echo "-- Applying packaging adjustments..."
set -x


# disable strict symbol files checks
sed -i '/dh_makeshlibs/ s/-c4//' debian/rules

# no orig tarball
echo '1.0' > debian/source/format

###############################################################
# packaging adjustments for next upstream release 221

# gtk-doc got removed
sed -i '/gtkdocize/d' debian/rules
sed -i '/gtk-doc/d' debian/libudev-dev.install

###############################################################
# upstream build system bug workarouds

echo build-deb/src/core/org.freedesktop.systemd1.policy.in >> po/POTFILES.skip

$PATCH < "$DEBIAN_DIR/patches/upstream-master/Revert-build-sys-make-man-systemd.directives.xml-dep.patch"

###############################################################
# build source package

set +x
dpkg-buildpackage -S -d -us -uc -nc
