# systemd-journal-upload
etc/systemd/journal-upload.conf
lib/systemd/systemd-journal-upload
lib/systemd/system/systemd-journal-upload.service

# systemd-journal-remote
etc/systemd/journal-remote.conf
lib/systemd/systemd-journal-remote
usr/lib/tmpfiles.d/systemd-remote.conf
usr/share/man/man8/systemd-journal-remote.8
usr/share/man/man5/journal-remote.conf.d.5
usr/share/man/man5/journal-remote.conf.5

# systemd-journal-gatewayd
lib/systemd/systemd-journal-gatewayd
lib/systemd/system/systemd-journal-gatewayd.service
lib/systemd/system/systemd-journal-gatewayd.socket
usr/share/systemd/gatewayd/
usr/share/man/man8/systemd-journal-gatewayd.service.8
usr/share/man/man8/systemd-journal-gatewayd.socket.8
usr/share/man/man8/systemd-journal-gatewayd.8

