#! /bin/sh

set -e

# Clean up the mess we created
if [ "$1" = "purge" ]; then
    statedir=/var/lib/systemd
    find $statedir -name "*.symlinks" | while read file ; do
        while read symlink ; do
             rm -f "$symlink"
        done < "$file"
        rm -f "$file"
    done
    rm -f $statedir/enabled-units
    rm -f $statedir/run-debian-enable-units
    rmdir --ignore-fail-on-non-empty $statedir
fi

#DEBHELPER#
